/* Generated by Nim Compiler v1.3.3 */
/*   (c) 2020 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w -g  -I/Users/elcritch/.asdf/installs/nim/devel/lib -I/Volumes/datastore/projects/pt/third-party/spryvm/tests -o /Volumes/datastore/projects/pt/third-party/spryvm/tests/_nimcache/@m..@sspryvm@sspryos.nim.c.o /Volumes/datastore/projects/pt/third-party/spryvm/tests/_nimcache/@m..@sspryvm@sspryos.nim.c */
#define NIM_INTBITS 64

/* section: NIM_merge_HEADERS */

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix

/* section: NIM_merge_FRAME_DEFINES */
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
  
/* section: NIM_merge_FORWARD_TYPES */
typedef struct tyObject_InterpretercolonObjectType___9a9c0PsXJdclNJBQRoT5OKJg tyObject_InterpretercolonObjectType___9a9c0PsXJdclNJBQRoT5OKJg;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ;
typedef struct tyObject_PrimFunccolonObjectType___Bo87RnDP4hF7V59b6rcAxSQ tyObject_PrimFunccolonObjectType___Bo87RnDP4hF7V59b6rcAxSQ;
typedef struct RootObj RootObj;
typedef struct TNimType TNimType;
typedef struct tyObject_BlokcolonObjectType___UIJsSh2kxAc9acGwoSYj4xw tyObject_BlokcolonObjectType___UIJsSh2kxAc9acGwoSYj4xw;
typedef struct tyObject_IntValcolonObjectType___aKHYxZgtDkEcxUVcEIFQ9cA tyObject_IntValcolonObjectType___aKHYxZgtDkEcxUVcEIFQ9cA;
typedef struct tyObject_ValuecolonObjectType___g8KVYO1ugQwf0HiFIjQQzw tyObject_ValuecolonObjectType___g8KVYO1ugQwf0HiFIjQQzw;
typedef struct tyObject_StringValcolonObjectType___OzaVEa2ZspAxtzIz1MQfcA tyObject_StringValcolonObjectType___OzaVEa2ZspAxtzIz1MQfcA;
typedef struct tyObject_StringTableObj__V5PVrt9bIxZEeV7lfvqqtNg tyObject_StringTableObj__V5PVrt9bIxZEeV7lfvqqtNg;
typedef struct tyObject_PrimMethcolonObjectType___7evgxa2ozVE9bj7jSo6ShwQ tyObject_PrimMethcolonObjectType___7evgxa2ozVE9bj7jSo6ShwQ;
typedef struct tyObject_FloatValcolonObjectType___L9aH8mAxkXlo8G9bklAV2LYg tyObject_FloatValcolonObjectType___L9aH8mAxkXlo8G9bklAV2LYg;

/* section: NIM_merge_TYPES */
struct NimStrPayload {NI cap;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {NI len;
NimStrPayload* p;
};
struct TNimType {void* destructor;
NI size;
NI align;
NCSTRING name;
void* traceImpl;
void* disposeImpl;
};
struct RootObj {TNimType* m_type;};
struct tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ {  RootObj Sup;tyObject_BlokcolonObjectType___UIJsSh2kxAc9acGwoSYj4xw* tags;
};
typedef struct {
N_NIMCALL_PTR(tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ*, ClP_0) (tyObject_InterpretercolonObjectType___9a9c0PsXJdclNJBQRoT5OKJg* spry, void* ClE_0);
void* ClE_0;
} tyProc__KzxxW30gLaLhm4JG7rojSg;
struct tyObject_PrimFunccolonObjectType___Bo87RnDP4hF7V59b6rcAxSQ {  tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ Sup;tyProc__KzxxW30gLaLhm4JG7rojSg primitive;
};
struct tyObject_ValuecolonObjectType___g8KVYO1ugQwf0HiFIjQQzw {  tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ Sup;};
struct tyObject_IntValcolonObjectType___aKHYxZgtDkEcxUVcEIFQ9cA {  tyObject_ValuecolonObjectType___g8KVYO1ugQwf0HiFIjQQzw Sup;NI value;
};
typedef N_CLOSURE_PTR(tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ*, TM__3ackGiBPaKXbrLRauqWfiw_4) (tyObject_InterpretercolonObjectType___9a9c0PsXJdclNJBQRoT5OKJg* spry, void* ClE_0);
struct tyObject_StringValcolonObjectType___OzaVEa2ZspAxtzIz1MQfcA {  tyObject_ValuecolonObjectType___g8KVYO1ugQwf0HiFIjQQzw Sup;NimStringV2 value;
};
typedef NU8 tySet_tyEnum_ProcessOption__bnU6W8LhTMnT4JaSWtGlSA;
typedef NimStringV2 tyArray__8ZvwQIddfpj2THRVPsFzIQ[1];
typedef N_CLOSURE_PTR(tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ*, TM__3ackGiBPaKXbrLRauqWfiw_9) (tyObject_InterpretercolonObjectType___9a9c0PsXJdclNJBQRoT5OKJg* spry, void* ClE_0);
struct tyObject_PrimMethcolonObjectType___7evgxa2ozVE9bj7jSo6ShwQ {  tyObject_PrimFunccolonObjectType___Bo87RnDP4hF7V59b6rcAxSQ Sup;};
struct tyObject_FloatValcolonObjectType___L9aH8mAxkXlo8G9bklAV2LYg {  tyObject_ValuecolonObjectType___g8KVYO1ugQwf0HiFIjQQzw Sup;NF value;
};
typedef N_CLOSURE_PTR(tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ*, TM__3ackGiBPaKXbrLRauqWfiw_12) (tyObject_InterpretercolonObjectType___9a9c0PsXJdclNJBQRoT5OKJg* spry, void* ClE_0);
typedef N_CLOSURE_PTR(tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ*, TM__3ackGiBPaKXbrLRauqWfiw_15) (tyObject_InterpretercolonObjectType___9a9c0PsXJdclNJBQRoT5OKJg* spry, void* ClE_0);

/* section: NIM_merge_PROC_HEADERS */
N_LIB_PRIVATE N_NIMCALL(void, makeWord__jieY5gv6B4AaNgmJTiZOCQ)(tyObject_InterpretercolonObjectType___9a9c0PsXJdclNJBQRoT5OKJg* self, NimStringV2 word, tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ* value);
N_LIB_PRIVATE N_NIMCALL(tyObject_PrimFunccolonObjectType___Bo87RnDP4hF7V59b6rcAxSQ*, newPrimFunc__nBoMFEu3I4ov5PqnQKilAA)(tyProc__KzxxW30gLaLhm4JG7rojSg primitive);
N_LIB_PRIVATE N_NIMCALL(tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ*, colonanonymous___KI7MqzNtEmVv9bEmnIB2etA)(tyObject_InterpretercolonObjectType___9a9c0PsXJdclNJBQRoT5OKJg* spry);
N_LIB_PRIVATE N_NIMCALL(void, nossleep)(NI milsecs);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___8eMhTKv1RRUDzX38ucu4fA_2)(tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ** dest, tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ* src);
N_LIB_PRIVATE N_NIMCALL(tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ*, evalArg__7W5SyHus4xS1zyMEKJKT6Q_3)(tyObject_InterpretercolonObjectType___9a9c0PsXJdclNJBQRoT5OKJg* spry);
static N_INLINE(NIM_BOOL, isObj)(TNimType* obj, NCSTRING subclass);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseObjectConversionError)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___9aO1dEPkfhJnKjHT0JFTXpA)(tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ** dest);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem__zxfKBYntu9cBapkhrCOk1fgmemory)(void* a, int v, NI size);
N_LIB_PRIVATE N_NIMCALL(tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ*, colonanonymous___KI7MqzNtEmVv9bEmnIB2etA_2)(tyObject_InterpretercolonObjectType___9a9c0PsXJdclNJBQRoT5OKJg* spry);
N_LIB_PRIVATE N_NIMCALL(tyObject_StringValcolonObjectType___OzaVEa2ZspAxtzIz1MQfcA*, newValue__OB9bX19atRBtyx10acMlkdCg)(NimStringV2 v);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nospexecProcess)(NimStringV2 command, NimStringV2 workingDir, NimStringV2* args, NI argsLen_0, tyObject_StringTableObj__V5PVrt9bIxZEeV7lfvqqtNg* env, tySet_tyEnum_ProcessOption__bnU6W8LhTMnT4JaSWtGlSA options);
N_LIB_PRIVATE N_NIMCALL(tyObject_PrimMethcolonObjectType___7evgxa2ozVE9bj7jSo6ShwQ*, newPrimMeth__7XdBOD8x4C4vz9aR71T9bfkA)(tyProc__KzxxW30gLaLhm4JG7rojSg primitive);
N_LIB_PRIVATE N_NIMCALL(tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ*, colonanonymous___KI7MqzNtEmVv9bEmnIB2etA_3)(tyObject_InterpretercolonObjectType___9a9c0PsXJdclNJBQRoT5OKJg* spry);
N_LIB_PRIVATE N_NIMCALL(NF, cpuTime__9aodCrWXscOGeNVh2cpuZkw_2)(void);
N_LIB_PRIVATE N_NIMCALL(tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ*, evalDo__Zq0aJgqgNre9b5XZwoac2zg)(tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ* self, tyObject_InterpretercolonObjectType___9a9c0PsXJdclNJBQRoT5OKJg* spry);
N_LIB_PRIVATE N_NIMCALL(tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ*, evalArgInfix__7W5SyHus4xS1zyMEKJKT6Q_2)(tyObject_InterpretercolonObjectType___9a9c0PsXJdclNJBQRoT5OKJg* spry);
N_LIB_PRIVATE N_NIMCALL(tyObject_FloatValcolonObjectType___L9aH8mAxkXlo8G9bklAV2LYg*, newValue__f45UdAkwx5Z71KYaltvm9aw)(NF v);
N_LIB_PRIVATE N_NIMCALL(tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ*, colonanonymous___KI7MqzNtEmVv9bEmnIB2etA_4)(tyObject_InterpretercolonObjectType___9a9c0PsXJdclNJBQRoT5OKJg* spry);
N_LIB_PRIVATE N_NIMCALL(NF, epochTime__9aodCrWXscOGeNVh2cpuZkw)(void);

/* section: NIM_merge_DATA */
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__3ackGiBPaKXbrLRauqWfiw_2 = { 5 | NIM_STRLIT_FLAG, "sleep" };
static const NimStringV2 TM__3ackGiBPaKXbrLRauqWfiw_3 = {5, (NimStrPayload*)&TM__3ackGiBPaKXbrLRauqWfiw_2};
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__3ackGiBPaKXbrLRauqWfiw_5 = { 5 | NIM_STRLIT_FLAG, "shell" };
static const NimStringV2 TM__3ackGiBPaKXbrLRauqWfiw_6 = {5, (NimStrPayload*)&TM__3ackGiBPaKXbrLRauqWfiw_5};
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__3ackGiBPaKXbrLRauqWfiw_7 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__3ackGiBPaKXbrLRauqWfiw_8 = {0, (NimStrPayload*)&TM__3ackGiBPaKXbrLRauqWfiw_7};
static const struct {
  NI cap; NIM_CHAR data[12+1];
} TM__3ackGiBPaKXbrLRauqWfiw_10 = { 12 | NIM_STRLIT_FLAG, "cpuTimeToRun" };
static const NimStringV2 TM__3ackGiBPaKXbrLRauqWfiw_11 = {12, (NimStrPayload*)&TM__3ackGiBPaKXbrLRauqWfiw_10};
static const struct {
  NI cap; NIM_CHAR data[9+1];
} TM__3ackGiBPaKXbrLRauqWfiw_13 = { 9 | NIM_STRLIT_FLAG, "timeToRun" };
static const NimStringV2 TM__3ackGiBPaKXbrLRauqWfiw_14 = {9, (NimStrPayload*)&TM__3ackGiBPaKXbrLRauqWfiw_13};

/* section: NIM_merge_VARS */
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_BOOL nimInErrorMode__759bT87luu8XGcbkw13FUjA;

/* section: NIM_merge_PROCS */

#line 541 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
static N_INLINE(void, nimFrame)(TFrame* s) {
#line 542 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	{
#line 542 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
		if (!(framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA3_;

#line 543 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
		(*s).calldepth = ((NI16) 0);	}
	goto LA1_;
	LA3_: ;
	{
#line 546 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"

#line 546 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
		(*s).calldepth = (NI16)((*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1));	}
	LA1_: ;

#line 548 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	(*s).prev = framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
#line 549 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = s;
#line 550 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	{
#line 550 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
		if (!((*s).calldepth == ((NI16) 2000))) goto LA8_;

#line 550 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"

#line 550 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
		callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw();
	}
	LA8_: ;
}

#line 85 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
static N_INLINE(void, popFrame)(void) {
#line 86 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).prev;}

#line 187 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/refs_v2.nim"
static N_INLINE(NIM_BOOL, isObj)(TNimType* obj, NCSTRING subclass) {	NIM_BOOL result;	NCSTRING T1_;	nimfr_("isObj", "/Users/elcritch/.asdf/installs/nim/devel/lib/system/refs_v2.nim");	result = (NIM_BOOL)0;
#line 190 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/refs_v2.nim"
	nimln_(190, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/refs_v2.nim");
#line 190 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/refs_v2.nim"

#line 190 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/refs_v2.nim"

#line 190 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/refs_v2.nim"

#line 190 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/refs_v2.nim"
	T1_ = (NCSTRING)0;	T1_ = strstr((*obj).name, subclass);	result = !((((void*) (T1_)) == NIM_NIL));	popFrame();	return result;}

#line 424 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {	NIM_BOOL* result;	result = (NIM_BOOL*)0;
#line 425 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	result = (&nimInErrorMode__759bT87luu8XGcbkw13FUjA);	return result;}

#line 1351 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryvm.nim"
N_LIB_PRIVATE N_NIMCALL(tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ*, colonanonymous___KI7MqzNtEmVv9bEmnIB2etA)(tyObject_InterpretercolonObjectType___9a9c0PsXJdclNJBQRoT5OKJg* spry) {	tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ* result;	tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ* colontmpD_;	tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ* T2_;NIM_BOOL oldNimErrFin1_;NIM_BOOL* nimErr_;	nimfr_(":anonymous", "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryvm"
".nim");{nimErr_ = nimErrorFlag();	result = (tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ*)0;	colontmpD_ = (tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ*)0;
#line 7 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryos.nim"
	nimln_(7, "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryos"
".nim");
#line 119 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
	nimln_(119, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");
#line 7 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryos.nim"
	nimln_(7, "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryos"
".nim");
#line 7 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryos.nim"
	T2_ = (tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ*)0;	T2_ = evalArg__7W5SyHus4xS1zyMEKJKT6Q_3(spry);	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
#line 119 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
	nimln_(119, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");	eqsink___8eMhTKv1RRUDzX38ucu4fA_2(&colontmpD_, T2_);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;	if (colontmpD_ && !isObj((*colontmpD_).Sup.m_type, "|spryvm.spryvm.IntVal:ObjectType|spryvm.spryvm.Value:ObjectType"
"|spryvm.spryvm.Node:ObjectType|RootObj|")){ raiseObjectConversionError(); goto LA1_;}
#line 7 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryos.nim"
	nimln_(7, "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryos"
".nim");	nossleep((*(*((tyObject_IntValcolonObjectType___aKHYxZgtDkEcxUVcEIFQ9cA**) (&(colontmpD_))))).value);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;	{		LA1_:;	}
	{		oldNimErrFin1_ = *nimErr_; *nimErr_ = NIM_FALSE;
#line 119 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
		nimln_(119, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");
#line 119 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
		eqdestroy___9aO1dEPkfhJnKjHT0JFTXpA(&colontmpD_);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;		*nimErr_ = oldNimErrFin1_;	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}BeforeRet_: ;
	popFrame();	return result;}

#line 22 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/memory.nim"
static N_INLINE(void, nimSetMem__zxfKBYntu9cBapkhrCOk1fgmemory)(void* a, int v, NI size) {	void* T1_;
#line 24 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/memory.nim"

#line 24 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/memory.nim"
	T1_ = (void*)0;	T1_ = memset(a, v, ((size_t) (size)));}

#line 33 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/memory.nim"
static N_INLINE(void, nimZeroMem)(void* p, NI size) {NIM_BOOL* nimErr_;{nimErr_ = nimErrorFlag();
#line 34 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/memory.nim"

#line 34 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/memory.nim"
	nimSetMem__zxfKBYntu9cBapkhrCOk1fgmemory(p, ((int) 0), size);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}BeforeRet_: ;
}

#line 1351 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryvm.nim"
N_LIB_PRIVATE N_NIMCALL(tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ*, colonanonymous___KI7MqzNtEmVv9bEmnIB2etA_2)(tyObject_InterpretercolonObjectType___9a9c0PsXJdclNJBQRoT5OKJg* spry) {	tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ* result;	tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ* colontmpD_;	tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ* T2_;	tyArray__8ZvwQIddfpj2THRVPsFzIQ T3_;	NimStringV2 T4_;	tyObject_StringValcolonObjectType___OzaVEa2ZspAxtzIz1MQfcA* T5_;NIM_BOOL oldNimErrFin1_;NIM_BOOL* nimErr_;	nimfr_(":anonymous", "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryvm"
".nim");{nimErr_ = nimErrorFlag();	result = (tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ*)0;	colontmpD_ = (tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ*)0;
#line 9 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryos.nim"
	nimln_(9, "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryos"
".nim");
#line 9 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryos.nim"

#line 9 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryos.nim"

#line 119 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
	nimln_(119, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");
#line 9 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryos.nim"
	nimln_(9, "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryos"
".nim");
#line 9 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryos.nim"
	T2_ = (tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ*)0;	T2_ = evalArg__7W5SyHus4xS1zyMEKJKT6Q_3(spry);	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
#line 119 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
	nimln_(119, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");	eqsink___8eMhTKv1RRUDzX38ucu4fA_2(&colontmpD_, T2_);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;	if (colontmpD_ && !isObj((*colontmpD_).Sup.m_type, "|spryvm.spryvm.StringVal:ObjectType|spryvm.spryvm.Value:ObjectT"
"ype|spryvm.spryvm.Node:ObjectType|RootObj|")){ raiseObjectConversionError(); goto LA1_;}
#line 9 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryos.nim"
	nimln_(9, "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryos"
".nim");	T4_.len = 0; T4_.p = NIM_NIL;	T4_ = nospexecProcess((*(*((tyObject_StringValcolonObjectType___OzaVEa2ZspAxtzIz1MQfcA**) (&(colontmpD_))))).value, TM__3ackGiBPaKXbrLRauqWfiw_8, T3_, 0, NIM_NIL, 14);	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
#line 9 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryos.nim"
	T5_ = (tyObject_StringValcolonObjectType___OzaVEa2ZspAxtzIz1MQfcA*)0;	T5_ = newValue__OB9bX19atRBtyx10acMlkdCg(T4_);	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;	result = &T5_->Sup.Sup;	{		LA1_:;	}
	{		oldNimErrFin1_ = *nimErr_; *nimErr_ = NIM_FALSE;
#line 119 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
		nimln_(119, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");
#line 119 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
		eqdestroy___9aO1dEPkfhJnKjHT0JFTXpA(&colontmpD_);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;		*nimErr_ = oldNimErrFin1_;	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}BeforeRet_: ;
	popFrame();	return result;}

#line 1355 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryvm.nim"
N_LIB_PRIVATE N_NIMCALL(tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ*, colonanonymous___KI7MqzNtEmVv9bEmnIB2etA_3)(tyObject_InterpretercolonObjectType___9a9c0PsXJdclNJBQRoT5OKJg* spry) {	tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ* result;	tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ* colontmpD_;	tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ* colontmpD__2;	NF t;	tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ* T2_;	tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ* T3_;	NF T4_;	tyObject_FloatValcolonObjectType___L9aH8mAxkXlo8G9bklAV2LYg* T5_;NIM_BOOL oldNimErrFin1_;NIM_BOOL* nimErr_;	nimfr_(":anonymous", "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryvm"
".nim");{nimErr_ = nimErrorFlag();	result = (tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ*)0;	colontmpD_ = (tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ*)0;	colontmpD__2 = (tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ*)0;
#line 11 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryos.nim"
	nimln_(11, "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryos"
".nim");
#line 11 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryos.nim"

#line 11 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryos.nim"
	t = cpuTime__9aodCrWXscOGeNVh2cpuZkw_2();	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
#line 12 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryos.nim"
	nimln_(12, "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryos"
".nim");
#line 119 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
	nimln_(119, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");
#line 12 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryos.nim"
	nimln_(12, "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryos"
".nim");
#line 119 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
	nimln_(119, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");
#line 12 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryos.nim"
	nimln_(12, "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryos"
".nim");
#line 12 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryos.nim"
	T2_ = (tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ*)0;	T2_ = evalArgInfix__7W5SyHus4xS1zyMEKJKT6Q_2(spry);	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
#line 119 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
	nimln_(119, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");	eqsink___8eMhTKv1RRUDzX38ucu4fA_2(&colontmpD_, T2_);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
#line 12 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryos.nim"
	nimln_(12, "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryos"
".nim");	T3_ = (tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ*)0;	T3_ = evalDo__Zq0aJgqgNre9b5XZwoac2zg(colontmpD_, spry);	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
#line 119 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
	nimln_(119, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");	eqsink___8eMhTKv1RRUDzX38ucu4fA_2(&colontmpD__2, T3_);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;	(void)(colontmpD__2);

#line 13 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryos.nim"
	nimln_(13, "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryos"
".nim");
#line 13 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryos.nim"

#line 13 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryos.nim"

#line 13 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryos.nim"

#line 13 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryos.nim"
	T4_ = (NF)0;	T4_ = cpuTime__9aodCrWXscOGeNVh2cpuZkw_2();	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
#line 13 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryos.nim"
	T5_ = (tyObject_FloatValcolonObjectType___L9aH8mAxkXlo8G9bklAV2LYg*)0;	T5_ = newValue__f45UdAkwx5Z71KYaltvm9aw(((NF)(((NF)(T4_) - (NF)(t))) * (NF)(1.0000000000000000e+03)));	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;	result = &T5_->Sup.Sup;	{		LA1_:;	}
	{		oldNimErrFin1_ = *nimErr_; *nimErr_ = NIM_FALSE;
#line 119 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
		nimln_(119, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");
#line 119 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
		eqdestroy___9aO1dEPkfhJnKjHT0JFTXpA(&colontmpD__2);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
#line 119 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"

#line 119 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
		eqdestroy___9aO1dEPkfhJnKjHT0JFTXpA(&colontmpD_);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;		*nimErr_ = oldNimErrFin1_;	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}BeforeRet_: ;
	popFrame();	return result;}

#line 1355 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryvm.nim"
N_LIB_PRIVATE N_NIMCALL(tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ*, colonanonymous___KI7MqzNtEmVv9bEmnIB2etA_4)(tyObject_InterpretercolonObjectType___9a9c0PsXJdclNJBQRoT5OKJg* spry) {	tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ* result;	tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ* colontmpD_;	tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ* colontmpD__2;	NF t;	tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ* T2_;	tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ* T3_;	NF T4_;	tyObject_FloatValcolonObjectType___L9aH8mAxkXlo8G9bklAV2LYg* T5_;NIM_BOOL oldNimErrFin1_;NIM_BOOL* nimErr_;	nimfr_(":anonymous", "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryvm"
".nim");{nimErr_ = nimErrorFlag();	result = (tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ*)0;	colontmpD_ = (tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ*)0;	colontmpD__2 = (tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ*)0;
#line 15 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryos.nim"
	nimln_(15, "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryos"
".nim");
#line 15 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryos.nim"

#line 15 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryos.nim"
	t = epochTime__9aodCrWXscOGeNVh2cpuZkw();	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
#line 16 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryos.nim"
	nimln_(16, "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryos"
".nim");
#line 119 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
	nimln_(119, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");
#line 16 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryos.nim"
	nimln_(16, "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryos"
".nim");
#line 119 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
	nimln_(119, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");
#line 16 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryos.nim"
	nimln_(16, "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryos"
".nim");
#line 16 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryos.nim"
	T2_ = (tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ*)0;	T2_ = evalArgInfix__7W5SyHus4xS1zyMEKJKT6Q_2(spry);	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
#line 119 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
	nimln_(119, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");	eqsink___8eMhTKv1RRUDzX38ucu4fA_2(&colontmpD_, T2_);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
#line 16 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryos.nim"
	nimln_(16, "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryos"
".nim");	T3_ = (tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ*)0;	T3_ = evalDo__Zq0aJgqgNre9b5XZwoac2zg(colontmpD_, spry);	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
#line 119 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
	nimln_(119, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");	eqsink___8eMhTKv1RRUDzX38ucu4fA_2(&colontmpD__2, T3_);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;	(void)(colontmpD__2);

#line 17 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryos.nim"
	nimln_(17, "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryos"
".nim");
#line 17 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryos.nim"

#line 17 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryos.nim"

#line 17 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryos.nim"

#line 17 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryos.nim"
	T4_ = (NF)0;	T4_ = epochTime__9aodCrWXscOGeNVh2cpuZkw();	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
#line 17 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryos.nim"
	T5_ = (tyObject_FloatValcolonObjectType___L9aH8mAxkXlo8G9bklAV2LYg*)0;	T5_ = newValue__f45UdAkwx5Z71KYaltvm9aw(((NF)(((NF)(T4_) - (NF)(t))) * (NF)(1.0000000000000000e+03)));	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;	result = &T5_->Sup.Sup;	{		LA1_:;	}
	{		oldNimErrFin1_ = *nimErr_; *nimErr_ = NIM_FALSE;
#line 119 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
		nimln_(119, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");
#line 119 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
		eqdestroy___9aO1dEPkfhJnKjHT0JFTXpA(&colontmpD__2);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
#line 119 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"

#line 119 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
		eqdestroy___9aO1dEPkfhJnKjHT0JFTXpA(&colontmpD_);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;		*nimErr_ = oldNimErrFin1_;	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}BeforeRet_: ;
	popFrame();	return result;}

#line 5 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryos.nim"
N_LIB_PRIVATE N_NIMCALL(void, addOS__2yrMKjWCuWq4nM6P0iiw3A)(tyObject_InterpretercolonObjectType___9a9c0PsXJdclNJBQRoT5OKJg* spry) {	tyProc__KzxxW30gLaLhm4JG7rojSg T1_;	tyObject_PrimFunccolonObjectType___Bo87RnDP4hF7V59b6rcAxSQ* T2_;	tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ* T3_;	tyProc__KzxxW30gLaLhm4JG7rojSg T4_;	tyObject_PrimFunccolonObjectType___Bo87RnDP4hF7V59b6rcAxSQ* T5_;	tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ* T6_;	tyProc__KzxxW30gLaLhm4JG7rojSg T7_;	tyObject_PrimMethcolonObjectType___7evgxa2ozVE9bj7jSo6ShwQ* T8_;	tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ* T9_;	tyProc__KzxxW30gLaLhm4JG7rojSg T10_;	tyObject_PrimMethcolonObjectType___7evgxa2ozVE9bj7jSo6ShwQ* T11_;	tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ* T12_;NIM_BOOL* nimErr_;	nimfr_("addOS", "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryos"
".nim");{nimErr_ = nimErrorFlag();
#line 6 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryos.nim"
	nimln_(6, "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryos"
".nim");
#line 1350 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryvm.nim"
	nimln_(1350, "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryvm"
".nim");	nimZeroMem((void*)(&T1_), sizeof(tyProc__KzxxW30gLaLhm4JG7rojSg));	T1_.ClP_0 = ((TM__3ackGiBPaKXbrLRauqWfiw_4) (colonanonymous___KI7MqzNtEmVv9bEmnIB2etA)); T1_.ClE_0 = NIM_NIL;
#line 1350 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryvm.nim"
	T2_ = (tyObject_PrimFunccolonObjectType___Bo87RnDP4hF7V59b6rcAxSQ*)0;	T2_ = newPrimFunc__nBoMFEu3I4ov5PqnQKilAA(T1_);	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	T3_ = (tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ*)0;	T3_ = &T2_->Sup;
#line 6 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryos.nim"
	nimln_(6, "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryos"
".nim");	makeWord__jieY5gv6B4AaNgmJTiZOCQ(spry, TM__3ackGiBPaKXbrLRauqWfiw_3, T3_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
#line 8 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryos.nim"
	nimln_(8, "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryos"
".nim");
#line 1350 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryvm.nim"
	nimln_(1350, "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryvm"
".nim");	nimZeroMem((void*)(&T4_), sizeof(tyProc__KzxxW30gLaLhm4JG7rojSg));	T4_.ClP_0 = ((TM__3ackGiBPaKXbrLRauqWfiw_9) (colonanonymous___KI7MqzNtEmVv9bEmnIB2etA_2)); T4_.ClE_0 = NIM_NIL;
#line 1350 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryvm.nim"
	T5_ = (tyObject_PrimFunccolonObjectType___Bo87RnDP4hF7V59b6rcAxSQ*)0;	T5_ = newPrimFunc__nBoMFEu3I4ov5PqnQKilAA(T4_);	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	T6_ = (tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ*)0;	T6_ = &T5_->Sup;
#line 8 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryos.nim"
	nimln_(8, "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryos"
".nim");	makeWord__jieY5gv6B4AaNgmJTiZOCQ(spry, TM__3ackGiBPaKXbrLRauqWfiw_6, T6_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
#line 10 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryos.nim"
	nimln_(10, "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryos"
".nim");
#line 1354 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryvm.nim"
	nimln_(1354, "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryvm"
".nim");	nimZeroMem((void*)(&T7_), sizeof(tyProc__KzxxW30gLaLhm4JG7rojSg));	T7_.ClP_0 = ((TM__3ackGiBPaKXbrLRauqWfiw_12) (colonanonymous___KI7MqzNtEmVv9bEmnIB2etA_3)); T7_.ClE_0 = NIM_NIL;
#line 1354 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryvm.nim"
	T8_ = (tyObject_PrimMethcolonObjectType___7evgxa2ozVE9bj7jSo6ShwQ*)0;	T8_ = newPrimMeth__7XdBOD8x4C4vz9aR71T9bfkA(T7_);	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	T9_ = (tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ*)0;	T9_ = &T8_->Sup.Sup;
#line 10 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryos.nim"
	nimln_(10, "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryos"
".nim");	makeWord__jieY5gv6B4AaNgmJTiZOCQ(spry, TM__3ackGiBPaKXbrLRauqWfiw_11, T9_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
#line 14 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryos.nim"
	nimln_(14, "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryos"
".nim");
#line 1354 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryvm.nim"
	nimln_(1354, "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryvm"
".nim");	nimZeroMem((void*)(&T10_), sizeof(tyProc__KzxxW30gLaLhm4JG7rojSg));	T10_.ClP_0 = ((TM__3ackGiBPaKXbrLRauqWfiw_15) (colonanonymous___KI7MqzNtEmVv9bEmnIB2etA_4)); T10_.ClE_0 = NIM_NIL;
#line 1354 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryvm.nim"
	T11_ = (tyObject_PrimMethcolonObjectType___7evgxa2ozVE9bj7jSo6ShwQ*)0;	T11_ = newPrimMeth__7XdBOD8x4C4vz9aR71T9bfkA(T10_);	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	T12_ = (tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ*)0;	T12_ = &T11_->Sup.Sup;
#line 14 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryos.nim"
	nimln_(14, "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryos"
".nim");	makeWord__jieY5gv6B4AaNgmJTiZOCQ(spry, TM__3ackGiBPaKXbrLRauqWfiw_14, T12_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}BeforeRet_: ;
	popFrame();}
