/* Generated by Nim Compiler v1.3.3 */
/*   (c) 2020 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w -g  -I/Users/elcritch/.asdf/installs/nim/devel/lib -I/Volumes/datastore/projects/pt/third-party/spryvm/tests -o /Volumes/datastore/projects/pt/third-party/spryvm/tests/_nimcache/@m..@sspryvm@ssprymemfile.nim.c.o /Volumes/datastore/projects/pt/third-party/spryvm/tests/_nimcache/@m..@sspryvm@ssprymemfile.nim.c */
#define NIM_INTBITS 64

/* section: NIM_merge_HEADERS */

#include "nimbase.h"
#include <stdio.h>
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix

/* section: NIM_merge_FRAME_DEFINES */
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
  
/* section: NIM_merge_FORWARD_TYPES */
typedef struct tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ;
typedef struct tyObject_MemfileNodecolonObjectType___SClUH77NqezEgy7ah1Yt5Q tyObject_MemfileNodecolonObjectType___SClUH77NqezEgy7ah1Yt5Q;
typedef struct tyObject_InterpretercolonObjectType___9a9c0PsXJdclNJBQRoT5OKJg tyObject_InterpretercolonObjectType___9a9c0PsXJdclNJBQRoT5OKJg;
typedef struct RootObj RootObj;
typedef struct TNimType TNimType;
typedef struct tyObject_BlokcolonObjectType___UIJsSh2kxAc9acGwoSYj4xw tyObject_BlokcolonObjectType___UIJsSh2kxAc9acGwoSYj4xw;
typedef struct tyObject_ValuecolonObjectType___g8KVYO1ugQwf0HiFIjQQzw tyObject_ValuecolonObjectType___g8KVYO1ugQwf0HiFIjQQzw;
typedef struct tyObject_MemFile__j4SnXNrJDFBxAz4BlbM9aIQ tyObject_MemFile__j4SnXNrJDFBxAz4BlbM9aIQ;
typedef struct tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_PrimFunccolonObjectType___Bo87RnDP4hF7V59b6rcAxSQ tyObject_PrimFunccolonObjectType___Bo87RnDP4hF7V59b6rcAxSQ;
typedef struct tyObject_StringValcolonObjectType___OzaVEa2ZspAxtzIz1MQfcA tyObject_StringValcolonObjectType___OzaVEa2ZspAxtzIz1MQfcA;
typedef struct tyObject_SeqCompositecolonObjectType___C3SNeoePmbb3Sj78kdPUzA tyObject_SeqCompositecolonObjectType___C3SNeoePmbb3Sj78kdPUzA;
typedef struct tyObject_CompositecolonObjectType___eo4EWNixFqGOnCaaADsXsQ tyObject_CompositecolonObjectType___eo4EWNixFqGOnCaaADsXsQ;
typedef struct tySequence__oulB5IH0TniKuw4AoG3BvA tySequence__oulB5IH0TniKuw4AoG3BvA;
typedef struct tySequence__oulB5IH0TniKuw4AoG3BvA_Content tySequence__oulB5IH0TniKuw4AoG3BvA_Content;
typedef struct tyObject_PrimMethcolonObjectType___7evgxa2ozVE9bj7jSo6ShwQ tyObject_PrimMethcolonObjectType___7evgxa2ozVE9bj7jSo6ShwQ;
typedef struct tyObject_MemSlice__fWlUmmDo9aQGKOHWrhWV54Q tyObject_MemSlice__fWlUmmDo9aQGKOHWrhWV54Q;
typedef struct TNimNode TNimNode;
typedef struct tyObject_ActivationcolonObjectType___jwMMFyLWVLpBU9ca5Dr6Vrw tyObject_ActivationcolonObjectType___jwMMFyLWVLpBU9ca5Dr6Vrw;
typedef struct tyObject_ParsercolonObjectType___9bkpYJZgm7rXSoRQ1xc0nBA tyObject_ParsercolonObjectType___9bkpYJZgm7rXSoRQ1xc0nBA;
typedef struct tyObject_RootActivationcolonObjectType___iVrg9cFaeTAqppeKtHaL8cg tyObject_RootActivationcolonObjectType___iVrg9cFaeTAqppeKtHaL8cg;
typedef struct tyObject_MapcolonObjectType___EsnExRpqJxGuuJFiAD81hg tyObject_MapcolonObjectType___EsnExRpqJxGuuJFiAD81hg;

/* section: NIM_merge_TYPES */
struct TNimType {void* destructor;
NI size;
NI align;
NCSTRING name;
void* traceImpl;
void* disposeImpl;
};
struct RootObj {TNimType* m_type;};
struct tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ {  RootObj Sup;tyObject_BlokcolonObjectType___UIJsSh2kxAc9acGwoSYj4xw* tags;
};
struct tyObject_ValuecolonObjectType___g8KVYO1ugQwf0HiFIjQQzw {  tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ Sup;};
struct tyObject_MemFile__j4SnXNrJDFBxAz4BlbM9aIQ {void* mem;
NI size;
int handle;
int flags;
};
struct tyObject_MemfileNodecolonObjectType___SClUH77NqezEgy7ah1Yt5Q {  tyObject_ValuecolonObjectType___g8KVYO1ugQwf0HiFIjQQzw Sup;tyObject_MemFile__j4SnXNrJDFBxAz4BlbM9aIQ memfile;
};
struct tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A {NI rc;
};
struct NimStrPayload {NI cap;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {NI len;
NimStrPayload* p;
};
typedef struct {
N_NIMCALL_PTR(tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ*, ClP_0) (tyObject_InterpretercolonObjectType___9a9c0PsXJdclNJBQRoT5OKJg* spry, void* ClE_0);
void* ClE_0;
} tyProc__KzxxW30gLaLhm4JG7rojSg;
struct tyObject_PrimFunccolonObjectType___Bo87RnDP4hF7V59b6rcAxSQ {  tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ Sup;tyProc__KzxxW30gLaLhm4JG7rojSg primitive;
};
struct tyObject_StringValcolonObjectType___OzaVEa2ZspAxtzIz1MQfcA {  tyObject_ValuecolonObjectType___g8KVYO1ugQwf0HiFIjQQzw Sup;NimStringV2 value;
};
struct tyObject_CompositecolonObjectType___eo4EWNixFqGOnCaaADsXsQ {  tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ Sup;};
struct tySequence__oulB5IH0TniKuw4AoG3BvA {
  NI len; tySequence__oulB5IH0TniKuw4AoG3BvA_Content* p;
};
struct tyObject_SeqCompositecolonObjectType___C3SNeoePmbb3Sj78kdPUzA {  tyObject_CompositecolonObjectType___eo4EWNixFqGOnCaaADsXsQ Sup;tySequence__oulB5IH0TniKuw4AoG3BvA nodes;
};
struct tyObject_BlokcolonObjectType___UIJsSh2kxAc9acGwoSYj4xw {  tyObject_SeqCompositecolonObjectType___C3SNeoePmbb3Sj78kdPUzA Sup;NI pos;
};
typedef NU8 tyEnum_FileMode__ZJfK20XeZ9bv2j1pZjw9aswg;
typedef N_CLOSURE_PTR(tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ*, TM__pwrqdpRNZbc1rhRZbgtEow_6) (tyObject_InterpretercolonObjectType___9a9c0PsXJdclNJBQRoT5OKJg* spry, void* ClE_0);
struct tyObject_PrimMethcolonObjectType___7evgxa2ozVE9bj7jSo6ShwQ {  tyObject_PrimFunccolonObjectType___Bo87RnDP4hF7V59b6rcAxSQ Sup;};
typedef N_CLOSURE_PTR(tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ*, TM__pwrqdpRNZbc1rhRZbgtEow_9) (tyObject_InterpretercolonObjectType___9a9c0PsXJdclNJBQRoT5OKJg* spry, void* ClE_0);
struct tyObject_MemSlice__fWlUmmDo9aQGKOHWrhWV54Q {void* data;
NI size;
};
struct TNimNode {char dummy;
};
typedef N_CLOSURE_PTR(tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ*, TM__pwrqdpRNZbc1rhRZbgtEow_15) (tyObject_InterpretercolonObjectType___9a9c0PsXJdclNJBQRoT5OKJg* spry, void* ClE_0);
struct tyObject_InterpretercolonObjectType___9a9c0PsXJdclNJBQRoT5OKJg {tyObject_ParsercolonObjectType___9bkpYJZgm7rXSoRQ1xc0nBA* parser;
tyObject_ActivationcolonObjectType___jwMMFyLWVLpBU9ca5Dr6Vrw* currentActivation;
tyObject_RootActivationcolonObjectType___iVrg9cFaeTAqppeKtHaL8cg* rootActivation;
tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ* lastSelf;
tyObject_MapcolonObjectType___EsnExRpqJxGuuJFiAD81hg* root;
tyObject_BlokcolonObjectType___UIJsSh2kxAc9acGwoSYj4xw* modules;
tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ* trueVal;
tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ* falseVal;
tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ* nilVal;
tyObject_BlokcolonObjectType___UIJsSh2kxAc9acGwoSYj4xw* emptyBlok;
tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ* objectTag;
tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ* moduleTag;
};
struct tyObject_ActivationcolonObjectType___jwMMFyLWVLpBU9ca5Dr6Vrw {  tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ Sup;tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ* last;
tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ* self;
NIM_BOOL returned;
tyObject_ActivationcolonObjectType___jwMMFyLWVLpBU9ca5Dr6Vrw* parent;
NI pos;
tyObject_SeqCompositecolonObjectType___C3SNeoePmbb3Sj78kdPUzA* body;
tyObject_SeqCompositecolonObjectType___C3SNeoePmbb3Sj78kdPUzA* catcher;
};
typedef N_CLOSURE_PTR(tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ*, TM__pwrqdpRNZbc1rhRZbgtEow_21) (tyObject_InterpretercolonObjectType___9a9c0PsXJdclNJBQRoT5OKJg* spry, void* ClE_0);


#ifndef tySequence__oulB5IH0TniKuw4AoG3BvA_Content_PP
#define tySequence__oulB5IH0TniKuw4AoG3BvA_Content_PP
struct tySequence__oulB5IH0TniKuw4AoG3BvA_Content { NI cap; tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ* data[SEQ_DECL_SIZE];};
#endif

      
/* section: NIM_merge_PROC_HEADERS */
N_LIB_PRIVATE N_NIMCALL(tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ*, eval__f6XObCfHu6zUMY37KOsgAg)(tyObject_MemfileNodecolonObjectType___SClUH77NqezEgy7ah1Yt5Q* self, tyObject_InterpretercolonObjectType___9a9c0PsXJdclNJBQRoT5OKJg* spry);
N_LIB_PRIVATE N_NIMCALL(void, eq___LIf9anzbADx2Pk8D7rRZkjA)(tyObject_MemfileNodecolonObjectType___SClUH77NqezEgy7ah1Yt5Q** dest, tyObject_MemfileNodecolonObjectType___SClUH77NqezEgy7ah1Yt5Q* src);
static N_INLINE(void, nimIncRef)(void* p);
static N_INLINE(NI, minuspercent___dgYAo7RfdUVVpvkfKDym8wsystem)(NI x, NI y);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p);
N_LIB_PRIVATE N_NIMCALL(void, nimDestroyAndDispose)(void* p);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, makeWord__jieY5gv6B4AaNgmJTiZOCQ)(tyObject_InterpretercolonObjectType___9a9c0PsXJdclNJBQRoT5OKJg* self, NimStringV2 word, tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ* value);
N_LIB_PRIVATE N_NIMCALL(tyObject_PrimFunccolonObjectType___Bo87RnDP4hF7V59b6rcAxSQ*, newPrimFunc__nBoMFEu3I4ov5PqnQKilAA)(tyProc__KzxxW30gLaLhm4JG7rojSg primitive);
N_LIB_PRIVATE N_NIMCALL(tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ*, colonanonymous___dplzm2YJ7bZn9b4A9bfAbXqQ)(tyObject_InterpretercolonObjectType___9a9c0PsXJdclNJBQRoT5OKJg* spry);
N_LIB_PRIVATE N_NIMCALL(void, eq___aBBXmHFBEivKqERloP6zmA_2)(NimStringV2* dest, NimStringV2 src);
N_LIB_PRIVATE N_NIMCALL(tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ*, evalArg__7W5SyHus4xS1zyMEKJKT6Q_3)(tyObject_InterpretercolonObjectType___9a9c0PsXJdclNJBQRoT5OKJg* spry);
static N_INLINE(NIM_BOOL, isObj)(TNimType* obj, NCSTRING subclass);
N_LIB_PRIVATE N_NOINLINE(void, raiseObjectConversionError)(void);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___xh2dJ15yFU7fmHKaAN9awww)(tyObject_MemfileNodecolonObjectType___SClUH77NqezEgy7ah1Yt5Q* dest);
N_LIB_PRIVATE N_NIMCALL(tyObject_MemFile__j4SnXNrJDFBxAz4BlbM9aIQ, open__QVGUjgJbeJv7RHdWON5YuA)(NimStringV2 filename, tyEnum_FileMode__ZJfK20XeZ9bv2j1pZjw9aswg mode, NI mappedSize, NI offset, NI newFileSize, NIM_BOOL allowRemap, int mapFlags);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ)(NimStringV2* dest);
static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem__zxfKBYntu9cBapkhrCOk1fgmemory)(void* a, int v, NI size);
N_LIB_PRIVATE N_NIMCALL(tyObject_PrimMethcolonObjectType___7evgxa2ozVE9bj7jSo6ShwQ*, newPrimMeth__7XdBOD8x4C4vz9aR71T9bfkA)(tyProc__KzxxW30gLaLhm4JG7rojSg primitive);
N_LIB_PRIVATE N_NIMCALL(tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ*, colonanonymous___dplzm2YJ7bZn9b4A9bfAbXqQ_2)(tyObject_InterpretercolonObjectType___9a9c0PsXJdclNJBQRoT5OKJg* spry);
N_LIB_PRIVATE N_NIMCALL(tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ*, evalArgInfix__7W5SyHus4xS1zyMEKJKT6Q_2)(tyObject_InterpretercolonObjectType___9a9c0PsXJdclNJBQRoT5OKJg* spry);
N_LIB_PRIVATE N_NIMCALL(void, close__gRakhE5v7JaOKQThVQTzkA)(tyObject_MemFile__j4SnXNrJDFBxAz4BlbM9aIQ* f);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___irQcc62iJvr8nkVPyMdezA)(tyObject_MemfileNodecolonObjectType___SClUH77NqezEgy7ah1Yt5Q** dest);
N_LIB_PRIVATE N_NIMCALL(tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ*, colonanonymous___dplzm2YJ7bZn9b4A9bfAbXqQ_3)(tyObject_InterpretercolonObjectType___9a9c0PsXJdclNJBQRoT5OKJg* spry);
N_LIB_PRIVATE N_NIMCALL(tyObject_BlokcolonObjectType___UIJsSh2kxAc9acGwoSYj4xw*, newBlok__StAJzwltfv7vj6MtMRp0QQ)(void);
N_NIMCALL(NimStringV2, rawNewString)(NI cap);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i, NI64 a, NI64 b);
N_LIB_PRIVATE N_NIMCALL(void, setLengthStrV2)(NimStringV2* s, NI newLen);
static N_INLINE(void, copyMem__i80o3k0SgEI5gTRCzYdyWAsystem)(void* dest, void* source, NI size);
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i, NI n);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___aBBXmHFBEivKqERloP6zmA)(NimStringV2* dest, NimStringV2 src);
N_LIB_PRIVATE N_NIMCALL(void, add__rdXg9c9cZ1CzHeD49bM9bvH3PA)(tyObject_SeqCompositecolonObjectType___C3SNeoePmbb3Sj78kdPUzA* self, tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ* n);
static N_INLINE(NI, minusemark___bLhXIfQwxhJGW6yuNG9b4LQmemfiles)(void* p, void* q);
static N_INLINE(NI, pluspercent___dgYAo7RfdUVVpvkfKDym8w_2system)(NI x, NI y);
N_LIB_PRIVATE N_NIMCALL(tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ*, colonanonymous___dplzm2YJ7bZn9b4A9bfAbXqQ_4)(tyObject_InterpretercolonObjectType___9a9c0PsXJdclNJBQRoT5OKJg* spry);
N_LIB_PRIVATE N_NIMCALL(void, eq___759cyjGBfDaxSOPsM2JffXw)(tyObject_ActivationcolonObjectType___jwMMFyLWVLpBU9ca5Dr6Vrw** dest, tyObject_ActivationcolonObjectType___jwMMFyLWVLpBU9ca5Dr6Vrw* src);
N_LIB_PRIVATE N_NIMCALL(void, eq___8eMhTKv1RRUDzX38ucu4fA)(tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ** dest, tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ* src);
N_LIB_PRIVATE N_NIMCALL(tyObject_ActivationcolonObjectType___jwMMFyLWVLpBU9ca5Dr6Vrw*, newActivation__z9aNhDNx4cfCuoQWvI0ReBw)(tyObject_BlokcolonObjectType___UIJsSh2kxAc9acGwoSYj4xw* body);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___8eMhTKv1RRUDzX38ucu4fA_2)(tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ** dest, tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ* src);
N_LIB_PRIVATE N_NIMCALL(tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ*, eval__VIBmNwKvb9acnasQzNrtApQ)(tyObject_ActivationcolonObjectType___jwMMFyLWVLpBU9ca5Dr6Vrw* current, tyObject_InterpretercolonObjectType___9a9c0PsXJdclNJBQRoT5OKJg* spry);
N_LIB_PRIVATE N_NIMCALL(void, reset__scJ8nNSlOQVuGEvoEUpjZw)(tyObject_ActivationcolonObjectType___jwMMFyLWVLpBU9ca5Dr6Vrw* self);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___9aO1dEPkfhJnKjHT0JFTXpA)(tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ** dest);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___dOERzQgALmYg78PEb20q5Q)(tyObject_ActivationcolonObjectType___jwMMFyLWVLpBU9ca5Dr6Vrw** dest);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___8fQUMkSQEEPPeEE5xVHN7g)(tyObject_BlokcolonObjectType___UIJsSh2kxAc9acGwoSYj4xw** dest);

/* section: NIM_merge_DATA */
static const struct {
  NI cap; NIM_CHAR data[11+1];
} TM__pwrqdpRNZbc1rhRZbgtEow_4 = { 11 | NIM_STRLIT_FLAG, "openMemfile" };
static const NimStringV2 TM__pwrqdpRNZbc1rhRZbgtEow_5 = {11, (NimStrPayload*)&TM__pwrqdpRNZbc1rhRZbgtEow_4};
N_LIB_PRIVATE TNimType NTI__SClUH77NqezEgy7ah1Yt5Q_;
static const struct {
  NI cap; NIM_CHAR data[12+1];
} TM__pwrqdpRNZbc1rhRZbgtEow_7 = { 12 | NIM_STRLIT_FLAG, "closeMemfile" };
static const NimStringV2 TM__pwrqdpRNZbc1rhRZbgtEow_8 = {12, (NimStrPayload*)&TM__pwrqdpRNZbc1rhRZbgtEow_7};
static const struct {
  NI cap; NIM_CHAR data[9+1];
} TM__pwrqdpRNZbc1rhRZbgtEow_10 = { 9 | NIM_STRLIT_FLAG, "readLines" };
static const NimStringV2 TM__pwrqdpRNZbc1rhRZbgtEow_11 = {9, (NimStrPayload*)&TM__pwrqdpRNZbc1rhRZbgtEow_10};
extern TNimType NTI__OzaVEa2ZspAxtzIz1MQfcA_;
static const struct {
  NI cap; NIM_CHAR data[8+1];
} TM__pwrqdpRNZbc1rhRZbgtEow_16 = { 8 | NIM_STRLIT_FLAG, "linesDo:" };
static const NimStringV2 TM__pwrqdpRNZbc1rhRZbgtEow_17 = {8, (NimStrPayload*)&TM__pwrqdpRNZbc1rhRZbgtEow_16};

/* section: NIM_merge_VARS */
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_BOOL nimInErrorMode__759bT87luu8XGcbkw13FUjA;

/* section: NIM_merge_PROCS */

#line 541 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
static N_INLINE(void, nimFrame)(TFrame* s) {
#line 542 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	{
#line 542 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
		if (!(framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA3_;

#line 543 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
		(*s).calldepth = ((NI16) 0);	}
	goto LA1_;
	LA3_: ;
	{
#line 546 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"

#line 546 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
		(*s).calldepth = (NI16)((*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1));	}
	LA1_: ;

#line 548 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	(*s).prev = framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
#line 549 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = s;
#line 550 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	{
#line 550 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
		if (!((*s).calldepth == ((NI16) 2000))) goto LA8_;

#line 550 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"

#line 550 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
		callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw();
	}
	LA8_: ;
}

#line 85 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
static N_INLINE(void, popFrame)(void) {
#line 86 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).prev;}

#line 436 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/arithmetics.nim"
static N_INLINE(NI, minuspercent___dgYAo7RfdUVVpvkfKDym8wsystem)(NI x, NI y) {	NI result;	nimfr_("-%", "/Users/elcritch/.asdf/installs/nim/devel/lib/system/arithmetics"
".nim");	result = (NI)0;
#line 437 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/arithmetics.nim"
	nimln_(437, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/arithmetics"
".nim");
#line 441 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/arithmetics.nim"
	nimln_(441, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/arithmetics"
".nim");	result = ((NI) ((NU)((NU64)(((NU) (x))) - (NU64)(((NU) (y))))));	popFrame();	return result;}

#line 107 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/refs_v2.nim"
static N_INLINE(void, nimIncRef)(void* p) {	NI T1_;	NI TM__pwrqdpRNZbc1rhRZbgtEow_2;	NI T2_;	int T3_;	nimfr_("nimIncRef", "/Users/elcritch/.asdf/installs/nim/devel/lib/system/refs_v2.nim");{
#line 108 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/refs_v2.nim"
	nimln_(108, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/refs_v2.nim");
#line 65 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/refs_v2.nim"
	nimln_(65, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/refs_v2.nim");
#line 65 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/refs_v2.nim"
	T1_ = (NI)0;	T1_ = minuspercent___dgYAo7RfdUVVpvkfKDym8wsystem(((NI) (ptrdiff_t) (p)), ((NI) 8));	if (nimAddInt((*((tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A*) (T1_))).rc, ((NI) 8), &TM__pwrqdpRNZbc1rhRZbgtEow_2)) { raiseOverflow(); goto BeforeRet_;};	(*((tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A*) (T1_))).rc = (NI)(TM__pwrqdpRNZbc1rhRZbgtEow_2);
#line 110 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/refs_v2.nim"
	nimln_(110, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/refs_v2.nim");
#line 65 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/refs_v2.nim"
	nimln_(65, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/refs_v2.nim");
#line 65 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/refs_v2.nim"
	T2_ = (NI)0;	T2_ = minuspercent___dgYAo7RfdUVVpvkfKDym8wsystem(((NI) (ptrdiff_t) (p)), ((NI) 8));
#line 110 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/refs_v2.nim"
	nimln_(110, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/refs_v2.nim");	T3_ = (int)0;	T3_ = printf("[INCREF] %p\012", ((tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A*) (T2_)));	}BeforeRet_: ;
	popFrame();}

#line 150 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/refs_v2.nim"
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p) {	NIM_BOOL result;	nimfr_("nimDecRefIsLast", "/Users/elcritch/.asdf/installs/nim/devel/lib/system/refs_v2.nim");{	result = (NIM_BOOL)0;
#line 151 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/refs_v2.nim"
	nimln_(151, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/refs_v2.nim");	{		tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A* cell;		NI T5_;
#line 151 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/refs_v2.nim"

#line 151 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/refs_v2.nim"
		if (!!((p == NIM_NIL))) goto LA3_;

#line 152 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/refs_v2.nim"
		nimln_(152, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/refs_v2.nim");
#line 65 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/refs_v2.nim"
		nimln_(65, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/refs_v2.nim");
#line 65 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/refs_v2.nim"
		T5_ = (NI)0;		T5_ = minuspercent___dgYAo7RfdUVVpvkfKDym8wsystem(((NI) (ptrdiff_t) (p)), ((NI) 8));		cell = ((tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A*) (T5_));
#line 153 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/refs_v2.nim"
		nimln_(153, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/refs_v2.nim");		{			int T10_;
#line 153 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/refs_v2.nim"

#line 153 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/refs_v2.nim"
			if (!((NI)((*cell).rc & ((NI) -8)) == ((NI) 0))) goto LA8_;

#line 154 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/refs_v2.nim"
			nimln_(154, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/refs_v2.nim");			result = NIM_TRUE;
#line 156 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/refs_v2.nim"
			nimln_(156, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/refs_v2.nim");
#line 156 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/refs_v2.nim"
			T10_ = (int)0;			T10_ = printf("[ABOUT TO DESTROY] %p\012", cell);		}
		goto LA6_;
		LA8_: ;
		{			NI TM__pwrqdpRNZbc1rhRZbgtEow_3;			int T12_;
#line 158 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/refs_v2.nim"
			nimln_(158, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/refs_v2.nim");			if (nimSubInt((*cell).rc, ((NI) 8), &TM__pwrqdpRNZbc1rhRZbgtEow_3)) { raiseOverflow(); goto BeforeRet_;};			(*cell).rc = (NI)(TM__pwrqdpRNZbc1rhRZbgtEow_3);
#line 161 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/refs_v2.nim"
			nimln_(161, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/refs_v2.nim");
#line 161 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/refs_v2.nim"
			T12_ = (int)0;			T12_ = printf("[DeCREF] %p\012", cell);		}
		LA6_: ;
	}
	LA3_: ;
	}BeforeRet_: ;
	popFrame();	return result;}

#line 9 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"
N_LIB_PRIVATE N_NIMCALL(void, eq___LIf9anzbADx2Pk8D7rRZkjA)(tyObject_MemfileNodecolonObjectType___SClUH77NqezEgy7ah1Yt5Q** dest, tyObject_MemfileNodecolonObjectType___SClUH77NqezEgy7ah1Yt5Q* src) {
#line 9 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"
	{		if (!src) goto LA3_;

#line 9 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"

#line 9 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"
		nimIncRef(src);
	}
	LA3_: ;

#line 9 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"
	{		NIM_BOOL T7_;
#line 9 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"

#line 9 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"
		T7_ = (NIM_BOOL)0;		T7_ = nimDecRefIsLast((*dest));		if (!T7_) goto LA8_;

#line 9 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"

#line 9 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"
		nimDestroyAndDispose((*dest));
	}
	LA8_: ;

#line 9 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"
	(*dest) = src;}

#line 424 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {	NIM_BOOL* result;	result = (NIM_BOOL*)0;
#line 425 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	result = (&nimInErrorMode__759bT87luu8XGcbkw13FUjA);	return result;}

#line 8 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"
N_LIB_PRIVATE N_NIMCALL(tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ*, eval__f6XObCfHu6zUMY37KOsgAg)(tyObject_MemfileNodecolonObjectType___SClUH77NqezEgy7ah1Yt5Q* self, tyObject_InterpretercolonObjectType___9a9c0PsXJdclNJBQRoT5OKJg* spry) {	tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ* result;	tyObject_MemfileNodecolonObjectType___SClUH77NqezEgy7ah1Yt5Q* colontmpD_;NIM_BOOL* nimErr_;	nimfr_("eval", "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryme"
"mfile.nim");{nimErr_ = nimErrorFlag();	result = (tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ*)0;	colontmpD_ = (tyObject_MemfileNodecolonObjectType___SClUH77NqezEgy7ah1Yt5Q*)0;
#line 9 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"
	nimln_(9, "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryme"
"mfile.nim");
#line 9 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"
	colontmpD_ = 0;
#line 9 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"

#line 9 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"
	eq___LIf9anzbADx2Pk8D7rRZkjA(&colontmpD_, self);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	result = &colontmpD_->Sup.Sup;	}BeforeRet_: ;
	popFrame();	return result;}

#line 187 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/refs_v2.nim"
static N_INLINE(NIM_BOOL, isObj)(TNimType* obj, NCSTRING subclass) {	NIM_BOOL result;	NCSTRING T1_;	nimfr_("isObj", "/Users/elcritch/.asdf/installs/nim/devel/lib/system/refs_v2.nim");	result = (NIM_BOOL)0;
#line 190 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/refs_v2.nim"
	nimln_(190, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/refs_v2.nim");
#line 190 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/refs_v2.nim"

#line 190 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/refs_v2.nim"

#line 190 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/refs_v2.nim"

#line 190 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/refs_v2.nim"
	T1_ = (NCSTRING)0;	T1_ = strstr((*obj).name, subclass);	result = !((((void*) (T1_)) == NIM_NIL));	popFrame();	return result;}

#line 9 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___xh2dJ15yFU7fmHKaAN9awww)(tyObject_MemfileNodecolonObjectType___SClUH77NqezEgy7ah1Yt5Q* dest) {
#line 9 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"
	{		NIM_BOOL T3_;
#line 9 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"

#line 9 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"
		T3_ = (NIM_BOOL)0;		T3_ = nimDecRefIsLast((*dest).Sup.Sup.tags);		if (!T3_) goto LA4_;

#line 9 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"

#line 9 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"
		nimDestroyAndDispose((*dest).Sup.Sup.tags);

#line 9 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"
		(*dest).Sup.Sup.tags = NIM_NIL;	}
	LA4_: ;
}

#line 1351 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryvm.nim"
N_LIB_PRIVATE N_NIMCALL(tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ*, colonanonymous___dplzm2YJ7bZn9b4A9bfAbXqQ)(tyObject_InterpretercolonObjectType___9a9c0PsXJdclNJBQRoT5OKJg* spry) {	tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ* result;	NimStringV2 path;	tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ* T2_;	tyObject_MemfileNodecolonObjectType___SClUH77NqezEgy7ah1Yt5Q* T3_;NIM_BOOL* nimErr_;	nimfr_(":anonymous", "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryvm"
".nim");{nimErr_ = nimErrorFlag();	result = (tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ*)0;	path.len = 0; path.p = NIM_NIL;
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
	nimln_(49, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");
#line 15 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"
	nimln_(15, "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryme"
"mfile.nim");
#line 15 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"
	T2_ = (tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ*)0;	T2_ = evalArg__7W5SyHus4xS1zyMEKJKT6Q_3(spry);	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;	if (T2_ && !isObj((*T2_).Sup.m_type, "|spryvm.spryvm.StringVal:ObjectType|spryvm.spryvm.Value:ObjectT"
"ype|spryvm.spryvm.Node:ObjectType|RootObj|")){ raiseObjectConversionError(); goto LA1_;}
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
	nimln_(49, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");	eq___aBBXmHFBEivKqERloP6zmA_2((&path), (*((tyObject_StringValcolonObjectType___OzaVEa2ZspAxtzIz1MQfcA*) (T2_))).value);

#line 16 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"
	nimln_(16, "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryme"
"mfile.nim");	T3_ = (tyObject_MemfileNodecolonObjectType___SClUH77NqezEgy7ah1Yt5Q*)0;	T3_ = (tyObject_MemfileNodecolonObjectType___SClUH77NqezEgy7ah1Yt5Q*) nimNewObj(sizeof(tyObject_MemfileNodecolonObjectType___SClUH77NqezEgy7ah1Yt5Q));	(*T3_).Sup.Sup.Sup.m_type = (&NTI__SClUH77NqezEgy7ah1Yt5Q_);
#line 16 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"

#line 16 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"
	(*T3_).memfile = open__QVGUjgJbeJv7RHdWON5YuA(path, ((tyEnum_FileMode__ZJfK20XeZ9bv2j1pZjw9aswg) 0), ((NI) -1), ((NI) 0), ((NI) -1), NIM_FALSE, ((int) -1));	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;	result = &T3_->Sup.Sup;	{		LA1_:;	}
	{
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
		nimln_(49, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
		eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&path));
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}BeforeRet_: ;
	popFrame();	return result;}

#line 22 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/memory.nim"
static N_INLINE(void, nimSetMem__zxfKBYntu9cBapkhrCOk1fgmemory)(void* a, int v, NI size) {	void* T1_;
#line 24 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/memory.nim"

#line 24 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/memory.nim"
	T1_ = (void*)0;	T1_ = memset(a, v, ((size_t) (size)));}

#line 33 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/memory.nim"
static N_INLINE(void, nimZeroMem)(void* p, NI size) {NIM_BOOL* nimErr_;{nimErr_ = nimErrorFlag();
#line 34 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/memory.nim"

#line 34 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/memory.nim"
	nimSetMem__zxfKBYntu9cBapkhrCOk1fgmemory(p, ((int) 0), size);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}BeforeRet_: ;
}

#line 9 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___irQcc62iJvr8nkVPyMdezA)(tyObject_MemfileNodecolonObjectType___SClUH77NqezEgy7ah1Yt5Q** dest) {
#line 9 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"
	{		NIM_BOOL T3_;
#line 9 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"

#line 9 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"
		T3_ = (NIM_BOOL)0;		T3_ = nimDecRefIsLast((*dest));		if (!T3_) goto LA4_;

#line 9 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"

#line 9 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"
		nimDestroyAndDispose((*dest));

#line 9 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"
		(*dest) = NIM_NIL;	}
	LA4_: ;
}

#line 1355 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryvm.nim"
N_LIB_PRIVATE N_NIMCALL(tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ*, colonanonymous___dplzm2YJ7bZn9b4A9bfAbXqQ_2)(tyObject_InterpretercolonObjectType___9a9c0PsXJdclNJBQRoT5OKJg* spry) {	tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ* result;	tyObject_MemfileNodecolonObjectType___SClUH77NqezEgy7ah1Yt5Q* node;	tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ* T2_;NIM_BOOL oldNimErrFin1_;NIM_BOOL* nimErr_;	nimfr_(":anonymous", "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryvm"
".nim");{nimErr_ = nimErrorFlag();	result = (tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ*)0;	node = (tyObject_MemfileNodecolonObjectType___SClUH77NqezEgy7ah1Yt5Q*)0;
#line 18 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"
	nimln_(18, "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryme"
"mfile.nim");
#line 18 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"

#line 18 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"
	T2_ = (tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ*)0;	T2_ = evalArgInfix__7W5SyHus4xS1zyMEKJKT6Q_2(spry);	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;	if (T2_ && !isObj((*T2_).Sup.m_type, "|spryvm.sprymemfile.MemfileNode:ObjectType|spryvm.spryvm.Value:"
"ObjectType|spryvm.spryvm.Node:ObjectType|RootObj|")){ raiseObjectConversionError(); goto LA1_;}	node = ((tyObject_MemfileNodecolonObjectType___SClUH77NqezEgy7ah1Yt5Q*) (T2_));
#line 19 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"
	nimln_(19, "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryme"
"mfile.nim");
#line 19 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"
	close__gRakhE5v7JaOKQThVQTzkA((&(*node).memfile));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;	{		LA1_:;	}
	{		oldNimErrFin1_ = *nimErr_; *nimErr_ = NIM_FALSE;
#line 9 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"
		nimln_(9, "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryme"
"mfile.nim");
#line 9 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"
		eqdestroy___irQcc62iJvr8nkVPyMdezA(&node);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;		*nimErr_ = oldNimErrFin1_;	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}BeforeRet_: ;
	popFrame();	return result;}

#line 11 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/memory.nim"
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size) {	void* T1_;
#line 13 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/memory.nim"

#line 13 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/memory.nim"
	T1_ = (void*)0;	T1_ = memcpy(dest, source, ((size_t) (size)));}

#line 2132 "/Users/elcritch/.asdf/installs/nim/devel/lib/system.nim"
static N_INLINE(void, copyMem__i80o3k0SgEI5gTRCzYdyWAsystem)(void* dest, void* source, NI size) {
#line 2133 "/Users/elcritch/.asdf/installs/nim/devel/lib/system.nim"

#line 2133 "/Users/elcritch/.asdf/installs/nim/devel/lib/system.nim"
	nimCopyMem(dest, source, size);
}

#line 413 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim"
static N_INLINE(NI, minusemark___bLhXIfQwxhJGW6yuNG9b4LQmemfiles)(void* p, void* q) {	NI result;	nimfr_("-!", "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim");{	result = (NI)0;
#line 413 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim"
	nimln_(413, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim");
#line 413 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim"

#line 413 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim"
	result = minuspercent___dgYAo7RfdUVVpvkfKDym8wsystem(((NI) (ptrdiff_t) (p)), ((NI) (ptrdiff_t) (q)));	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();	return result;}

#line 425 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/arithmetics.nim"
static N_INLINE(NI, pluspercent___dgYAo7RfdUVVpvkfKDym8w_2system)(NI x, NI y) {	NI result;	nimfr_("+%", "/Users/elcritch/.asdf/installs/nim/devel/lib/system/arithmetics"
".nim");	result = (NI)0;
#line 426 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/arithmetics.nim"
	nimln_(426, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/arithmetics"
".nim");
#line 430 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/arithmetics.nim"
	nimln_(430, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/arithmetics"
".nim");	result = ((NI) ((NU)((NU64)(((NU) (x))) + (NU64)(((NU) (y))))));	popFrame();	return result;}

#line 1351 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryvm.nim"
N_LIB_PRIVATE N_NIMCALL(tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ*, colonanonymous___dplzm2YJ7bZn9b4A9bfAbXqQ_3)(tyObject_InterpretercolonObjectType___9a9c0PsXJdclNJBQRoT5OKJg* spry) {	tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ* result;	NimStringV2 path;	NimStringV2 line;	NimStringV2 buf;	NimStringV2 line_2;	tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ* T2_;	tyObject_MemFile__j4SnXNrJDFBxAz4BlbM9aIQ memfile;	tyObject_BlokcolonObjectType___UIJsSh2kxAc9acGwoSYj4xw* T3_;NIM_BOOL* nimErr_;	nimfr_(":anonymous", "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryvm"
".nim");{nimErr_ = nimErrorFlag();	result = (tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ*)0;	path.len = 0; path.p = NIM_NIL;	line.len = 0; line.p = NIM_NIL;	buf.len = 0; buf.p = NIM_NIL;	line_2.len = 0; line_2.p = NIM_NIL;
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
	nimln_(49, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");
#line 21 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"
	nimln_(21, "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryme"
"mfile.nim");
#line 21 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"
	T2_ = (tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ*)0;	T2_ = evalArg__7W5SyHus4xS1zyMEKJKT6Q_3(spry);	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;	if (T2_ && !isObj((*T2_).Sup.m_type, "|spryvm.spryvm.StringVal:ObjectType|spryvm.spryvm.Value:ObjectT"
"ype|spryvm.spryvm.Node:ObjectType|RootObj|")){ raiseObjectConversionError(); goto LA1_;}
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
	nimln_(49, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");	eq___aBBXmHFBEivKqERloP6zmA_2((&path), (*((tyObject_StringValcolonObjectType___OzaVEa2ZspAxtzIz1MQfcA*) (T2_))).value);

#line 22 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"
	nimln_(22, "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryme"
"mfile.nim");
#line 22 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"
	memfile = open__QVGUjgJbeJv7RHdWON5YuA(path, ((tyEnum_FileMode__ZJfK20XeZ9bv2j1pZjw9aswg) 0), ((NI) -1), ((NI) 0), ((NI) -1), NIM_FALSE, ((int) -1));	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
#line 23 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"
	nimln_(23, "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryme"
"mfile.nim");
#line 23 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"

#line 23 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"
	T3_ = (tyObject_BlokcolonObjectType___UIJsSh2kxAc9acGwoSYj4xw*)0;	T3_ = newBlok__StAJzwltfv7vj6MtMRp0QQ();	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;	result = &T3_->Sup.Sup.Sup;	{
#line 463 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim"
		nimln_(463, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim");
#line 463 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim"

#line 463 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim"
		buf = rawNewString(((NI) 80));		{			{				tyObject_MemSlice__fWlUmmDo9aQGKOHWrhWV54Q ms;				tyObject_MemSlice__fWlUmmDo9aQGKOHWrhWV54Q ms_2;				void* ending;				NI remaining;				nimZeroMem((void*)(&ms), sizeof(tyObject_MemSlice__fWlUmmDo9aQGKOHWrhWV54Q));				nimZeroMem((void*)(&ms_2), sizeof(tyObject_MemSlice__fWlUmmDo9aQGKOHWrhWV54Q));				ending = (void*)0;
#line 416 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim"
				nimln_(416, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim");				ms_2.data = memfile.mem;
#line 417 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim"
				nimln_(417, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim");				remaining = memfile.size;				{
#line 418 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim"
					nimln_(418, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim");					while (1) {						NI T20_;						tyObject_SeqCompositecolonObjectType___C3SNeoePmbb3Sj78kdPUzA* T33_;						tyObject_StringValcolonObjectType___OzaVEa2ZspAxtzIz1MQfcA* T34_;						NimStringV2 blitTmp_2;						tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ* T35_;						NI T36_;						NI T37_;						NI TM__pwrqdpRNZbc1rhRZbgtEow_14;
#line 418 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim"
						if (!(((NI) 0) < remaining)) goto LA8;

#line 419 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim"
						nimln_(419, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim");
#line 419 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim"
						ending = memchr(ms_2.data, 10, remaining);
#line 420 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim"
						nimln_(420, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim");						{							tyObject_SeqCompositecolonObjectType___C3SNeoePmbb3Sj78kdPUzA* T17_;							tyObject_StringValcolonObjectType___OzaVEa2ZspAxtzIz1MQfcA* T18_;							NimStringV2 blitTmp;							tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ* T19_;
#line 420 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim"
							if (!(ending == NIM_NIL)) goto LA11_;

#line 421 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim"
							nimln_(421, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim");							ms_2.size = remaining;
#line 445 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim"
							nimln_(445, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim");							ms = ms_2;
#line 446 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim"
							nimln_(446, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim");							if ((ms.size) < ((NI) 0) || (ms.size) > ((NI) IL64(9223372036854775807))){ raiseRangeErrorI(ms.size, ((NI) 0), ((NI) IL64(9223372036854775807))); goto LA1_;}							setLengthStrV2((&buf), ((NI) (ms.size)));
#line 447 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim"
							nimln_(447, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim");							{
#line 447 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim"
								if (!(((NI) 0) < ms.size)) goto LA15_;

#line 448 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim"
								nimln_(448, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim");								if ((NU)(((NI) 0)) >= (NU)buf.len){ raiseIndexError2(((NI) 0),buf.len-1); goto LA1_;}								if ((ms.size) < ((NI) 0) || (ms.size) > ((NI) IL64(9223372036854775807))){ raiseRangeErrorI(ms.size, ((NI) 0), ((NI) IL64(9223372036854775807))); goto LA1_;}
#line 448 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim"
								copyMem__i80o3k0SgEI5gTRCzYdyWAsystem(((void*) ((&buf.p->data[((NI) 0)]))), ms.data, ((NI) (ms.size)));
							}
							LA15_: ;

#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
							nimln_(49, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
							eq___aBBXmHFBEivKqERloP6zmA_2((&line_2), buf);

#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"

#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
							eqsink___aBBXmHFBEivKqERloP6zmA((&line), buf);

#line 24 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"
							nimln_(24, "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryme"
"mfile.nim");							buf.len = 0; buf.p = NIM_NIL;
#line 25 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"
							nimln_(25, "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryme"
"mfile.nim");							if (result && !isObj((*result).Sup.m_type, "|spryvm.spryvm.Blok:ObjectType|spryvm.spryvm.SeqComposite:Objec"
"tType|spryvm.spryvm.Composite:ObjectType|spryvm.spryvm.Node:Obje"
"ctType|RootObj|")){ raiseObjectConversionError(); goto LA1_;}							T17_ = (tyObject_SeqCompositecolonObjectType___C3SNeoePmbb3Sj78kdPUzA*)0;							T17_ = &(*((tyObject_BlokcolonObjectType___UIJsSh2kxAc9acGwoSYj4xw**) (&(result))))->Sup;							T18_ = (tyObject_StringValcolonObjectType___OzaVEa2ZspAxtzIz1MQfcA*)0;							T18_ = (tyObject_StringValcolonObjectType___OzaVEa2ZspAxtzIz1MQfcA*) nimNewObj(sizeof(tyObject_StringValcolonObjectType___OzaVEa2ZspAxtzIz1MQfcA));							(*T18_).Sup.Sup.Sup.m_type = (&NTI__OzaVEa2ZspAxtzIz1MQfcA_);
#line 25 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"
							blitTmp = line;
#line 25 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"
							line.len = 0; line.p = NIM_NIL;							(*T18_).value = blitTmp;							T19_ = (tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ*)0;							T19_ = &T18_->Sup.Sup;
#line 25 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"
							add__rdXg9c9cZ1CzHeD49bM9bvH3PA(T17_, T19_);
							if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
#line 423 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim"
							nimln_(423, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim");							goto LA7;
						}
						LA11_: ;

#line 424 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim"
						nimln_(424, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim");
#line 424 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim"
						T20_ = (NI)0;						T20_ = minusemark___bLhXIfQwxhJGW6yuNG9b4LQmemfiles(ending, ms_2.data);						if (NIM_UNLIKELY(*nimErr_)) goto LA1_;						ms_2.size = T20_;
#line 425 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim"
						nimln_(425, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim");						{							NIM_BOOL T23_;							NIM_BOOL T24_;							NI TM__pwrqdpRNZbc1rhRZbgtEow_12;							NI TM__pwrqdpRNZbc1rhRZbgtEow_13;
#line 425 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim"
							T23_ = (NIM_BOOL)0;
#line 425 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim"
							T24_ = (NIM_BOOL)0;							T24_ = NIM_TRUE;							if (!(T24_)) goto LA25_;

#line 425 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim"
							T24_ = (((NI) 0) < ms_2.size);							LA25_: ;
							T23_ = T24_;							if (!(T23_)) goto LA26_;

#line 425 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim"

#line 425 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim"
							if (nimSubInt(ms_2.size, ((NI) 1), &TM__pwrqdpRNZbc1rhRZbgtEow_12)) { raiseOverflow(); goto LA1_;};							T23_ = ((NU8)(((NCSTRING) (ms_2.data))[(NI)(TM__pwrqdpRNZbc1rhRZbgtEow_12)]) == (NU8)(13));							LA26_: ;
							if (!T23_) goto LA27_;

#line 426 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim"
							nimln_(426, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim");							if (nimSubInt(ms_2.size, ((NI) 1), &TM__pwrqdpRNZbc1rhRZbgtEow_13)) { raiseOverflow(); goto LA1_;};							ms_2.size = (NI)(TM__pwrqdpRNZbc1rhRZbgtEow_13);						}
						LA27_: ;

#line 445 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim"
						nimln_(445, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim");						ms = ms_2;
#line 446 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim"
						nimln_(446, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim");						if ((ms.size) < ((NI) 0) || (ms.size) > ((NI) IL64(9223372036854775807))){ raiseRangeErrorI(ms.size, ((NI) 0), ((NI) IL64(9223372036854775807))); goto LA1_;}						setLengthStrV2((&buf), ((NI) (ms.size)));
#line 447 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim"
						nimln_(447, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim");						{
#line 447 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim"
							if (!(((NI) 0) < ms.size)) goto LA31_;

#line 448 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim"
							nimln_(448, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim");							if ((NU)(((NI) 0)) >= (NU)buf.len){ raiseIndexError2(((NI) 0),buf.len-1); goto LA1_;}							if ((ms.size) < ((NI) 0) || (ms.size) > ((NI) IL64(9223372036854775807))){ raiseRangeErrorI(ms.size, ((NI) 0), ((NI) IL64(9223372036854775807))); goto LA1_;}
#line 448 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim"
							copyMem__i80o3k0SgEI5gTRCzYdyWAsystem(((void*) ((&buf.p->data[((NI) 0)]))), ms.data, ((NI) (ms.size)));
						}
						LA31_: ;

#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
						nimln_(49, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
						eq___aBBXmHFBEivKqERloP6zmA_2((&line_2), buf);

#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"

#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
						eq___aBBXmHFBEivKqERloP6zmA_2((&line), buf);

#line 25 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"
						nimln_(25, "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryme"
"mfile.nim");						if (result && !isObj((*result).Sup.m_type, "|spryvm.spryvm.Blok:ObjectType|spryvm.spryvm.SeqComposite:Objec"
"tType|spryvm.spryvm.Composite:ObjectType|spryvm.spryvm.Node:Obje"
"ctType|RootObj|")){ raiseObjectConversionError(); goto LA1_;}						T33_ = (tyObject_SeqCompositecolonObjectType___C3SNeoePmbb3Sj78kdPUzA*)0;						T33_ = &(*((tyObject_BlokcolonObjectType___UIJsSh2kxAc9acGwoSYj4xw**) (&(result))))->Sup;						T34_ = (tyObject_StringValcolonObjectType___OzaVEa2ZspAxtzIz1MQfcA*)0;						T34_ = (tyObject_StringValcolonObjectType___OzaVEa2ZspAxtzIz1MQfcA*) nimNewObj(sizeof(tyObject_StringValcolonObjectType___OzaVEa2ZspAxtzIz1MQfcA));						(*T34_).Sup.Sup.Sup.m_type = (&NTI__OzaVEa2ZspAxtzIz1MQfcA_);
#line 25 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"
						blitTmp_2 = line;
#line 25 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"
						line.len = 0; line.p = NIM_NIL;						(*T34_).value = blitTmp_2;						T35_ = (tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ*)0;						T35_ = &T34_->Sup.Sup;
#line 25 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"
						add__rdXg9c9cZ1CzHeD49bM9bvH3PA(T33_, T35_);
						if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
#line 428 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim"
						nimln_(428, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim");
#line 428 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim"

#line 428 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim"
						T36_ = (NI)0;						T36_ = pluspercent___dgYAo7RfdUVVpvkfKDym8w_2system(((NI) (ptrdiff_t) (ending)), ((NI) 1));						ms_2.data = ((void*) (T36_));
#line 429 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim"
						nimln_(429, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim");
#line 429 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim"

#line 429 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim"

#line 429 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim"
						T37_ = (NI)0;						T37_ = minusemark___bLhXIfQwxhJGW6yuNG9b4LQmemfiles(ms_2.data, memfile.mem);						if (NIM_UNLIKELY(*nimErr_)) goto LA1_;						if (nimSubInt(memfile.size, T37_, &TM__pwrqdpRNZbc1rhRZbgtEow_14)) { raiseOverflow(); goto LA1_;};						remaining = (NI)(TM__pwrqdpRNZbc1rhRZbgtEow_14);					} LA8: ;
				} LA7: ;
			}
		}
	}

#line 26 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"
	nimln_(26, "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryme"
"mfile.nim");
#line 26 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"
	close__gRakhE5v7JaOKQThVQTzkA((&memfile));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;	{		LA1_:;	}
	{
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
		nimln_(49, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
		eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&line_2));

#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"

#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
		eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&buf));

#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"

#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
		eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&line));

#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"

#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
		eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&path));
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}BeforeRet_: ;
	popFrame();	return result;}

#line 1355 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryvm.nim"
N_LIB_PRIVATE N_NIMCALL(tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ*, colonanonymous___dplzm2YJ7bZn9b4A9bfAbXqQ_4)(tyObject_InterpretercolonObjectType___9a9c0PsXJdclNJBQRoT5OKJg* spry) {	tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ* result;	tyObject_BlokcolonObjectType___UIJsSh2kxAc9acGwoSYj4xw* blk;	tyObject_ActivationcolonObjectType___jwMMFyLWVLpBU9ca5Dr6Vrw* current;	tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ* orig;	tyObject_ActivationcolonObjectType___jwMMFyLWVLpBU9ca5Dr6Vrw* activation;	NimStringV2 line;	NimStringV2 buf;	NimStringV2 line_2;	tyObject_ActivationcolonObjectType___jwMMFyLWVLpBU9ca5Dr6Vrw* colontmpD_;	tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ* colontmpD__2;	tyObject_ActivationcolonObjectType___jwMMFyLWVLpBU9ca5Dr6Vrw* colontmpD__3;	tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ* colontmpD__4;	tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ* T2_;	tyObject_MemFile__j4SnXNrJDFBxAz4BlbM9aIQ memfile;	tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ* T3_;	NI oldpos;NIM_BOOL oldNimErrFin1_;NIM_BOOL* nimErr_;	nimfr_(":anonymous", "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryvm"
".nim");{nimErr_ = nimErrorFlag();	result = (tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ*)0;	blk = (tyObject_BlokcolonObjectType___UIJsSh2kxAc9acGwoSYj4xw*)0;	current = (tyObject_ActivationcolonObjectType___jwMMFyLWVLpBU9ca5Dr6Vrw*)0;	orig = (tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ*)0;	activation = (tyObject_ActivationcolonObjectType___jwMMFyLWVLpBU9ca5Dr6Vrw*)0;	line.len = 0; line.p = NIM_NIL;	buf.len = 0; buf.p = NIM_NIL;	line_2.len = 0; line_2.p = NIM_NIL;	colontmpD_ = (tyObject_ActivationcolonObjectType___jwMMFyLWVLpBU9ca5Dr6Vrw*)0;	colontmpD__2 = (tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ*)0;	colontmpD__3 = (tyObject_ActivationcolonObjectType___jwMMFyLWVLpBU9ca5Dr6Vrw*)0;	colontmpD__4 = (tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ*)0;
#line 28 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"
	nimln_(28, "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryme"
"mfile.nim");
#line 28 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"

#line 28 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"
	T2_ = (tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ*)0;	T2_ = evalArgInfix__7W5SyHus4xS1zyMEKJKT6Q_2(spry);	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;	if (T2_ && !isObj((*T2_).Sup.m_type, "|spryvm.sprymemfile.MemfileNode:ObjectType|spryvm.spryvm.Value:"
"ObjectType|spryvm.spryvm.Node:ObjectType|RootObj|")){ raiseObjectConversionError(); goto LA1_;}	result = &((tyObject_MemfileNodecolonObjectType___SClUH77NqezEgy7ah1Yt5Q*) (T2_))->Sup.Sup;
#line 29 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"
	nimln_(29, "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryme"
"mfile.nim");	if (result && !isObj((*result).Sup.m_type, "|spryvm.sprymemfile.MemfileNode:ObjectType|spryvm.spryvm.Value:"
"ObjectType|spryvm.spryvm.Node:ObjectType|RootObj|")){ raiseObjectConversionError(); goto LA1_;}	memfile = (*(*((tyObject_MemfileNodecolonObjectType___SClUH77NqezEgy7ah1Yt5Q**) (&(result))))).memfile;
#line 30 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"
	nimln_(30, "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryme"
"mfile.nim");
#line 30 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"

#line 30 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"
	T3_ = (tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ*)0;	T3_ = evalArg__7W5SyHus4xS1zyMEKJKT6Q_3(spry);	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;	if (T3_ && !isObj((*T3_).Sup.m_type, "|spryvm.spryvm.Blok:ObjectType|spryvm.spryvm.SeqComposite:Objec"
"tType|spryvm.spryvm.Composite:ObjectType|spryvm.spryvm.Node:Obje"
"ctType|RootObj|")){ raiseObjectConversionError(); goto LA1_;}	blk = ((tyObject_BlokcolonObjectType___UIJsSh2kxAc9acGwoSYj4xw*) (T3_));
#line 947 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryvm.nim"
	nimln_(947, "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryvm"
".nim");
#line 947 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryvm.nim"
	eq___759cyjGBfDaxSOPsM2JffXw(&current, (*spry).currentActivation);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
#line 119 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
	nimln_(119, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");	if ((NU)(((NI) 0)) >= (NU)(*(*current).body).nodes.len){ raiseIndexError2(((NI) 0),(*(*current).body).nodes.len-1); goto LA1_;}
#line 119 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
	eq___8eMhTKv1RRUDzX38ucu4fA(&orig, (*(*current).body).nodes.p->data[((NI) 0)]);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
#line 34 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"
	nimln_(34, "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryme"
"mfile.nim");	oldpos = (*current).pos;
#line 35 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"
	nimln_(35, "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryme"
"mfile.nim");	(*current).pos = ((NI) 0);
#line 36 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"
	nimln_(36, "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryme"
"mfile.nim");
#line 36 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"
	activation = newActivation__z9aNhDNx4cfCuoQWvI0ReBw(blk);	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;	{
#line 463 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim"
		nimln_(463, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim");
#line 463 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim"

#line 463 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim"
		buf = rawNewString(((NI) 80));		{			{				tyObject_MemSlice__fWlUmmDo9aQGKOHWrhWV54Q ms;				tyObject_MemSlice__fWlUmmDo9aQGKOHWrhWV54Q ms_2;				void* ending;				NI remaining;				nimZeroMem((void*)(&ms), sizeof(tyObject_MemSlice__fWlUmmDo9aQGKOHWrhWV54Q));				nimZeroMem((void*)(&ms_2), sizeof(tyObject_MemSlice__fWlUmmDo9aQGKOHWrhWV54Q));				ending = (void*)0;
#line 416 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim"
				nimln_(416, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim");				ms_2.data = memfile.mem;
#line 417 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim"
				nimln_(417, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim");				remaining = memfile.size;				{
#line 418 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim"
					nimln_(418, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim");					while (1) {						NI T24_;						tyObject_StringValcolonObjectType___OzaVEa2ZspAxtzIz1MQfcA* T37_;						NimStringV2 blitTmp_2;						tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ* T38_;						tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ* T39_;						NI T44_;						NI T45_;						NI TM__pwrqdpRNZbc1rhRZbgtEow_20;
#line 418 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim"
						if (!(((NI) 0) < remaining)) goto LA8;

#line 419 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim"
						nimln_(419, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim");
#line 419 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim"
						ending = memchr(ms_2.data, 10, remaining);
#line 420 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim"
						nimln_(420, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim");						{							tyObject_StringValcolonObjectType___OzaVEa2ZspAxtzIz1MQfcA* T17_;							NimStringV2 blitTmp;							tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ* T18_;							tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ* T19_;
#line 420 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim"
							if (!(ending == NIM_NIL)) goto LA11_;

#line 421 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim"
							nimln_(421, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim");							ms_2.size = remaining;
#line 445 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim"
							nimln_(445, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim");							ms = ms_2;
#line 446 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim"
							nimln_(446, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim");							if ((ms.size) < ((NI) 0) || (ms.size) > ((NI) IL64(9223372036854775807))){ raiseRangeErrorI(ms.size, ((NI) 0), ((NI) IL64(9223372036854775807))); goto LA1_;}							setLengthStrV2((&buf), ((NI) (ms.size)));
#line 447 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim"
							nimln_(447, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim");							{
#line 447 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim"
								if (!(((NI) 0) < ms.size)) goto LA15_;

#line 448 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim"
								nimln_(448, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim");								if ((NU)(((NI) 0)) >= (NU)buf.len){ raiseIndexError2(((NI) 0),buf.len-1); goto LA1_;}								if ((ms.size) < ((NI) 0) || (ms.size) > ((NI) IL64(9223372036854775807))){ raiseRangeErrorI(ms.size, ((NI) 0), ((NI) IL64(9223372036854775807))); goto LA1_;}
#line 448 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim"
								copyMem__i80o3k0SgEI5gTRCzYdyWAsystem(((void*) ((&buf.p->data[((NI) 0)]))), ms.data, ((NI) (ms.size)));
							}
							LA15_: ;

#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
							nimln_(49, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
							eq___aBBXmHFBEivKqERloP6zmA_2((&line_2), buf);

#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"

#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
							eqsink___aBBXmHFBEivKqERloP6zmA((&line), buf);

#line 37 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"
							nimln_(37, "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryme"
"mfile.nim");							buf.len = 0; buf.p = NIM_NIL;
#line 119 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
							nimln_(119, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");							if ((NU)(((NI) 0)) >= (NU)(*(*current).body).nodes.len){ raiseIndexError2(((NI) 0),(*(*current).body).nodes.len-1); goto LA1_;}							T17_ = (tyObject_StringValcolonObjectType___OzaVEa2ZspAxtzIz1MQfcA*)0;							T17_ = (tyObject_StringValcolonObjectType___OzaVEa2ZspAxtzIz1MQfcA*) nimNewObj(sizeof(tyObject_StringValcolonObjectType___OzaVEa2ZspAxtzIz1MQfcA));							(*T17_).Sup.Sup.Sup.m_type = (&NTI__OzaVEa2ZspAxtzIz1MQfcA_);
#line 38 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"
							nimln_(38, "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryme"
"mfile.nim");							blitTmp = line;
#line 38 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"
							line.len = 0; line.p = NIM_NIL;							(*T17_).value = blitTmp;							T18_ = (tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ*)0;							T18_ = &T17_->Sup.Sup;
#line 119 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
							nimln_(119, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");							eqsink___8eMhTKv1RRUDzX38ucu4fA_2(&(*(*current).body).nodes.p->data[((NI) 0)], T18_);
							if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
#line 39 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"
							nimln_(39, "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryme"
"mfile.nim");
#line 119 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
							nimln_(119, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");
#line 39 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"
							nimln_(39, "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryme"
"mfile.nim");
#line 39 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"
							colontmpD_ = 0;
#line 947 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryvm.nim"
							nimln_(947, "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryvm"
".nim");
#line 947 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryvm.nim"
							eq___759cyjGBfDaxSOPsM2JffXw(&colontmpD_, activation);
							if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
#line 39 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"
							nimln_(39, "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryme"
"mfile.nim");							T19_ = (tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ*)0;							T19_ = eval__VIBmNwKvb9acnasQzNrtApQ(colontmpD_, spry);							if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
#line 119 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
							nimln_(119, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");							eqsink___8eMhTKv1RRUDzX38ucu4fA_2(&colontmpD__2, T19_);
							if (NIM_UNLIKELY(*nimErr_)) goto LA1_;							(void)(colontmpD__2);

#line 40 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"
							nimln_(40, "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryme"
"mfile.nim");
#line 40 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"
							reset__scJ8nNSlOQVuGEvoEUpjZw(activation);
							if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
#line 41 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"
							nimln_(41, "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryme"
"mfile.nim");							(*current).pos = ((NI) 0);
#line 43 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"
							nimln_(43, "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryme"
"mfile.nim");							{								if (!(*current).returned) goto LA22_;

#line 119 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
								nimln_(119, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");								if ((NU)(((NI) 0)) >= (NU)(*(*current).body).nodes.len){ raiseIndexError2(((NI) 0),(*(*current).body).nodes.len-1); goto LA1_;}
#line 119 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
								eqsink___8eMhTKv1RRUDzX38ucu4fA_2(&(*(*current).body).nodes.p->data[((NI) 0)], orig);
								if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
#line 45 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"
								nimln_(45, "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryme"
"mfile.nim");								orig = 0;
#line 46 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"
								nimln_(46, "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryme"
"mfile.nim");								(*current).pos = oldpos;
#line 47 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"
								nimln_(47, "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryme"
"mfile.nim");
#line 119 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
								nimln_(119, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");
#line 119 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
								eq___8eMhTKv1RRUDzX38ucu4fA(&result, (*current).last);
								if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
#line 119 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"

#line 119 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
								eqdestroy___9aO1dEPkfhJnKjHT0JFTXpA(&colontmpD__4);
								if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
#line 119 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"

#line 119 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
								eqdestroy___9aO1dEPkfhJnKjHT0JFTXpA(&colontmpD__2);
								if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
								nimln_(49, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
								eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&line_2));

#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"

#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
								eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&buf));

#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"

#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
								eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&line));

#line 947 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryvm.nim"
								nimln_(947, "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryvm"
".nim");
#line 947 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryvm.nim"
								eqdestroy___dOERzQgALmYg78PEb20q5Q(&activation);
								if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
#line 119 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
								nimln_(119, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");
#line 119 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
								eqdestroy___9aO1dEPkfhJnKjHT0JFTXpA(&orig);
								if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
#line 947 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryvm.nim"
								nimln_(947, "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryvm"
".nim");
#line 947 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryvm.nim"
								eqdestroy___dOERzQgALmYg78PEb20q5Q(&current);
								if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
#line 314 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryvm.nim"
								nimln_(314, "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryvm"
".nim");
#line 314 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryvm.nim"
								eqdestroy___8fQUMkSQEEPPeEE5xVHN7g(&blk);
								if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;								goto BeforeRet_;
							}
							LA22_: ;

#line 423 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim"
							nimln_(423, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim");							goto LA7;
						}
						LA11_: ;

#line 424 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim"
						nimln_(424, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim");
#line 424 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim"
						T24_ = (NI)0;						T24_ = minusemark___bLhXIfQwxhJGW6yuNG9b4LQmemfiles(ending, ms_2.data);						if (NIM_UNLIKELY(*nimErr_)) goto LA1_;						ms_2.size = T24_;
#line 425 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim"
						nimln_(425, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim");						{							NIM_BOOL T27_;							NIM_BOOL T28_;							NI TM__pwrqdpRNZbc1rhRZbgtEow_18;							NI TM__pwrqdpRNZbc1rhRZbgtEow_19;
#line 425 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim"
							T27_ = (NIM_BOOL)0;
#line 425 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim"
							T28_ = (NIM_BOOL)0;							T28_ = NIM_TRUE;							if (!(T28_)) goto LA29_;

#line 425 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim"
							T28_ = (((NI) 0) < ms_2.size);							LA29_: ;
							T27_ = T28_;							if (!(T27_)) goto LA30_;

#line 425 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim"

#line 425 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim"
							if (nimSubInt(ms_2.size, ((NI) 1), &TM__pwrqdpRNZbc1rhRZbgtEow_18)) { raiseOverflow(); goto LA1_;};							T27_ = ((NU8)(((NCSTRING) (ms_2.data))[(NI)(TM__pwrqdpRNZbc1rhRZbgtEow_18)]) == (NU8)(13));							LA30_: ;
							if (!T27_) goto LA31_;

#line 426 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim"
							nimln_(426, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim");							if (nimSubInt(ms_2.size, ((NI) 1), &TM__pwrqdpRNZbc1rhRZbgtEow_19)) { raiseOverflow(); goto LA1_;};							ms_2.size = (NI)(TM__pwrqdpRNZbc1rhRZbgtEow_19);						}
						LA31_: ;

#line 445 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim"
						nimln_(445, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim");						ms = ms_2;
#line 446 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim"
						nimln_(446, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim");						if ((ms.size) < ((NI) 0) || (ms.size) > ((NI) IL64(9223372036854775807))){ raiseRangeErrorI(ms.size, ((NI) 0), ((NI) IL64(9223372036854775807))); goto LA1_;}						setLengthStrV2((&buf), ((NI) (ms.size)));
#line 447 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim"
						nimln_(447, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim");						{
#line 447 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim"
							if (!(((NI) 0) < ms.size)) goto LA35_;

#line 448 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim"
							nimln_(448, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim");							if ((NU)(((NI) 0)) >= (NU)buf.len){ raiseIndexError2(((NI) 0),buf.len-1); goto LA1_;}							if ((ms.size) < ((NI) 0) || (ms.size) > ((NI) IL64(9223372036854775807))){ raiseRangeErrorI(ms.size, ((NI) 0), ((NI) IL64(9223372036854775807))); goto LA1_;}
#line 448 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim"
							copyMem__i80o3k0SgEI5gTRCzYdyWAsystem(((void*) ((&buf.p->data[((NI) 0)]))), ms.data, ((NI) (ms.size)));
						}
						LA35_: ;

#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
						nimln_(49, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
						eq___aBBXmHFBEivKqERloP6zmA_2((&line_2), buf);

#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"

#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
						eq___aBBXmHFBEivKqERloP6zmA_2((&line), buf);

#line 119 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
						nimln_(119, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");						if ((NU)(((NI) 0)) >= (NU)(*(*current).body).nodes.len){ raiseIndexError2(((NI) 0),(*(*current).body).nodes.len-1); goto LA1_;}						T37_ = (tyObject_StringValcolonObjectType___OzaVEa2ZspAxtzIz1MQfcA*)0;						T37_ = (tyObject_StringValcolonObjectType___OzaVEa2ZspAxtzIz1MQfcA*) nimNewObj(sizeof(tyObject_StringValcolonObjectType___OzaVEa2ZspAxtzIz1MQfcA));						(*T37_).Sup.Sup.Sup.m_type = (&NTI__OzaVEa2ZspAxtzIz1MQfcA_);
#line 38 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"
						nimln_(38, "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryme"
"mfile.nim");						blitTmp_2 = line;
#line 38 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"
						line.len = 0; line.p = NIM_NIL;						(*T37_).value = blitTmp_2;						T38_ = (tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ*)0;						T38_ = &T37_->Sup.Sup;
#line 119 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
						nimln_(119, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");						eqsink___8eMhTKv1RRUDzX38ucu4fA_2(&(*(*current).body).nodes.p->data[((NI) 0)], T38_);
						if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
#line 39 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"
						nimln_(39, "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryme"
"mfile.nim");
#line 119 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
						nimln_(119, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");
#line 39 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"
						nimln_(39, "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryme"
"mfile.nim");
#line 39 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"
						colontmpD__3 = 0;
#line 947 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryvm.nim"
						nimln_(947, "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryvm"
".nim");
#line 947 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryvm.nim"
						eq___759cyjGBfDaxSOPsM2JffXw(&colontmpD__3, activation);
						if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
#line 39 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"
						nimln_(39, "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryme"
"mfile.nim");						T39_ = (tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ*)0;						T39_ = eval__VIBmNwKvb9acnasQzNrtApQ(colontmpD__3, spry);						if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
#line 119 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
						nimln_(119, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");						eqsink___8eMhTKv1RRUDzX38ucu4fA_2(&colontmpD__4, T39_);
						if (NIM_UNLIKELY(*nimErr_)) goto LA1_;						(void)(colontmpD__4);

#line 40 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"
						nimln_(40, "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryme"
"mfile.nim");
#line 40 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"
						reset__scJ8nNSlOQVuGEvoEUpjZw(activation);
						if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
#line 41 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"
						nimln_(41, "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryme"
"mfile.nim");						(*current).pos = ((NI) 0);
#line 43 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"
						nimln_(43, "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryme"
"mfile.nim");						{							if (!(*current).returned) goto LA42_;

#line 119 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
							nimln_(119, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");							if ((NU)(((NI) 0)) >= (NU)(*(*current).body).nodes.len){ raiseIndexError2(((NI) 0),(*(*current).body).nodes.len-1); goto LA1_;}
#line 119 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
							eqsink___8eMhTKv1RRUDzX38ucu4fA_2(&(*(*current).body).nodes.p->data[((NI) 0)], orig);
							if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
#line 45 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"
							nimln_(45, "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryme"
"mfile.nim");							orig = 0;
#line 46 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"
							nimln_(46, "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryme"
"mfile.nim");							(*current).pos = oldpos;
#line 47 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"
							nimln_(47, "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryme"
"mfile.nim");
#line 119 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
							nimln_(119, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");
#line 119 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
							eq___8eMhTKv1RRUDzX38ucu4fA(&result, (*current).last);
							if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
#line 119 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"

#line 119 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
							eqdestroy___9aO1dEPkfhJnKjHT0JFTXpA(&colontmpD__4);
							if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
#line 119 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"

#line 119 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
							eqdestroy___9aO1dEPkfhJnKjHT0JFTXpA(&colontmpD__2);
							if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
							nimln_(49, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
							eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&line_2));

#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"

#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
							eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&buf));

#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"

#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
							eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&line));

#line 947 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryvm.nim"
							nimln_(947, "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryvm"
".nim");
#line 947 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryvm.nim"
							eqdestroy___dOERzQgALmYg78PEb20q5Q(&activation);
							if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
#line 119 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
							nimln_(119, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");
#line 119 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
							eqdestroy___9aO1dEPkfhJnKjHT0JFTXpA(&orig);
							if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
#line 947 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryvm.nim"
							nimln_(947, "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryvm"
".nim");
#line 947 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryvm.nim"
							eqdestroy___dOERzQgALmYg78PEb20q5Q(&current);
							if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
#line 314 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryvm.nim"
							nimln_(314, "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryvm"
".nim");
#line 314 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryvm.nim"
							eqdestroy___8fQUMkSQEEPPeEE5xVHN7g(&blk);
							if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;							goto BeforeRet_;
						}
						LA42_: ;

#line 428 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim"
						nimln_(428, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim");
#line 428 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim"

#line 428 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim"
						T44_ = (NI)0;						T44_ = pluspercent___dgYAo7RfdUVVpvkfKDym8w_2system(((NI) (ptrdiff_t) (ending)), ((NI) 1));						ms_2.data = ((void*) (T44_));
#line 429 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim"
						nimln_(429, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim");
#line 429 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim"

#line 429 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim"

#line 429 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/memfiles.nim"
						T45_ = (NI)0;						T45_ = minusemark___bLhXIfQwxhJGW6yuNG9b4LQmemfiles(ms_2.data, memfile.mem);						if (NIM_UNLIKELY(*nimErr_)) goto LA1_;						if (nimSubInt(memfile.size, T45_, &TM__pwrqdpRNZbc1rhRZbgtEow_20)) { raiseOverflow(); goto LA1_;};						remaining = (NI)(TM__pwrqdpRNZbc1rhRZbgtEow_20);					} LA8: ;
				} LA7: ;
			}
		}
	}

#line 119 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
	nimln_(119, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");	if ((NU)(((NI) 0)) >= (NU)(*(*current).body).nodes.len){ raiseIndexError2(((NI) 0),(*(*current).body).nodes.len-1); goto LA1_;}
#line 119 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
	eqsink___8eMhTKv1RRUDzX38ucu4fA_2(&(*(*current).body).nodes.p->data[((NI) 0)], orig);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
#line 49 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"
	nimln_(49, "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryme"
"mfile.nim");	orig = 0;
#line 50 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"
	nimln_(50, "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryme"
"mfile.nim");	(*current).pos = oldpos;	{		LA1_:;	}
	{		oldNimErrFin1_ = *nimErr_; *nimErr_ = NIM_FALSE;
#line 119 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
		nimln_(119, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");
#line 119 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
		eqdestroy___9aO1dEPkfhJnKjHT0JFTXpA(&colontmpD__4);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
#line 119 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"

#line 119 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
		eqdestroy___9aO1dEPkfhJnKjHT0JFTXpA(&colontmpD__2);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
		nimln_(49, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
		eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&line_2));

#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"

#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
		eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&buf));

#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"

#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
		eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&line));

#line 947 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryvm.nim"
		nimln_(947, "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryvm"
".nim");
#line 947 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryvm.nim"
		eqdestroy___dOERzQgALmYg78PEb20q5Q(&activation);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
#line 119 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
		nimln_(119, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");
#line 119 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
		eqdestroy___9aO1dEPkfhJnKjHT0JFTXpA(&orig);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
#line 947 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryvm.nim"
		nimln_(947, "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryvm"
".nim");
#line 947 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryvm.nim"
		eqdestroy___dOERzQgALmYg78PEb20q5Q(&current);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
#line 314 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryvm.nim"
		nimln_(314, "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryvm"
".nim");
#line 314 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryvm.nim"
		eqdestroy___8fQUMkSQEEPPeEE5xVHN7g(&blk);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;		*nimErr_ = oldNimErrFin1_;	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}BeforeRet_: ;
	popFrame();	return result;}

#line 12 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"
N_LIB_PRIVATE N_NIMCALL(void, addMemfile__idLyJlGbGlFTm811uQu9a7w)(tyObject_InterpretercolonObjectType___9a9c0PsXJdclNJBQRoT5OKJg* spry) {	tyProc__KzxxW30gLaLhm4JG7rojSg T1_;	tyObject_PrimFunccolonObjectType___Bo87RnDP4hF7V59b6rcAxSQ* T2_;	tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ* T3_;	tyProc__KzxxW30gLaLhm4JG7rojSg T4_;	tyObject_PrimMethcolonObjectType___7evgxa2ozVE9bj7jSo6ShwQ* T5_;	tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ* T6_;	tyProc__KzxxW30gLaLhm4JG7rojSg T7_;	tyObject_PrimFunccolonObjectType___Bo87RnDP4hF7V59b6rcAxSQ* T8_;	tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ* T9_;	tyProc__KzxxW30gLaLhm4JG7rojSg T10_;	tyObject_PrimMethcolonObjectType___7evgxa2ozVE9bj7jSo6ShwQ* T11_;	tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ* T12_;NIM_BOOL* nimErr_;	nimfr_("addMemfile", "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryme"
"mfile.nim");{nimErr_ = nimErrorFlag();
#line 14 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"
	nimln_(14, "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryme"
"mfile.nim");
#line 1350 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryvm.nim"
	nimln_(1350, "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryvm"
".nim");	nimZeroMem((void*)(&T1_), sizeof(tyProc__KzxxW30gLaLhm4JG7rojSg));	T1_.ClP_0 = ((TM__pwrqdpRNZbc1rhRZbgtEow_6) (colonanonymous___dplzm2YJ7bZn9b4A9bfAbXqQ)); T1_.ClE_0 = NIM_NIL;
#line 1350 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryvm.nim"
	T2_ = (tyObject_PrimFunccolonObjectType___Bo87RnDP4hF7V59b6rcAxSQ*)0;	T2_ = newPrimFunc__nBoMFEu3I4ov5PqnQKilAA(T1_);	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	T3_ = (tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ*)0;	T3_ = &T2_->Sup;
#line 14 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"
	nimln_(14, "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryme"
"mfile.nim");	makeWord__jieY5gv6B4AaNgmJTiZOCQ(spry, TM__pwrqdpRNZbc1rhRZbgtEow_5, T3_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
#line 17 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"
	nimln_(17, "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryme"
"mfile.nim");
#line 1354 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryvm.nim"
	nimln_(1354, "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryvm"
".nim");	nimZeroMem((void*)(&T4_), sizeof(tyProc__KzxxW30gLaLhm4JG7rojSg));	T4_.ClP_0 = ((TM__pwrqdpRNZbc1rhRZbgtEow_9) (colonanonymous___dplzm2YJ7bZn9b4A9bfAbXqQ_2)); T4_.ClE_0 = NIM_NIL;
#line 1354 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryvm.nim"
	T5_ = (tyObject_PrimMethcolonObjectType___7evgxa2ozVE9bj7jSo6ShwQ*)0;	T5_ = newPrimMeth__7XdBOD8x4C4vz9aR71T9bfkA(T4_);	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	T6_ = (tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ*)0;	T6_ = &T5_->Sup.Sup;
#line 17 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"
	nimln_(17, "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryme"
"mfile.nim");	makeWord__jieY5gv6B4AaNgmJTiZOCQ(spry, TM__pwrqdpRNZbc1rhRZbgtEow_8, T6_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
#line 20 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"
	nimln_(20, "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryme"
"mfile.nim");
#line 1350 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryvm.nim"
	nimln_(1350, "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryvm"
".nim");	nimZeroMem((void*)(&T7_), sizeof(tyProc__KzxxW30gLaLhm4JG7rojSg));	T7_.ClP_0 = ((TM__pwrqdpRNZbc1rhRZbgtEow_15) (colonanonymous___dplzm2YJ7bZn9b4A9bfAbXqQ_3)); T7_.ClE_0 = NIM_NIL;
#line 1350 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryvm.nim"
	T8_ = (tyObject_PrimFunccolonObjectType___Bo87RnDP4hF7V59b6rcAxSQ*)0;	T8_ = newPrimFunc__nBoMFEu3I4ov5PqnQKilAA(T7_);	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	T9_ = (tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ*)0;	T9_ = &T8_->Sup;
#line 20 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"
	nimln_(20, "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryme"
"mfile.nim");	makeWord__jieY5gv6B4AaNgmJTiZOCQ(spry, TM__pwrqdpRNZbc1rhRZbgtEow_11, T9_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
#line 27 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"
	nimln_(27, "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryme"
"mfile.nim");
#line 1354 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryvm.nim"
	nimln_(1354, "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryvm"
".nim");	nimZeroMem((void*)(&T10_), sizeof(tyProc__KzxxW30gLaLhm4JG7rojSg));	T10_.ClP_0 = ((TM__pwrqdpRNZbc1rhRZbgtEow_21) (colonanonymous___dplzm2YJ7bZn9b4A9bfAbXqQ_4)); T10_.ClE_0 = NIM_NIL;
#line 1354 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryvm.nim"
	T11_ = (tyObject_PrimMethcolonObjectType___7evgxa2ozVE9bj7jSo6ShwQ*)0;	T11_ = newPrimMeth__7XdBOD8x4C4vz9aR71T9bfkA(T10_);	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	T12_ = (tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ*)0;	T12_ = &T11_->Sup.Sup;
#line 27 "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/sprymemfile.nim"
	nimln_(27, "/Volumes/datastore/projects/pt/third-party/spryvm/spryvm/spryme"
"mfile.nim");	makeWord__jieY5gv6B4AaNgmJTiZOCQ(spry, TM__pwrqdpRNZbc1rhRZbgtEow_17, T12_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}BeforeRet_: ;
	popFrame();}
N_LIB_PRIVATE N_NIMCALL(void, spryvm_sprymemfileDatInit000)(void) {

#line 999999 "generated_not_to_break_here"

/* section: NIM_merge_TYPE_INIT3 */
NTI__SClUH77NqezEgy7ah1Yt5Q_.destructor = (void*)eqdestroy___xh2dJ15yFU7fmHKaAN9awww; NTI__SClUH77NqezEgy7ah1Yt5Q_.size = sizeof(tyObject_MemfileNodecolonObjectType___SClUH77NqezEgy7ah1Yt5Q); NTI__SClUH77NqezEgy7ah1Yt5Q_.align = NIM_ALIGNOF(tyObject_MemfileNodecolonObjectType___SClUH77NqezEgy7ah1Yt5Q); NTI__SClUH77NqezEgy7ah1Yt5Q_.name = "|spryvm.sprymemfile.MemfileNode:ObjectType|spryvm.spryvm.Value:"
"ObjectType|spryvm.spryvm.Node:ObjectType|RootObj|";
; NTI__SClUH77NqezEgy7ah1Yt5Q_.traceImpl = (void*)NIM_NIL; NTI__SClUH77NqezEgy7ah1Yt5Q_.disposeImpl = (void*)NIM_NIL;}

