/* Generated by Nim Compiler v1.3.3 */
/*   (c) 2020 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w -g  -I/Users/elcritch/.asdf/installs/nim/devel/lib -I/Volumes/datastore/projects/pt/third-party/spryvm/tests -o /Volumes/datastore/projects/pt/third-party/spryvm/tests/_nimcache/@mspryiotest.nim.c.o /Volumes/datastore/projects/pt/third-party/spryvm/tests/_nimcache/@mspryiotest.nim.c */
#define NIM_INTBITS 64

/* section: NIM_merge_HEADERS */

#include "nimbase.h"
#include <string.h>
#include <stdlib.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix

/* section: NIM_merge_FRAME_DEFINES */
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
  
/* section: NIM_merge_FORWARD_TYPES */
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_OutputFormattercolonObjectType___F9cVkVj1qOwgl27pKTy0srg tyObject_OutputFormattercolonObjectType___F9cVkVj1qOwgl27pKTy0srg;
typedef struct tyObject_InterpretercolonObjectType___9a9c0PsXJdclNJBQRoT5OKJg tyObject_InterpretercolonObjectType___9a9c0PsXJdclNJBQRoT5OKJg;
typedef struct tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ;
typedef struct Exception Exception;
typedef struct tyObject_TestResult__GEvSVSxdPWWgMGM48ywEYQ tyObject_TestResult__GEvSVSxdPWWgMGM48ywEYQ;
typedef struct tySequence__shvncLWJZ4vpydQXcCi7CA tySequence__shvncLWJZ4vpydQXcCi7CA;
typedef struct tySequence__shvncLWJZ4vpydQXcCi7CA_Content tySequence__shvncLWJZ4vpydQXcCi7CA_Content;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ tySequence__sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content;
typedef struct tyObject_ParsercolonObjectType___9bkpYJZgm7rXSoRQ1xc0nBA tyObject_ParsercolonObjectType___9bkpYJZgm7rXSoRQ1xc0nBA;
typedef struct tyObject_ActivationcolonObjectType___jwMMFyLWVLpBU9ca5Dr6Vrw tyObject_ActivationcolonObjectType___jwMMFyLWVLpBU9ca5Dr6Vrw;
typedef struct tyObject_RootActivationcolonObjectType___iVrg9cFaeTAqppeKtHaL8cg tyObject_RootActivationcolonObjectType___iVrg9cFaeTAqppeKtHaL8cg;
typedef struct tyObject_MapcolonObjectType___EsnExRpqJxGuuJFiAD81hg tyObject_MapcolonObjectType___EsnExRpqJxGuuJFiAD81hg;
typedef struct tyObject_BlokcolonObjectType___UIJsSh2kxAc9acGwoSYj4xw tyObject_BlokcolonObjectType___UIJsSh2kxAc9acGwoSYj4xw;
typedef struct RootObj RootObj;
typedef struct TNimType TNimType;
typedef struct tySequence__uB9b75OUPRENsBAu4AnoePA tySequence__uB9b75OUPRENsBAu4AnoePA;
typedef struct tySequence__uB9b75OUPRENsBAu4AnoePA_Content tySequence__uB9b75OUPRENsBAu4AnoePA_Content;
typedef struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA;

/* section: NIM_merge_TYPES */
struct NimStrPayload {NI cap;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {NI len;
NimStrPayload* p;
};
typedef NU8 tyEnum_TestStatus__W9bTUg9c9a7UlIYkKYmd5uasQ;
struct tyObject_TestResult__GEvSVSxdPWWgMGM48ywEYQ {NimStringV2 suiteName;
NimStringV2 testName;
tyEnum_TestStatus__W9bTUg9c9a7UlIYkKYmd5uasQ status;
};
struct tySequence__shvncLWJZ4vpydQXcCi7CA {
  NI len; tySequence__shvncLWJZ4vpydQXcCi7CA_Content* p;
};
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ {
  NI len; tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content* p;
};
struct tyObject_InterpretercolonObjectType___9a9c0PsXJdclNJBQRoT5OKJg {tyObject_ParsercolonObjectType___9bkpYJZgm7rXSoRQ1xc0nBA* parser;
tyObject_ActivationcolonObjectType___jwMMFyLWVLpBU9ca5Dr6Vrw* currentActivation;
tyObject_RootActivationcolonObjectType___iVrg9cFaeTAqppeKtHaL8cg* rootActivation;
tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ* lastSelf;
tyObject_MapcolonObjectType___EsnExRpqJxGuuJFiAD81hg* root;
tyObject_BlokcolonObjectType___UIJsSh2kxAc9acGwoSYj4xw* modules;
tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ* trueVal;
tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ* falseVal;
tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ* nilVal;
tyObject_BlokcolonObjectType___UIJsSh2kxAc9acGwoSYj4xw* emptyBlok;
tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ* objectTag;
tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ* moduleTag;
};
struct TNimType {void* destructor;
NI size;
NI align;
NCSTRING name;
void* traceImpl;
void* disposeImpl;
};
struct RootObj {TNimType* m_type;};
struct tySequence__uB9b75OUPRENsBAu4AnoePA {
  NI len; tySequence__uB9b75OUPRENsBAu4AnoePA_Content* p;
};
struct Exception {  RootObj Sup;Exception* parent;
NCSTRING name;
NimStringV2 message;
tySequence__uB9b75OUPRENsBAu4AnoePA trace;
Exception* up;
};


#ifndef tySequence__shvncLWJZ4vpydQXcCi7CA_Content_PP
#define tySequence__shvncLWJZ4vpydQXcCi7CA_Content_PP
struct tySequence__shvncLWJZ4vpydQXcCi7CA_Content { NI cap; tyObject_OutputFormattercolonObjectType___F9cVkVj1qOwgl27pKTy0srg* data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content_PP
#define tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content_PP
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content_PP
#define tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content_PP
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content_PP
#define tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content_PP
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content_PP
#define tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content_PP
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE];};
#endif

      struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA {NCSTRING procname;
NI line;
NCSTRING filename;
};


#ifndef tySequence__uB9b75OUPRENsBAu4AnoePA_Content_PP
#define tySequence__uB9b75OUPRENsBAu4AnoePA_Content_PP
struct tySequence__uB9b75OUPRENsBAu4AnoePA_Content { NI cap; tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content_PP
#define tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content_PP
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content_PP
#define tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content_PP
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE];};
#endif

      
/* section: NIM_merge_PROC_HEADERS */
N_LIB_PRIVATE N_NIMCALL(void, ensureInitialized__PRD4IUUOrtlUkEdtJsvXEg)(void);
N_LIB_PRIVATE N_NIMCALL(void, eq___q9b1rGCpRgO9aMrUqDNKr8xg)(tyObject_OutputFormattercolonObjectType___F9cVkVj1qOwgl27pKTy0srg** dest, tyObject_OutputFormattercolonObjectType___F9cVkVj1qOwgl27pKTy0srg* src);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i, NI n);
N_LIB_PRIVATE N_NIMCALL(void, suiteStarted__j0mPLQ9c5pzduNBKNlfnFlg)(tyObject_OutputFormattercolonObjectType___F9cVkVj1qOwgl27pKTy0srg* formatter, NimStringV2 suiteName);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__W9cjVocn1tjhW7p7xohJj6A)(NimStringV2 msg);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, shouldRun__FW0uR9cZPUde1S2WLzSdSZQ)(NimStringV2 currentSuiteName, NimStringV2 testName);
N_LIB_PRIVATE N_NIMCALL(void*, newSeqPayload)(NI cap, NI elemSize, NI elemAlign);
N_LIB_PRIVATE N_NIMCALL(void, testStarted__9aN6nyiOKNgU81zEfFgR3vA)(tyObject_OutputFormattercolonObjectType___F9cVkVj1qOwgl27pKTy0srg* formatter, NimStringV2 testName);
N_LIB_PRIVATE N_NIMCALL(tyObject_InterpretercolonObjectType___9a9c0PsXJdclNJBQRoT5OKJg*, newInterpreter__OuvnitWQkoa1f5n9ccxSoDw)(void);
N_LIB_PRIVATE N_NIMCALL(void, addCore__9aGw28fmPhn0boCFqGkv2oQ)(tyObject_InterpretercolonObjectType___9a9c0PsXJdclNJBQRoT5OKJg* spry);
N_LIB_PRIVATE N_NIMCALL(void, addIO__i0Nqoj6flnQbJabPkSmo1g)(tyObject_InterpretercolonObjectType___9a9c0PsXJdclNJBQRoT5OKJg* spry);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___hZfNbxospUoPn58Xzz3STg)(tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ* self);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___8eMhTKv1RRUDzX38ucu4fA_2)(tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ** dest, tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ* src);
N_LIB_PRIVATE N_NIMCALL(tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ*, evalRoot__3ukOIV3jcWKIYIGZtdBXHw)(tyObject_InterpretercolonObjectType___9a9c0PsXJdclNJBQRoT5OKJg* spry, NimStringV2 code);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringV2 a, NimStringV2 b);
static N_INLINE(NIM_BOOL, equalMem__9bGgqEk7RXXl6eqM9c1HdELAsystem)(void* a, void* b, NI size);
static N_INLINE(int, nimCmpMem)(void* a, void* b, NI size);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(void, checkpoint__GcyHRjPNZ3mrdaHmiIrEXA)(NimStringV2 msg);
static N_INLINE(void, appendString)(NimStringV2* dest, NimStringV2 src);
static N_INLINE(void, copyMem__i80o3k0SgEI5gTRCzYdyWAsystem)(void* dest, void* source, NI size);
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i, NI64 a, NI64 b);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, rawNewString)(NI space);
N_LIB_PRIVATE N_NIMCALL(void, failureOccurred__rS69ckJD2qVNsK841qIsLQg)(tyObject_OutputFormattercolonObjectType___F9cVkVj1qOwgl27pKTy0srg* formatter, tySequence__sM4lkSb7zS6F7OVMvW9cffQ checkpoints, NimStringV2 stackTrace);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___r6aagoRVuov7HvfEjIi3Uw)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ* dest, tySequence__sM4lkSb7zS6F7OVMvW9cffQ src);
static N_INLINE(Exception*, getCurrentException)(void);
N_LIB_PRIVATE N_NIMCALL(void, eq___rR9boD7urcxl7uyUtE46AOA)(Exception** dest, Exception* src);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___aBBXmHFBEivKqERloP6zmA)(NimStringV2* dest, NimStringV2 src);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, cstrToNimstr)(NCSTRING str);
static N_INLINE(NimStringV2, getCurrentExceptionMsg__jLt3ACHcgYt9bbV4Vf9a5mgwsystem)(void);
N_LIB_PRIVATE N_NIMCALL(void, eq___aBBXmHFBEivKqERloP6zmA_2)(NimStringV2* dest, NimStringV2 src);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, getStackTrace__UTyxM84G9cIKwBP74ZFOh4A)(Exception* e);
static N_INLINE(void, popCurrentException)(void);
static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem__zxfKBYntu9cBapkhrCOk1fgmemory)(void* a, int v, NI size);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, testEnded__ojLWHapKL1jpFxJVjmKgUg)(tyObject_TestResult__GEvSVSxdPWWgMGM48ywEYQ* testResult);
N_LIB_PRIVATE N_NIMCALL(void, suiteEnded__PRD4IUUOrtlUkEdtJsvXEg_2)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ)(NimStringV2* dest);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___9aO1dEPkfhJnKjHT0JFTXpA)(tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ** dest);

/* section: NIM_merge_DATA */
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__7WJ5AEckzChKAlQnTLCM8A_2 = { 7 | NIM_STRLIT_FLAG, "spry io" };
static const NimStringV2 TM__7WJ5AEckzChKAlQnTLCM8A_3 = {7, (NimStrPayload*)&TM__7WJ5AEckzChKAlQnTLCM8A_2};
static const NimStringV2 TM__7WJ5AEckzChKAlQnTLCM8A_4 = {7, (NimStrPayload*)&TM__7WJ5AEckzChKAlQnTLCM8A_2};
static const struct {
  NI cap; NIM_CHAR data[142+1];
} TM__7WJ5AEckzChKAlQnTLCM8A_6 = { 142 | NIM_STRLIT_FLAG, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators.n"
"im(189, 11) `len(a) == L` the length of the seq changed while it"
"erating over it" };
static const NimStringV2 TM__7WJ5AEckzChKAlQnTLCM8A_7 = {142, (NimStrPayload*)&TM__7WJ5AEckzChKAlQnTLCM8A_6};
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__7WJ5AEckzChKAlQnTLCM8A_8 = { 5 | NIM_STRLIT_FLAG, "files" };
static const NimStringV2 TM__7WJ5AEckzChKAlQnTLCM8A_9 = {5, (NimStrPayload*)&TM__7WJ5AEckzChKAlQnTLCM8A_8};
static const NimStringV2 TM__7WJ5AEckzChKAlQnTLCM8A_10 = {5, (NimStrPayload*)&TM__7WJ5AEckzChKAlQnTLCM8A_8};
static const NimStringV2 TM__7WJ5AEckzChKAlQnTLCM8A_12 = {142, (NimStrPayload*)&TM__7WJ5AEckzChKAlQnTLCM8A_6};
static const struct {
  NI cap; NIM_CHAR data[44+1];
} TM__7WJ5AEckzChKAlQnTLCM8A_13 = { 44 | NIM_STRLIT_FLAG, "[((parse readFile \"data.spry\") at: 0) at: 0]" };
static const NimStringV2 TM__7WJ5AEckzChKAlQnTLCM8A_14 = {44, (NimStrPayload*)&TM__7WJ5AEckzChKAlQnTLCM8A_13};
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__7WJ5AEckzChKAlQnTLCM8A_15 = { 6 | NIM_STRLIT_FLAG, "121412" };
static const NimStringV2 TM__7WJ5AEckzChKAlQnTLCM8A_16 = {6, (NimStrPayload*)&TM__7WJ5AEckzChKAlQnTLCM8A_15};
static const struct {
  NI cap; NIM_CHAR data[157+1];
} TM__7WJ5AEckzChKAlQnTLCM8A_17 = { 157 | NIM_STRLIT_FLAG, "/Volumes/datastore/projects/pt/third-party/spryvm/tests/spryiot"
"est.nim(13, 62): Check failed: run(\"((parse readFile \\\"data.spry"
"\\\") at: 0) at: 0\") == \"121412\"" };
static const NimStringV2 TM__7WJ5AEckzChKAlQnTLCM8A_18 = {157, (NimStrPayload*)&TM__7WJ5AEckzChKAlQnTLCM8A_17};
static const struct {
  NI cap; NIM_CHAR data[56+1];
} TM__7WJ5AEckzChKAlQnTLCM8A_19 = { 56 | NIM_STRLIT_FLAG, "run(\"((parse readFile \\\"data.spry\\\") at: 0) at: 0\") was " };
static const NimStringV2 TM__7WJ5AEckzChKAlQnTLCM8A_20 = {56, (NimStrPayload*)&TM__7WJ5AEckzChKAlQnTLCM8A_19};
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__7WJ5AEckzChKAlQnTLCM8A_23 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__7WJ5AEckzChKAlQnTLCM8A_24 = {0, (NimStrPayload*)&TM__7WJ5AEckzChKAlQnTLCM8A_23};
static const NimStringV2 TM__7WJ5AEckzChKAlQnTLCM8A_26 = {142, (NimStrPayload*)&TM__7WJ5AEckzChKAlQnTLCM8A_6};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__7WJ5AEckzChKAlQnTLCM8A_27 = { 1 | NIM_STRLIT_FLAG, "[" };
static const NimStringV2 TM__7WJ5AEckzChKAlQnTLCM8A_28 = {1, (NimStrPayload*)&TM__7WJ5AEckzChKAlQnTLCM8A_27};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__7WJ5AEckzChKAlQnTLCM8A_29 = { 1 | NIM_STRLIT_FLAG, "]" };
static const NimStringV2 TM__7WJ5AEckzChKAlQnTLCM8A_30 = {1, (NimStrPayload*)&TM__7WJ5AEckzChKAlQnTLCM8A_29};
static const struct {
  NI cap; NIM_CHAR data[21+1];
} TM__7WJ5AEckzChKAlQnTLCM8A_31 = { 21 | NIM_STRLIT_FLAG, "Unhandled exception: " };
static const NimStringV2 TM__7WJ5AEckzChKAlQnTLCM8A_32 = {21, (NimStrPayload*)&TM__7WJ5AEckzChKAlQnTLCM8A_31};
static const NimStringV2 TM__7WJ5AEckzChKAlQnTLCM8A_33 = {0, (NimStrPayload*)&TM__7WJ5AEckzChKAlQnTLCM8A_23};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__7WJ5AEckzChKAlQnTLCM8A_34 = { 1 | NIM_STRLIT_FLAG, " " };
static const NimStringV2 TM__7WJ5AEckzChKAlQnTLCM8A_35 = {1, (NimStrPayload*)&TM__7WJ5AEckzChKAlQnTLCM8A_34};
static const NimStringV2 TM__7WJ5AEckzChKAlQnTLCM8A_37 = {142, (NimStrPayload*)&TM__7WJ5AEckzChKAlQnTLCM8A_6};
static const NimStringV2 TM__7WJ5AEckzChKAlQnTLCM8A_38 = {5, (NimStrPayload*)&TM__7WJ5AEckzChKAlQnTLCM8A_8};

/* section: NIM_merge_VARS */
N_LIB_PRIVATE NimStringV2 testSuiteName__d5TZtcslZvIeKAkJRGbLbw;
N_LIB_PRIVATE tyObject_OutputFormattercolonObjectType___F9cVkVj1qOwgl27pKTy0srg* formatter__hIZ9ajwrBvQ3puaq4Cz5CEQ;
N_LIB_PRIVATE tyObject_OutputFormattercolonObjectType___F9cVkVj1qOwgl27pKTy0srg* formatter__hIZ9ajwrBvQ3puaq4Cz5CEQ_2;
N_LIB_PRIVATE tyObject_InterpretercolonObjectType___9a9c0PsXJdclNJBQRoT5OKJg* vm__2Z4sw9bnhmSvXjKwh1ET2sw;
N_LIB_PRIVATE NimStringV2 colonc1___UQ7yHwk9a7kp1BgTfmHYukg;
N_LIB_PRIVATE tyObject_OutputFormattercolonObjectType___F9cVkVj1qOwgl27pKTy0srg* formatterX60gensym33985202___z7MLondCprq5VW5KorOkbg;
N_LIB_PRIVATE Exception* e__LHzMJIXoyFCbAQ1ZNfQllQ;
N_LIB_PRIVATE NimStringV2 eTypeDesc__8izfZITWqXJQWSStoHoewA;
N_LIB_PRIVATE NimStringV2 stackTrace__STS9az9cYGrqitDOOh1Nfqig;
N_LIB_PRIVATE tyObject_OutputFormattercolonObjectType___F9cVkVj1qOwgl27pKTy0srg* formatterX60gensym33995003___9aW4E0Ju47swbQjH9bw5SNYw;
N_LIB_PRIVATE tyObject_TestResult__GEvSVSxdPWWgMGM48ywEYQ testResult__dCs7uy1mdJONvrH2lHVETA;
extern tySequence__shvncLWJZ4vpydQXcCi7CA formatters__55U7g4zhjHV9bCI6emTgDiA;
extern tySequence__shvncLWJZ4vpydQXcCi7CA formatters__55U7g4zhjHV9bCI6emTgDiA;
extern tySequence__shvncLWJZ4vpydQXcCi7CA formatters__55U7g4zhjHV9bCI6emTgDiA;
N_LIB_PRIVATE NIM_BOOL testSetupIMPLFlag__79cREag7hagnw5FDORKWpUQ = NIM_TRUE;
extern tySequence__sM4lkSb7zS6F7OVMvW9cffQ checkpoints__bq5hLRYOyiTcYy29a9akD9c9bQ;
N_LIB_PRIVATE tyEnum_TestStatus__W9bTUg9c9a7UlIYkKYmd5uasQ testStatusIMPL__k34iKCKn5adN8PGQaQevqA = ((tyEnum_TestStatus__W9bTUg9c9a7UlIYkKYmd5uasQ) 0);
extern tySequence__shvncLWJZ4vpydQXcCi7CA formatters__55U7g4zhjHV9bCI6emTgDiA;
extern tySequence__shvncLWJZ4vpydQXcCi7CA formatters__55U7g4zhjHV9bCI6emTgDiA;
extern tySequence__shvncLWJZ4vpydQXcCi7CA formatters__55U7g4zhjHV9bCI6emTgDiA;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern tySequence__shvncLWJZ4vpydQXcCi7CA formatters__55U7g4zhjHV9bCI6emTgDiA;
extern tySequence__shvncLWJZ4vpydQXcCi7CA formatters__55U7g4zhjHV9bCI6emTgDiA;
extern tySequence__sM4lkSb7zS6F7OVMvW9cffQ checkpoints__bq5hLRYOyiTcYy29a9akD9c9bQ;
extern tySequence__shvncLWJZ4vpydQXcCi7CA formatters__55U7g4zhjHV9bCI6emTgDiA;
extern NIM_BOOL abortOnError__Bte3Uiwc4Q19ago2N4C89cUA;
extern NI nim_program_result;
extern tySequence__sM4lkSb7zS6F7OVMvW9cffQ checkpoints__bq5hLRYOyiTcYy29a9akD9c9bQ;
extern Exception* currException__9bVPeDJlYTi9bQApZpfH8wjg;
extern Exception* currException__9bVPeDJlYTi9bQApZpfH8wjg;
extern Exception* currException__9bVPeDJlYTi9bQApZpfH8wjg;
extern tySequence__shvncLWJZ4vpydQXcCi7CA formatters__55U7g4zhjHV9bCI6emTgDiA;
extern tySequence__shvncLWJZ4vpydQXcCi7CA formatters__55U7g4zhjHV9bCI6emTgDiA;
extern tySequence__sM4lkSb7zS6F7OVMvW9cffQ checkpoints__bq5hLRYOyiTcYy29a9akD9c9bQ;
extern tySequence__shvncLWJZ4vpydQXcCi7CA formatters__55U7g4zhjHV9bCI6emTgDiA;
extern NIM_BOOL abortOnError__Bte3Uiwc4Q19ago2N4C89cUA;
extern tySequence__sM4lkSb7zS6F7OVMvW9cffQ checkpoints__bq5hLRYOyiTcYy29a9akD9c9bQ;
extern Exception* currException__9bVPeDJlYTi9bQApZpfH8wjg;
extern Exception* currException__9bVPeDJlYTi9bQApZpfH8wjg;
extern NIM_BOOL nimInErrorMode__759bT87luu8XGcbkw13FUjA;
extern tySequence__sM4lkSb7zS6F7OVMvW9cffQ checkpoints__bq5hLRYOyiTcYy29a9akD9c9bQ;

/* section: NIM_merge_PROCS */

#line 36 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/memory.nim"
static N_INLINE(int, nimCmpMem)(void* a, void* b, NI size) {	int result;	result = (int)0;
#line 38 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/memory.nim"

#line 38 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/memory.nim"
	result = memcmp(a, b, ((size_t) (size)));	return result;}

#line 2140 "/Users/elcritch/.asdf/installs/nim/devel/lib/system.nim"
static N_INLINE(NIM_BOOL, equalMem__9bGgqEk7RXXl6eqM9c1HdELAsystem)(void* a, void* b, NI size) {	NIM_BOOL result;	int T1_;	result = (NIM_BOOL)0;
#line 2141 "/Users/elcritch/.asdf/installs/nim/devel/lib/system.nim"

#line 2141 "/Users/elcritch/.asdf/installs/nim/devel/lib/system.nim"

#line 2141 "/Users/elcritch/.asdf/installs/nim/devel/lib/system.nim"

#line 2141 "/Users/elcritch/.asdf/installs/nim/devel/lib/system.nim"
	T1_ = (int)0;	T1_ = nimCmpMem(a, b, size);	result = (T1_ == ((NI32) 0));	return result;}

#line 541 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
static N_INLINE(void, nimFrame)(TFrame* s) {
#line 542 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	{
#line 542 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
		if (!(framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA3_;

#line 543 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
		(*s).calldepth = ((NI16) 0);	}
	goto LA1_;
	LA3_: ;
	{
#line 546 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"

#line 546 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
		(*s).calldepth = (NI16)((*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1));	}
	LA1_: ;

#line 548 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	(*s).prev = framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
#line 549 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = s;
#line 550 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	{
#line 550 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
		if (!((*s).calldepth == ((NI16) 2000))) goto LA8_;

#line 550 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"

#line 550 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
		callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw();
	}
	LA8_: ;
}

#line 85 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
static N_INLINE(void, popFrame)(void) {
#line 86 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).prev;}

#line 23 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/strmantle.nim"
static N_INLINE(NIM_BOOL, eqStrings)(NimStringV2 a, NimStringV2 b) {	NIM_BOOL result;	NI alen;	NI blen;	nimfr_("eqStrings", "/Users/elcritch/.asdf/installs/nim/devel/lib/system/strmantle.n"
"im");{	result = (NIM_BOOL)0;
#line 24 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/strmantle.nim"
	nimln_(24, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/strmantle.n"
"im");
#line 24 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/strmantle.nim"
	alen = a.len;
#line 25 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/strmantle.nim"
	nimln_(25, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/strmantle.n"
"im");
#line 25 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/strmantle.nim"
	blen = b.len;
#line 26 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/strmantle.nim"
	nimln_(26, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/strmantle.n"
"im");	{
#line 26 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/strmantle.nim"
		if (!(alen == blen)) goto LA3_;

#line 27 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/strmantle.nim"
		nimln_(27, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/strmantle.n"
"im");		{
#line 27 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/strmantle.nim"
			if (!(alen == ((NI) 0))) goto LA7_;

#line 27 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/strmantle.nim"

#line 27 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/strmantle.nim"
			result = NIM_TRUE;			goto BeforeRet_;
		}
		LA7_: ;

#line 28 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/strmantle.nim"
		nimln_(28, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/strmantle.n"
"im");
#line 28 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/strmantle.nim"

#line 28 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/strmantle.nim"
		result = equalMem__9bGgqEk7RXXl6eqM9c1HdELAsystem(((void*) ((&a.p->data[((NI) 0)]))), ((void*) ((&b.p->data[((NI) 0)]))), ((NI) (alen)));		goto BeforeRet_;
	}
	LA3_: ;
	}BeforeRet_: ;
	popFrame();	return result;}

#line 11 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/memory.nim"
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size) {	void* T1_;
#line 13 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/memory.nim"

#line 13 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/memory.nim"
	T1_ = (void*)0;	T1_ = memcpy(dest, source, ((size_t) (size)));}

#line 2132 "/Users/elcritch/.asdf/installs/nim/devel/lib/system.nim"
static N_INLINE(void, copyMem__i80o3k0SgEI5gTRCzYdyWAsystem)(void* dest, void* source, NI size) {
#line 2133 "/Users/elcritch/.asdf/installs/nim/devel/lib/system.nim"

#line 2133 "/Users/elcritch/.asdf/installs/nim/devel/lib/system.nim"
	nimCopyMem(dest, source, size);
}

#line 80 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/strs_v2.nim"
static N_INLINE(void, appendString)(NimStringV2* dest, NimStringV2 src) {{
#line 81 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/strs_v2.nim"
	{		NI TM__7WJ5AEckzChKAlQnTLCM8A_21;		NI TM__7WJ5AEckzChKAlQnTLCM8A_22;
#line 81 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/strs_v2.nim"
		if (!(((NI) 0) < src.len)) goto LA3_;

#line 83 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/strs_v2.nim"

#line 83 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/strs_v2.nim"
		if (nimAddInt(src.len, ((NI) 1), &TM__7WJ5AEckzChKAlQnTLCM8A_21)) { raiseOverflow(); goto BeforeRet_;};		if (((NI)(TM__7WJ5AEckzChKAlQnTLCM8A_21)) < ((NI) 0) || ((NI)(TM__7WJ5AEckzChKAlQnTLCM8A_21)) > ((NI) IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__7WJ5AEckzChKAlQnTLCM8A_21), ((NI) 0), ((NI) IL64(9223372036854775807))); goto BeforeRet_;}
#line 83 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/strs_v2.nim"
		copyMem__i80o3k0SgEI5gTRCzYdyWAsystem(((void*) ((&(*(*dest).p).data[(*dest).len]))), ((void*) ((&(*src.p).data[((NI) 0)]))), ((NI) ((NI)(TM__7WJ5AEckzChKAlQnTLCM8A_21))));

#line 84 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/strs_v2.nim"
		if (nimAddInt((*dest).len, src.len, &TM__7WJ5AEckzChKAlQnTLCM8A_22)) { raiseOverflow(); goto BeforeRet_;};		(*dest).len = (NI)(TM__7WJ5AEckzChKAlQnTLCM8A_22);	}
	LA3_: ;
	}BeforeRet_: ;
}

#line 2304 "/Users/elcritch/.asdf/installs/nim/devel/lib/system.nim"
static N_INLINE(Exception*, getCurrentException)(void) {	Exception* result;	nimfr_("getCurrentException", "/Users/elcritch/.asdf/installs/nim/devel/lib/system.nim");	result = (Exception*)0;
#line 75 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	nimln_(75, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim");
#line 75 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	eq___rR9boD7urcxl7uyUtE46AOA(&result, currException__9bVPeDJlYTi9bQApZpfH8wjg);
	popFrame();	return result;}

#line 2313 "/Users/elcritch/.asdf/installs/nim/devel/lib/system.nim"
static N_INLINE(NimStringV2, getCurrentExceptionMsg__jLt3ACHcgYt9bbV4Vf9a5mgwsystem)(void) {	NimStringV2 result;	NimStringV2 T1_;	nimfr_("getCurrentExceptionMsg", "/Users/elcritch/.asdf/installs/nim/devel/lib/system.nim");{	result.len = 0; result.p = NIM_NIL;
#line 2316 "/Users/elcritch/.asdf/installs/nim/devel/lib/system.nim"
	nimln_(2316, "/Users/elcritch/.asdf/installs/nim/devel/lib/system.nim");	T1_.len = 0; T1_.p = NIM_NIL;
#line 2316 "/Users/elcritch/.asdf/installs/nim/devel/lib/system.nim"
	{
#line 2316 "/Users/elcritch/.asdf/installs/nim/devel/lib/system.nim"
		if (!(currException__9bVPeDJlYTi9bQApZpfH8wjg == NIM_NIL)) goto LA4_;

#line 2316 "/Users/elcritch/.asdf/installs/nim/devel/lib/system.nim"
		result = TM__7WJ5AEckzChKAlQnTLCM8A_33;	}
	goto LA2_;
	LA4_: ;
	{
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
		nimln_(49, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
		eq___aBBXmHFBEivKqERloP6zmA_2((&result), (*currException__9bVPeDJlYTi9bQApZpfH8wjg).message);
	}
	LA2_: ;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();	return result;}

#line 123 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
static N_INLINE(void, popCurrentException)(void) {
#line 75 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"

#line 75 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	eq___rR9boD7urcxl7uyUtE46AOA(&currException__9bVPeDJlYTi9bQApZpfH8wjg, (*currException__9bVPeDJlYTi9bQApZpfH8wjg).up);
}

#line 22 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/memory.nim"
static N_INLINE(void, nimSetMem__zxfKBYntu9cBapkhrCOk1fgmemory)(void* a, int v, NI size) {	void* T1_;
#line 24 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/memory.nim"

#line 24 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/memory.nim"
	T1_ = (void*)0;	T1_ = memset(a, v, ((size_t) (size)));}

#line 424 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {	NIM_BOOL* result;	result = (NIM_BOOL*)0;
#line 425 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	result = (&nimInErrorMode__759bT87luu8XGcbkw13FUjA);	return result;}

#line 33 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/memory.nim"
static N_INLINE(void, nimZeroMem)(void* p, NI size) {NIM_BOOL* nimErr_;{nimErr_ = nimErrorFlag();
#line 34 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/memory.nim"

#line 34 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/memory.nim"
	nimSetMem__zxfKBYntu9cBapkhrCOk1fgmemory(p, ((int) 0), size);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, spryvm_spryiotestInit000)(void) {

#line 999999 "generated_not_to_break_here"
{
	tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ* colontmpD_;	NimStringV2 colontmpD__2;	NimStringV2 colontmpD__3;	NimStringV2 colontmpD__4;	tyEnum_TestStatus__W9bTUg9c9a7UlIYkKYmd5uasQ colontmpD__5;NIM_BOOL oldNimErrFin27_;NIM_BOOL oldNimErrFin3_;NIM_BOOL oldNimErrFin1_;NIM_BOOL* nimErr_;	nimfr_("spryiotest", "/Volumes/datastore/projects/pt/third-party/spryvm/tests/spryiot"
"est.nim");nimErr_ = nimErrorFlag();	colontmpD_ = (tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ*)0;	colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;	colontmpD__3.len = 0; colontmpD__3.p = NIM_NIL;	colontmpD__4.len = 0; colontmpD__4.p = NIM_NIL;	colontmpD__5 = (tyEnum_TestStatus__W9bTUg9c9a7UlIYkKYmd5uasQ)0;	{
#line 6 "/Volumes/datastore/projects/pt/third-party/spryvm/tests/spryiotest.nim"
		nimln_(6, "/Volumes/datastore/projects/pt/third-party/spryvm/tests/spryiot"
"est.nim");		testSuiteName__d5TZtcslZvIeKAkJRGbLbw = TM__7WJ5AEckzChKAlQnTLCM8A_3;
#line 478 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim"
		nimln_(478, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim");
#line 478 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim"
		ensureInitialized__PRD4IUUOrtlUkEdtJsvXEg();
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;		{			NI i;			NI L;			NI T5_;
#line 184 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators.nim"
			nimln_(184, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators.n"
"im");			i = ((NI) 0);
#line 185 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators.nim"
			nimln_(185, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators.n"
"im");
#line 185 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators.nim"
			T5_ = formatters__55U7g4zhjHV9bCI6emTgDiA.len;			L = T5_;			{
#line 186 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators.nim"
				nimln_(186, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators.n"
"im");				while (1) {					NI TM__7WJ5AEckzChKAlQnTLCM8A_5;
#line 186 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators.nim"
					if (!(i < L)) goto LA7;

#line 81 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/seqs_v2.nim"
					nimln_(81, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/seqs_v2.nim");					if ((NU)(i) >= (NU)formatters__55U7g4zhjHV9bCI6emTgDiA.len){ raiseIndexError2(i,formatters__55U7g4zhjHV9bCI6emTgDiA.len-1); goto LA3_;}
#line 81 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/seqs_v2.nim"
					eq___q9b1rGCpRgO9aMrUqDNKr8xg(&formatter__hIZ9ajwrBvQ3puaq4Cz5CEQ, formatters__55U7g4zhjHV9bCI6emTgDiA.p->data[i]);
					if (NIM_UNLIKELY(*nimErr_)) goto LA3_;
#line 481 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim"
					nimln_(481, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim");
#line 481 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim"
					suiteStarted__j0mPLQ9c5pzduNBKNlfnFlg(formatter__hIZ9ajwrBvQ3puaq4Cz5CEQ, TM__7WJ5AEckzChKAlQnTLCM8A_4);
					if (NIM_UNLIKELY(*nimErr_)) goto LA3_;
#line 188 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators.nim"
					nimln_(188, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators.n"
"im");					if (nimAddInt(i, ((NI) 1), &TM__7WJ5AEckzChKAlQnTLCM8A_5)) { raiseOverflow(); goto LA3_;};					i = (NI)(TM__7WJ5AEckzChKAlQnTLCM8A_5);
#line 189 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators.nim"
					nimln_(189, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators.n"
"im");					{						NI T10_;
#line 189 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators.nim"

#line 189 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators.nim"

#line 189 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators.nim"
						T10_ = formatters__55U7g4zhjHV9bCI6emTgDiA.len;						if (!!((T10_ == L))) goto LA11_;

#line 189 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators.nim"

#line 189 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators.nim"
						failedAssertImpl__W9cjVocn1tjhW7p7xohJj6A(TM__7WJ5AEckzChKAlQnTLCM8A_7);
						if (NIM_UNLIKELY(*nimErr_)) goto LA3_;					}
					LA11_: ;
				} LA7: ;
			}
		}

#line 504 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim"
		nimln_(504, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim");
#line 504 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim"
		ensureInitialized__PRD4IUUOrtlUkEdtJsvXEg();
		if (NIM_UNLIKELY(*nimErr_)) goto LA3_;
#line 12 "/Volumes/datastore/projects/pt/third-party/spryvm/tests/spryiotest.nim"
		nimln_(12, "/Volumes/datastore/projects/pt/third-party/spryvm/tests/spryiot"
"est.nim");		{			NIM_BOOL T15_;			tyObject_InterpretercolonObjectType___9a9c0PsXJdclNJBQRoT5OKJg* T28_;
#line 506 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim"
			nimln_(506, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim");
#line 506 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim"
			T15_ = (NIM_BOOL)0;			T15_ = shouldRun__FW0uR9cZPUde1S2WLzSdSZQ(testSuiteName__d5TZtcslZvIeKAkJRGbLbw, TM__7WJ5AEckzChKAlQnTLCM8A_9);			if (NIM_UNLIKELY(*nimErr_)) goto LA3_;			if (!T15_) goto LA16_;

#line 507 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim"
			nimln_(507, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim");			checkpoints__bq5hLRYOyiTcYy29a9akD9c9bQ.len = 0; checkpoints__bq5hLRYOyiTcYy29a9akD9c9bQ.p = (tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content*) newSeqPayload(0, sizeof(NimStringV2), NIM_ALIGNOF(NimStringV2));			{				NI i_2;				NI L_2;				NI T19_;
#line 184 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators.nim"
				nimln_(184, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators.n"
"im");				i_2 = ((NI) 0);
#line 185 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators.nim"
				nimln_(185, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators.n"
"im");
#line 185 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators.nim"
				T19_ = formatters__55U7g4zhjHV9bCI6emTgDiA.len;				L_2 = T19_;				{
#line 186 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators.nim"
					nimln_(186, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators.n"
"im");					while (1) {						NI TM__7WJ5AEckzChKAlQnTLCM8A_11;
#line 186 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators.nim"
						if (!(i_2 < L_2)) goto LA21;

#line 81 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/seqs_v2.nim"
						nimln_(81, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/seqs_v2.nim");						if ((NU)(i_2) >= (NU)formatters__55U7g4zhjHV9bCI6emTgDiA.len){ raiseIndexError2(i_2,formatters__55U7g4zhjHV9bCI6emTgDiA.len-1); goto LA3_;}
#line 81 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/seqs_v2.nim"
						eq___q9b1rGCpRgO9aMrUqDNKr8xg(&formatter__hIZ9ajwrBvQ3puaq4Cz5CEQ_2, formatters__55U7g4zhjHV9bCI6emTgDiA.p->data[i_2]);
						if (NIM_UNLIKELY(*nimErr_)) goto LA3_;
#line 511 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim"
						nimln_(511, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim");
#line 511 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim"
						testStarted__9aN6nyiOKNgU81zEfFgR3vA(formatter__hIZ9ajwrBvQ3puaq4Cz5CEQ_2, TM__7WJ5AEckzChKAlQnTLCM8A_10);
						if (NIM_UNLIKELY(*nimErr_)) goto LA3_;
#line 188 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators.nim"
						nimln_(188, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators.n"
"im");						if (nimAddInt(i_2, ((NI) 1), &TM__7WJ5AEckzChKAlQnTLCM8A_11)) { raiseOverflow(); goto LA3_;};						i_2 = (NI)(TM__7WJ5AEckzChKAlQnTLCM8A_11);
#line 189 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators.nim"
						nimln_(189, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators.n"
"im");						{							NI T24_;
#line 189 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators.nim"

#line 189 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators.nim"

#line 189 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators.nim"
							T24_ = formatters__55U7g4zhjHV9bCI6emTgDiA.len;							if (!!((T24_ == L_2))) goto LA25_;

#line 189 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators.nim"

#line 189 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators.nim"
							failedAssertImpl__W9cjVocn1tjhW7p7xohJj6A(TM__7WJ5AEckzChKAlQnTLCM8A_12);
							if (NIM_UNLIKELY(*nimErr_)) goto LA3_;						}
						LA25_: ;
					} LA21: ;
				}
			}

#line 8 "/Volumes/datastore/projects/pt/third-party/spryvm/tests/spryiotest.nim"
			nimln_(8, "/Volumes/datastore/projects/pt/third-party/spryvm/tests/spryiot"
"est.nim");
#line 8 "/Volumes/datastore/projects/pt/third-party/spryvm/tests/spryiotest.nim"
			T28_ = (tyObject_InterpretercolonObjectType___9a9c0PsXJdclNJBQRoT5OKJg*)0;			T28_ = newInterpreter__OuvnitWQkoa1f5n9ccxSoDw();			if (NIM_UNLIKELY(*nimErr_)) goto LA27_;			vm__2Z4sw9bnhmSvXjKwh1ET2sw = T28_;
#line 9 "/Volumes/datastore/projects/pt/third-party/spryvm/tests/spryiotest.nim"
			nimln_(9, "/Volumes/datastore/projects/pt/third-party/spryvm/tests/spryiot"
"est.nim");
#line 9 "/Volumes/datastore/projects/pt/third-party/spryvm/tests/spryiotest.nim"
			addCore__9aGw28fmPhn0boCFqGkv2oQ(vm__2Z4sw9bnhmSvXjKwh1ET2sw);
			if (NIM_UNLIKELY(*nimErr_)) goto LA27_;
#line 10 "/Volumes/datastore/projects/pt/third-party/spryvm/tests/spryiotest.nim"
			nimln_(10, "/Volumes/datastore/projects/pt/third-party/spryvm/tests/spryiot"
"est.nim");
#line 10 "/Volumes/datastore/projects/pt/third-party/spryvm/tests/spryiotest.nim"
			addIO__i0Nqoj6flnQbJabPkSmo1g(vm__2Z4sw9bnhmSvXjKwh1ET2sw);
			if (NIM_UNLIKELY(*nimErr_)) goto LA27_;			{				tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ* T30_;				NimStringV2 T31_;
#line 13 "/Volumes/datastore/projects/pt/third-party/spryvm/tests/spryiotest.nim"
				nimln_(13, "/Volumes/datastore/projects/pt/third-party/spryvm/tests/spryiot"
"est.nim");
#line 119 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
				nimln_(119, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");
#line 13 "/Volumes/datastore/projects/pt/third-party/spryvm/tests/spryunittest.nim"
				nimln_(13, "/Volumes/datastore/projects/pt/third-party/spryvm/tests/spryuni"
"ttest.nim");
#line 13 "/Volumes/datastore/projects/pt/third-party/spryvm/tests/spryunittest.nim"
				T30_ = (tyObject_NodecolonObjectType___9b2icaXRytXqioWcLSlnKfQ*)0;				T30_ = evalRoot__3ukOIV3jcWKIYIGZtdBXHw(vm__2Z4sw9bnhmSvXjKwh1ET2sw, TM__7WJ5AEckzChKAlQnTLCM8A_14);				if (NIM_UNLIKELY(*nimErr_)) goto LA27_;
#line 119 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
				nimln_(119, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");				eqsink___8eMhTKv1RRUDzX38ucu4fA_2(&colontmpD_, T30_);
				if (NIM_UNLIKELY(*nimErr_)) goto LA27_;
#line 13 "/Volumes/datastore/projects/pt/third-party/spryvm/tests/spryiotest.nim"
				nimln_(13, "/Volumes/datastore/projects/pt/third-party/spryvm/tests/spryiot"
"est.nim");				T31_.len = 0; T31_.p = NIM_NIL;				T31_ = dollar___hZfNbxospUoPn58Xzz3STg(colontmpD_);				if (NIM_UNLIKELY(*nimErr_)) goto LA27_;				colonc1___UQ7yHwk9a7kp1BgTfmHYukg = T31_;
#line 674 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim"
				nimln_(674, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim");				{					NimStringV2 T36_;					tySequence__sM4lkSb7zS6F7OVMvW9cffQ T50_;
#line 674 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim"

#line 671 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim"
					nimln_(671, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim");					if (!!(eqStrings(colonc1___UQ7yHwk9a7kp1BgTfmHYukg, TM__7WJ5AEckzChKAlQnTLCM8A_16))) goto LA34_;

#line 675 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim"
					nimln_(675, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim");
#line 675 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim"
					checkpoint__GcyHRjPNZ3mrdaHmiIrEXA(TM__7WJ5AEckzChKAlQnTLCM8A_18);
					if (NIM_UNLIKELY(*nimErr_)) goto LA27_;
#line 626 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim"
					nimln_(626, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim");
#line 626 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim"
					T36_.len = 0; T36_.p = NIM_NIL;					T36_ = rawNewString(colonc1___UQ7yHwk9a7kp1BgTfmHYukg.len + 56);appendString((&T36_), TM__7WJ5AEckzChKAlQnTLCM8A_20);appendString((&T36_), colonc1___UQ7yHwk9a7kp1BgTfmHYukg);
#line 626 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim"
					checkpoint__GcyHRjPNZ3mrdaHmiIrEXA(T36_);
					if (NIM_UNLIKELY(*nimErr_)) goto LA27_;
#line 567 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim"
					nimln_(567, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim");					testStatusIMPL__k34iKCKn5adN8PGQaQevqA = ((tyEnum_TestStatus__W9bTUg9c9a7UlIYkKYmd5uasQ) 1);
#line 571 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim"
					nimln_(571, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim");
#line 571 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim"
					ensureInitialized__PRD4IUUOrtlUkEdtJsvXEg();
					if (NIM_UNLIKELY(*nimErr_)) goto LA27_;					{						NI i_3;						NI L_3;						NI T38_;
#line 184 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators.nim"
						nimln_(184, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators.n"
"im");						i_3 = ((NI) 0);
#line 185 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators.nim"
						nimln_(185, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators.n"
"im");
#line 185 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators.nim"
						T38_ = formatters__55U7g4zhjHV9bCI6emTgDiA.len;						L_3 = T38_;						{
#line 186 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators.nim"
							nimln_(186, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators.n"
"im");							while (1) {								NI TM__7WJ5AEckzChKAlQnTLCM8A_25;
#line 186 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators.nim"
								if (!(i_3 < L_3)) goto LA40;

#line 81 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/seqs_v2.nim"
								nimln_(81, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/seqs_v2.nim");								if ((NU)(i_3) >= (NU)formatters__55U7g4zhjHV9bCI6emTgDiA.len){ raiseIndexError2(i_3,formatters__55U7g4zhjHV9bCI6emTgDiA.len-1); goto LA27_;}
#line 81 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/seqs_v2.nim"
								eq___q9b1rGCpRgO9aMrUqDNKr8xg(&formatterX60gensym33985202___z7MLondCprq5VW5KorOkbg, formatters__55U7g4zhjHV9bCI6emTgDiA.p->data[i_3]);
								if (NIM_UNLIKELY(*nimErr_)) goto LA27_;
#line 578 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim"
								nimln_(578, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim");
#line 578 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim"
								failureOccurred__rS69ckJD2qVNsK841qIsLQg(formatterX60gensym33985202___z7MLondCprq5VW5KorOkbg, checkpoints__bq5hLRYOyiTcYy29a9akD9c9bQ, TM__7WJ5AEckzChKAlQnTLCM8A_24);
								if (NIM_UNLIKELY(*nimErr_)) goto LA27_;
#line 188 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators.nim"
								nimln_(188, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators.n"
"im");								if (nimAddInt(i_3, ((NI) 1), &TM__7WJ5AEckzChKAlQnTLCM8A_25)) { raiseOverflow(); goto LA27_;};								i_3 = (NI)(TM__7WJ5AEckzChKAlQnTLCM8A_25);
#line 189 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators.nim"
								nimln_(189, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators.n"
"im");								{									NI T43_;
#line 189 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators.nim"

#line 189 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators.nim"

#line 189 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators.nim"
									T43_ = formatters__55U7g4zhjHV9bCI6emTgDiA.len;									if (!!((T43_ == L_3))) goto LA44_;

#line 189 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators.nim"

#line 189 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators.nim"
									failedAssertImpl__W9cjVocn1tjhW7p7xohJj6A(TM__7WJ5AEckzChKAlQnTLCM8A_26);
									if (NIM_UNLIKELY(*nimErr_)) goto LA27_;								}
								LA44_: ;
							} LA40: ;
						}
					}

#line 581 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim"
					nimln_(581, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim");					{						if (!abortOnError__Bte3Uiwc4Q19ago2N4C89cUA) goto LA48_;

#line 581 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim"

#line 581 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim"
						exit(nim_program_result);
					}
					LA48_: ;

#line 2160 "/Users/elcritch/.asdf/installs/nim/devel/lib/system.nim"
					nimln_(2160, "/Users/elcritch/.asdf/installs/nim/devel/lib/system.nim");					T50_.len = 0; T50_.p = NIM_NIL;					T50_.len = 0; T50_.p = (tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content*) newSeqPayload(0, sizeof(NimStringV2), NIM_ALIGNOF(NimStringV2));
#line 2160 "/Users/elcritch/.asdf/installs/nim/devel/lib/system.nim"
					eqsink___r6aagoRVuov7HvfEjIi3Uw((&checkpoints__bq5hLRYOyiTcYy29a9akD9c9bQ), T50_);
				}
				LA34_: ;
			}
			if (NIM_UNLIKELY(*nimErr_)) {				LA27_:;				{					NimStringV2 T54_;					NimStringV2 T55_;					NimStringV2 T56_;					NimStringV2 T57_;					tySequence__sM4lkSb7zS6F7OVMvW9cffQ T71_;					*nimErr_ = NIM_FALSE;
#line 520 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim"
					nimln_(520, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim");
#line 520 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim"
					e__LHzMJIXoyFCbAQ1ZNfQllQ = getCurrentException();
#line 521 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim"
					nimln_(521, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim");
#line 521 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim"
					T54_.len = 0; T54_.p = NIM_NIL;
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
					nimln_(49, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");
#line 521 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim"
					nimln_(521, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim");					T55_.len = 0; T55_.p = NIM_NIL;					T55_ = cstrToNimstr((*e__LHzMJIXoyFCbAQ1ZNfQllQ).name);
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
					nimln_(49, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");					eqsink___aBBXmHFBEivKqERloP6zmA((&colontmpD__2), T55_);
					T54_ = rawNewString(colontmpD__2.len + 2);appendString((&T54_), TM__7WJ5AEckzChKAlQnTLCM8A_28);appendString((&T54_), colontmpD__2);appendString((&T54_), TM__7WJ5AEckzChKAlQnTLCM8A_30);					eTypeDesc__8izfZITWqXJQWSStoHoewA = T54_;
#line 522 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim"
					nimln_(522, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim");
#line 522 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim"
					T56_.len = 0; T56_.p = NIM_NIL;
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
					nimln_(49, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");
#line 522 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim"
					nimln_(522, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim");
#line 522 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim"
					T57_.len = 0; T57_.p = NIM_NIL;					T57_ = getCurrentExceptionMsg__jLt3ACHcgYt9bbV4Vf9a5mgwsystem();
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
					nimln_(49, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");					eqsink___aBBXmHFBEivKqERloP6zmA((&colontmpD__3), T57_);
					T56_ = rawNewString(colontmpD__3.len + eTypeDesc__8izfZITWqXJQWSStoHoewA.len + 22);appendString((&T56_), TM__7WJ5AEckzChKAlQnTLCM8A_32);appendString((&T56_), colontmpD__3);appendString((&T56_), TM__7WJ5AEckzChKAlQnTLCM8A_35);appendString((&T56_), eTypeDesc__8izfZITWqXJQWSStoHoewA);
#line 522 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim"
					nimln_(522, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim");					checkpoint__GcyHRjPNZ3mrdaHmiIrEXA(T56_);
					if (NIM_UNLIKELY(*nimErr_)) goto LA52_;
#line 523 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim"
					nimln_(523, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim");
#line 523 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim"
					stackTrace__STS9az9cYGrqitDOOh1Nfqig = getStackTrace__UTyxM84G9cIKwBP74ZFOh4A(e__LHzMJIXoyFCbAQ1ZNfQllQ);
#line 567 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim"
					nimln_(567, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim");					testStatusIMPL__k34iKCKn5adN8PGQaQevqA = ((tyEnum_TestStatus__W9bTUg9c9a7UlIYkKYmd5uasQ) 1);
#line 571 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim"
					nimln_(571, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim");
#line 571 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim"
					ensureInitialized__PRD4IUUOrtlUkEdtJsvXEg();
					if (NIM_UNLIKELY(*nimErr_)) goto LA52_;					{						NI i_4;						NI L_4;						NI T59_;
#line 184 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators.nim"
						nimln_(184, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators.n"
"im");						i_4 = ((NI) 0);
#line 185 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators.nim"
						nimln_(185, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators.n"
"im");
#line 185 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators.nim"
						T59_ = formatters__55U7g4zhjHV9bCI6emTgDiA.len;						L_4 = T59_;						{
#line 186 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators.nim"
							nimln_(186, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators.n"
"im");							while (1) {								NI TM__7WJ5AEckzChKAlQnTLCM8A_36;
#line 186 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators.nim"
								if (!(i_4 < L_4)) goto LA61;

#line 81 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/seqs_v2.nim"
								nimln_(81, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/seqs_v2.nim");								if ((NU)(i_4) >= (NU)formatters__55U7g4zhjHV9bCI6emTgDiA.len){ raiseIndexError2(i_4,formatters__55U7g4zhjHV9bCI6emTgDiA.len-1); goto LA52_;}
#line 81 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/seqs_v2.nim"
								eq___q9b1rGCpRgO9aMrUqDNKr8xg(&formatterX60gensym33995003___9aW4E0Ju47swbQjH9bw5SNYw, formatters__55U7g4zhjHV9bCI6emTgDiA.p->data[i_4]);
								if (NIM_UNLIKELY(*nimErr_)) goto LA52_;
#line 576 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim"
								nimln_(576, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim");
#line 576 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim"
								failureOccurred__rS69ckJD2qVNsK841qIsLQg(formatterX60gensym33995003___9aW4E0Ju47swbQjH9bw5SNYw, checkpoints__bq5hLRYOyiTcYy29a9akD9c9bQ, stackTrace__STS9az9cYGrqitDOOh1Nfqig);
								if (NIM_UNLIKELY(*nimErr_)) goto LA52_;
#line 188 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators.nim"
								nimln_(188, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators.n"
"im");								if (nimAddInt(i_4, ((NI) 1), &TM__7WJ5AEckzChKAlQnTLCM8A_36)) { raiseOverflow(); goto LA52_;};								i_4 = (NI)(TM__7WJ5AEckzChKAlQnTLCM8A_36);
#line 189 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators.nim"
								nimln_(189, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators.n"
"im");								{									NI T64_;
#line 189 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators.nim"

#line 189 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators.nim"

#line 189 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators.nim"
									T64_ = formatters__55U7g4zhjHV9bCI6emTgDiA.len;									if (!!((T64_ == L_4))) goto LA65_;

#line 189 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators.nim"

#line 189 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators.nim"
									failedAssertImpl__W9cjVocn1tjhW7p7xohJj6A(TM__7WJ5AEckzChKAlQnTLCM8A_37);
									if (NIM_UNLIKELY(*nimErr_)) goto LA52_;								}
								LA65_: ;
							} LA61: ;
						}
					}

#line 581 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim"
					nimln_(581, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim");					{						if (!abortOnError__Bte3Uiwc4Q19ago2N4C89cUA) goto LA69_;

#line 581 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim"

#line 581 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim"
						exit(nim_program_result);
					}
					LA69_: ;

#line 2160 "/Users/elcritch/.asdf/installs/nim/devel/lib/system.nim"
					nimln_(2160, "/Users/elcritch/.asdf/installs/nim/devel/lib/system.nim");					T71_.len = 0; T71_.p = NIM_NIL;					T71_.len = 0; T71_.p = (tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content*) newSeqPayload(0, sizeof(NimStringV2), NIM_ALIGNOF(NimStringV2));
#line 2160 "/Users/elcritch/.asdf/installs/nim/devel/lib/system.nim"
					eqsink___r6aagoRVuov7HvfEjIi3Uw((&checkpoints__bq5hLRYOyiTcYy29a9akD9c9bQ), T71_);
					popCurrentException();					LA52_:;				}
			}
			{				tySequence__sM4lkSb7zS6F7OVMvW9cffQ T77_;				oldNimErrFin27_ = *nimErr_; *nimErr_ = NIM_FALSE;
#line 527 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim"
				nimln_(527, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim");				{
#line 527 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim"
					if (!(testStatusIMPL__k34iKCKn5adN8PGQaQevqA == ((tyEnum_TestStatus__W9bTUg9c9a7UlIYkKYmd5uasQ) 1))) goto LA75_;

#line 528 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim"
					nimln_(528, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim");					nim_program_result = ((NI) 1);				}
				LA75_: ;

#line 529 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim"
				nimln_(529, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim");				nimZeroMem((void*)(&testResult__dCs7uy1mdJONvrH2lHVETA), sizeof(tyObject_TestResult__GEvSVSxdPWWgMGM48ywEYQ));
#line 530 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim"
				nimln_(530, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim");				colontmpD__4.len = 0; colontmpD__4.p = NIM_NIL;
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
				nimln_(49, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
				eq___aBBXmHFBEivKqERloP6zmA_2((&colontmpD__4), testSuiteName__d5TZtcslZvIeKAkJRGbLbw);
				testResult__dCs7uy1mdJONvrH2lHVETA.suiteName = colontmpD__4;				testResult__dCs7uy1mdJONvrH2lHVETA.testName = TM__7WJ5AEckzChKAlQnTLCM8A_38;
#line 532 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim"
				nimln_(532, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim");				colontmpD__5 = testStatusIMPL__k34iKCKn5adN8PGQaQevqA;				testResult__dCs7uy1mdJONvrH2lHVETA.status = colontmpD__5;
#line 534 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim"
				nimln_(534, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim");
#line 534 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim"
				testEnded__ojLWHapKL1jpFxJVjmKgUg((&testResult__dCs7uy1mdJONvrH2lHVETA));
				if (NIM_UNLIKELY(*nimErr_)) goto LA3_;
#line 2160 "/Users/elcritch/.asdf/installs/nim/devel/lib/system.nim"
				nimln_(2160, "/Users/elcritch/.asdf/installs/nim/devel/lib/system.nim");				T77_.len = 0; T77_.p = NIM_NIL;				T77_.len = 0; T77_.p = (tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content*) newSeqPayload(0, sizeof(NimStringV2), NIM_ALIGNOF(NimStringV2));
#line 2160 "/Users/elcritch/.asdf/installs/nim/devel/lib/system.nim"
				eqsink___r6aagoRVuov7HvfEjIi3Uw((&checkpoints__bq5hLRYOyiTcYy29a9akD9c9bQ), T77_);
				*nimErr_ = oldNimErrFin27_;			}
		}
		LA16_: ;
		{			LA3_:;		}
		{			oldNimErrFin3_ = *nimErr_; *nimErr_ = NIM_FALSE;
#line 484 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim"
			nimln_(484, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim");
#line 484 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim"
			suiteEnded__PRD4IUUOrtlUkEdtJsvXEg_2();
			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;			*nimErr_ = oldNimErrFin3_;		}
	}
	{		LA1_:;	}
	{		oldNimErrFin1_ = *nimErr_; *nimErr_ = NIM_FALSE;
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
		nimln_(49, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
		eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&colontmpD__3));

#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"

#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
		eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&colontmpD__2));

#line 119 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
		nimln_(119, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim");
#line 119 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/repr_v2.nim"
		eqdestroy___9aO1dEPkfhJnKjHT0JFTXpA(&colontmpD_);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;		*nimErr_ = oldNimErrFin1_;	}
	BeforeRet_: ;
	popFrame();}
}

