/* Generated by Nim Compiler v1.3.3 */
/*   (c) 2020 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w -g  -I/Users/elcritch/.asdf/installs/nim/devel/lib -I/Volumes/datastore/projects/pt/third-party/spryvm/tests -o /Volumes/datastore/projects/pt/third-party/spryvm/tests/_nimcache/stdlib_strformat.nim.c.o /Volumes/datastore/projects/pt/third-party/spryvm/tests/_nimcache/stdlib_strformat.nim.c */
#define NIM_INTBITS 64

/* section: NIM_merge_HEADERS */

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix

/* section: NIM_merge_FRAME_DEFINES */
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
  
/* section: NIM_merge_FORWARD_TYPES */
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_StandardFormatSpecifier__NDU7AW5Eu6Q69c8cH6RDouQ tyObject_StandardFormatSpecifier__NDU7AW5Eu6Q69c8cH6RDouQ;
typedef struct tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw;
typedef struct tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimType TNimType;
typedef struct tySequence__uB9b75OUPRENsBAu4AnoePA tySequence__uB9b75OUPRENsBAu4AnoePA;
typedef struct tySequence__uB9b75OUPRENsBAu4AnoePA_Content tySequence__uB9b75OUPRENsBAu4AnoePA_Content;
typedef struct TNimNode TNimNode;
typedef struct tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA;
typedef struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA;

/* section: NIM_merge_TYPES */
struct NimStrPayload {NI cap;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {NI len;
NimStrPayload* p;
};
struct tyObject_StandardFormatSpecifier__NDU7AW5Eu6Q69c8cH6RDouQ {NIM_CHAR fill;
NIM_CHAR align;
NIM_CHAR sign;
NIM_BOOL alternateForm;
NIM_BOOL padWithZero;
NI minimumWidth;
NI precision;
NIM_CHAR typ;
NI endPosition;
};
struct TNimType {void* destructor;
NI size;
NI align;
NCSTRING name;
void* traceImpl;
void* disposeImpl;
};
struct RootObj {TNimType* m_type;};
struct tySequence__uB9b75OUPRENsBAu4AnoePA {
  NI len; tySequence__uB9b75OUPRENsBAu4AnoePA_Content* p;
};
struct Exception {  RootObj Sup;Exception* parent;
NCSTRING name;
NimStringV2 message;
tySequence__uB9b75OUPRENsBAu4AnoePA trace;
Exception* up;
};
struct tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA {  Exception Sup;};
struct tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw {  tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA Sup;};
struct TNimNode {char dummy;
};
struct tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA {NI a;
NI b;
};
struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA {NCSTRING procname;
NI line;
NCSTRING filename;
};


#ifndef tySequence__uB9b75OUPRENsBAu4AnoePA_Content_PP
#define tySequence__uB9b75OUPRENsBAu4AnoePA_Content_PP
struct tySequence__uB9b75OUPRENsBAu4AnoePA_Content { NI cap; tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];};
#endif

      
/* section: NIM_merge_PROC_HEADERS */
N_LIB_PRIVATE N_NIMCALL(tyObject_StandardFormatSpecifier__NDU7AW5Eu6Q69c8cH6RDouQ, parseStandardFormatSpecifier__VVCKI4fK6GYPxQ9cDpjISyA)(NimStringV2 s, NI start, NIM_BOOL ignoreUnknownSuffix);
static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem__zxfKBYntu9cBapkhrCOk1fgmemory)(void* a, int v, NI size);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i, NI n);
N_LIB_PRIVATE N_NIMCALL(NI, parseSaturatedNatural__hGWFPKYRsDcYFCjZLM9acZw)(NimStringV2 s, NI* b, NI start);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size);
static N_INLINE(void, appendString)(NimStringV2* dest, NimStringV2 src);
static N_INLINE(void, copyMem__i80o3k0SgEI5gTRCzYdyWAsystem)(void* dest, void* source, NI size);
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i, NI64 a, NI64 b);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___aBBXmHFBEivKqERloP6zmA)(NimStringV2* dest, NimStringV2 src);
static N_INLINE(NimStringV2, X5BX5D___ogYTOKbgqbjPfyC123US1gsystem)(NimStringV2 s, tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA x);
N_NIMCALL(NimStringV2, mnewString)(NI len);
N_LIB_PRIVATE N_NIMCALL(void, nimPrepareStrMutationV2)(NimStringV2* s);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA, dotdot___xNR8BVBMWzS9bXXNMikmyLgsystem)(NI a, NI b);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, rawNewString)(NI space);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e, NCSTRING ename, NCSTRING procname, NCSTRING filename, NI line);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ)(NimStringV2* dest);
N_LIB_PRIVATE N_NIMCALL(void, eq___aBBXmHFBEivKqERloP6zmA_2)(NimStringV2* dest, NimStringV2 src);
static N_INLINE(void, appendChar)(NimStringV2* dest, NIM_CHAR c);
N_LIB_PRIVATE N_NIMCALL(NI, nucruneLen)(NimStringV2 s);
N_LIB_PRIVATE N_NIMCALL(NI, runeOffset__EnrqtYM0boqQqeAIRc9bdmA)(NimStringV2 s, NI pos, NI start);
N_LIB_PRIVATE N_NIMCALL(void, setLengthStrV2)(NimStringV2* s, NI newLen);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, alignString__pfisktkC9crnJPz5c4ILtRg)(NimStringV2 s, NI minimumWidth, NIM_CHAR align, NIM_CHAR fill);
N_LIB_PRIVATE N_NIMCALL(NI, validateUtf8__gZHDHaRdP4jROav7Hun29aA)(NimStringV2 s);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuRepeatChar)(NIM_CHAR c, NI count);
N_LIB_PRIVATE N_NOINLINE(void, raiseDivByZero)(void);
static N_INLINE(NIM_BOOL, nimDivInt)(NI a, NI b, NI* res);
N_LIB_PRIVATE N_NIMCALL(void, prepareAdd)(NimStringV2* s, NI addlen);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nimIntToStr)(NI x);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, formatInt__mfFKm9aYkQ8qj8x65rdunAg)(NI n, NI radix, tyObject_StandardFormatSpecifier__NDU7AW5Eu6Q69c8cH6RDouQ* spec);
static N_INLINE(NIM_BOOL, nimDivInt64)(NI64 a, NI64 b, NI64* res);
static N_INLINE(NimStringV2, mkDigit__MPiQ66k9cc3im5NcFk1Mg9cwstrformat)(NI v, NIM_CHAR typ);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__W9cjVocn1tjhW7p7xohJj6A)(NimStringV2 msg);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nimCharToStr)(NIM_CHAR x);
N_LIB_PRIVATE N_NIMCALL(void, nimAddCharV1)(NimStringV2* s, NIM_CHAR c);

/* section: NIM_merge_DATA */
extern TNimType NTI__yoNlBGx0D2tRizIdhQuENw_;
static const struct {
  NI cap; NIM_CHAR data[37+1];
} TM__qDXzsifTQdn8ucTam9cFp4w_16 = { 37 | NIM_STRLIT_FLAG, "invalid format string, cannot parse: " };
static const NimStringV2 TM__qDXzsifTQdn8ucTam9cFp4w_17 = {37, (NimStrPayload*)&TM__qDXzsifTQdn8ucTam9cFp4w_16};
static const struct {
  NI cap; NIM_CHAR data[64+1];
} TM__qDXzsifTQdn8ucTam9cFp4w_25 = { 64 | NIM_STRLIT_FLAG, "invalid type in format string for string, expected \'s\', but got"
" " };
static const NimStringV2 TM__qDXzsifTQdn8ucTam9cFp4w_26 = {64, (NimStrPayload*)&TM__qDXzsifTQdn8ucTam9cFp4w_25};
static const struct {
  NI cap; NIM_CHAR data[92+1];
} TM__qDXzsifTQdn8ucTam9cFp4w_32 = { 92 | NIM_STRLIT_FLAG, "invalid type in format string for number, expected one  of \'x\',"
" \'X\', \'b\', \'d\', \'o\' but got: " };
static const NimStringV2 TM__qDXzsifTQdn8ucTam9cFp4w_33 = {92, (NimStrPayload*)&TM__qDXzsifTQdn8ucTam9cFp4w_32};
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__qDXzsifTQdn8ucTam9cFp4w_35 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__qDXzsifTQdn8ucTam9cFp4w_36 = {0, (NimStrPayload*)&TM__qDXzsifTQdn8ucTam9cFp4w_35};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__qDXzsifTQdn8ucTam9cFp4w_37 = { 2 | NIM_STRLIT_FLAG, "0x" };
static const NimStringV2 TM__qDXzsifTQdn8ucTam9cFp4w_38 = {2, (NimStrPayload*)&TM__qDXzsifTQdn8ucTam9cFp4w_37};
static const NimStringV2 TM__qDXzsifTQdn8ucTam9cFp4w_39 = {2, (NimStrPayload*)&TM__qDXzsifTQdn8ucTam9cFp4w_37};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__qDXzsifTQdn8ucTam9cFp4w_40 = { 2 | NIM_STRLIT_FLAG, "0b" };
static const NimStringV2 TM__qDXzsifTQdn8ucTam9cFp4w_41 = {2, (NimStrPayload*)&TM__qDXzsifTQdn8ucTam9cFp4w_40};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__qDXzsifTQdn8ucTam9cFp4w_42 = { 2 | NIM_STRLIT_FLAG, "0o" };
static const NimStringV2 TM__qDXzsifTQdn8ucTam9cFp4w_43 = {2, (NimStrPayload*)&TM__qDXzsifTQdn8ucTam9cFp4w_42};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__qDXzsifTQdn8ucTam9cFp4w_44 = { 1 | NIM_STRLIT_FLAG, "0" };
static const NimStringV2 TM__qDXzsifTQdn8ucTam9cFp4w_45 = {1, (NimStrPayload*)&TM__qDXzsifTQdn8ucTam9cFp4w_44};
static const NimStringV2 TM__qDXzsifTQdn8ucTam9cFp4w_46 = {0, (NimStrPayload*)&TM__qDXzsifTQdn8ucTam9cFp4w_35};
static const struct {
  NI cap; NIM_CHAR data[81+1];
} TM__qDXzsifTQdn8ucTam9cFp4w_49 = { 81 | NIM_STRLIT_FLAG, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
"(270, 9) `v < 26` " };
static const NimStringV2 TM__qDXzsifTQdn8ucTam9cFp4w_50 = {81, (NimStrPayload*)&TM__qDXzsifTQdn8ucTam9cFp4w_49};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__qDXzsifTQdn8ucTam9cFp4w_61 = { 1 | NIM_STRLIT_FLAG, "-" };
static const NimStringV2 TM__qDXzsifTQdn8ucTam9cFp4w_62 = {1, (NimStrPayload*)&TM__qDXzsifTQdn8ucTam9cFp4w_61};

/* section: NIM_merge_VARS */
extern NIM_BOOL nimInErrorMode__759bT87luu8XGcbkw13FUjA;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;

/* section: NIM_merge_PROCS */

#line 22 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/memory.nim"
static N_INLINE(void, nimSetMem__zxfKBYntu9cBapkhrCOk1fgmemory)(void* a, int v, NI size) {	void* T1_;
#line 24 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/memory.nim"

#line 24 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/memory.nim"
	T1_ = (void*)0;	T1_ = memset(a, v, ((size_t) (size)));}

#line 424 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {	NIM_BOOL* result;	result = (NIM_BOOL*)0;
#line 425 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	result = (&nimInErrorMode__759bT87luu8XGcbkw13FUjA);	return result;}

#line 33 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/memory.nim"
static N_INLINE(void, nimZeroMem)(void* p, NI size) {NIM_BOOL* nimErr_;{nimErr_ = nimErrorFlag();
#line 34 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/memory.nim"

#line 34 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/memory.nim"
	nimSetMem__zxfKBYntu9cBapkhrCOk1fgmemory(p, ((int) 0), size);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}BeforeRet_: ;
}

#line 11 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/memory.nim"
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size) {	void* T1_;
#line 13 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/memory.nim"

#line 13 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/memory.nim"
	T1_ = (void*)0;	T1_ = memcpy(dest, source, ((size_t) (size)));}

#line 2132 "/Users/elcritch/.asdf/installs/nim/devel/lib/system.nim"
static N_INLINE(void, copyMem__i80o3k0SgEI5gTRCzYdyWAsystem)(void* dest, void* source, NI size) {
#line 2133 "/Users/elcritch/.asdf/installs/nim/devel/lib/system.nim"

#line 2133 "/Users/elcritch/.asdf/installs/nim/devel/lib/system.nim"
	nimCopyMem(dest, source, size);
}

#line 80 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/strs_v2.nim"
static N_INLINE(void, appendString)(NimStringV2* dest, NimStringV2 src) {{
#line 81 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/strs_v2.nim"
	{		NI TM__qDXzsifTQdn8ucTam9cFp4w_18;		NI TM__qDXzsifTQdn8ucTam9cFp4w_19;
#line 81 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/strs_v2.nim"
		if (!(((NI) 0) < src.len)) goto LA3_;

#line 83 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/strs_v2.nim"

#line 83 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/strs_v2.nim"
		if (nimAddInt(src.len, ((NI) 1), &TM__qDXzsifTQdn8ucTam9cFp4w_18)) { raiseOverflow(); goto BeforeRet_;};		if (((NI)(TM__qDXzsifTQdn8ucTam9cFp4w_18)) < ((NI) 0) || ((NI)(TM__qDXzsifTQdn8ucTam9cFp4w_18)) > ((NI) IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__qDXzsifTQdn8ucTam9cFp4w_18), ((NI) 0), ((NI) IL64(9223372036854775807))); goto BeforeRet_;}
#line 83 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/strs_v2.nim"
		copyMem__i80o3k0SgEI5gTRCzYdyWAsystem(((void*) ((&(*(*dest).p).data[(*dest).len]))), ((void*) ((&(*src.p).data[((NI) 0)]))), ((NI) ((NI)(TM__qDXzsifTQdn8ucTam9cFp4w_18))));

#line 84 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/strs_v2.nim"
		if (nimAddInt((*dest).len, src.len, &TM__qDXzsifTQdn8ucTam9cFp4w_19)) { raiseOverflow(); goto BeforeRet_;};		(*dest).len = (NI)(TM__qDXzsifTQdn8ucTam9cFp4w_19);	}
	LA3_: ;
	}BeforeRet_: ;
}

#line 541 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
static N_INLINE(void, nimFrame)(TFrame* s) {
#line 542 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	{
#line 542 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
		if (!(framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA3_;

#line 543 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
		(*s).calldepth = ((NI16) 0);	}
	goto LA1_;
	LA3_: ;
	{
#line 546 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"

#line 546 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
		(*s).calldepth = (NI16)((*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1));	}
	LA1_: ;

#line 548 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	(*s).prev = framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
#line 549 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = s;
#line 550 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	{
#line 550 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
		if (!((*s).calldepth == ((NI16) 2000))) goto LA8_;

#line 550 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"

#line 550 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
		callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw();
	}
	LA8_: ;
}

#line 85 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
static N_INLINE(void, popFrame)(void) {
#line 86 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).prev;}

#line 2445 "/Users/elcritch/.asdf/installs/nim/devel/lib/system.nim"
static N_INLINE(NimStringV2, X5BX5D___ogYTOKbgqbjPfyC123US1gsystem)(NimStringV2 s, tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA x) {	NimStringV2 result;	NI a;	NI L;	NI TM__qDXzsifTQdn8ucTam9cFp4w_20;	NI TM__qDXzsifTQdn8ucTam9cFp4w_21;	NI TM__qDXzsifTQdn8ucTam9cFp4w_22;	nimfr_("[]", "/Users/elcritch/.asdf/installs/nim/devel/lib/system.nim");{	result.len = 0; result.p = NIM_NIL;
#line 2452 "/Users/elcritch/.asdf/installs/nim/devel/lib/system.nim"
	nimln_(2452, "/Users/elcritch/.asdf/installs/nim/devel/lib/system.nim");	a = x.a;
#line 2453 "/Users/elcritch/.asdf/installs/nim/devel/lib/system.nim"
	nimln_(2453, "/Users/elcritch/.asdf/installs/nim/devel/lib/system.nim");
#line 2453 "/Users/elcritch/.asdf/installs/nim/devel/lib/system.nim"

#line 2453 "/Users/elcritch/.asdf/installs/nim/devel/lib/system.nim"

#line 2440 "/Users/elcritch/.asdf/installs/nim/devel/lib/system.nim"
	nimln_(2440, "/Users/elcritch/.asdf/installs/nim/devel/lib/system.nim");
#line 2440 "/Users/elcritch/.asdf/installs/nim/devel/lib/system.nim"
	if (nimSubInt(s.len, x.b, &TM__qDXzsifTQdn8ucTam9cFp4w_20)) { raiseOverflow(); goto BeforeRet_;};	if (nimSubInt((NI)(TM__qDXzsifTQdn8ucTam9cFp4w_20), a, &TM__qDXzsifTQdn8ucTam9cFp4w_21)) { raiseOverflow(); goto BeforeRet_;};	if (nimAddInt((NI)(TM__qDXzsifTQdn8ucTam9cFp4w_21), ((NI) 1), &TM__qDXzsifTQdn8ucTam9cFp4w_22)) { raiseOverflow(); goto BeforeRet_;};	L = (NI)(TM__qDXzsifTQdn8ucTam9cFp4w_22);
#line 2454 "/Users/elcritch/.asdf/installs/nim/devel/lib/system.nim"
	nimln_(2454, "/Users/elcritch/.asdf/installs/nim/devel/lib/system.nim");
#line 2454 "/Users/elcritch/.asdf/installs/nim/devel/lib/system.nim"
	if ((L) < ((NI) 0) || (L) > ((NI) IL64(9223372036854775807))){ raiseRangeErrorI(L, ((NI) 0), ((NI) IL64(9223372036854775807))); goto BeforeRet_;}
#line 2454 "/Users/elcritch/.asdf/installs/nim/devel/lib/system.nim"
	result = mnewString(((NI) (L)));	{		NI i;		NI i_2;		i = (NI)0;
#line 106 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators_1.nim"
		nimln_(106, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators_1"
".nim");		i_2 = ((NI) 0);		{
#line 107 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators_1.nim"
			nimln_(107, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators_1"
".nim");			while (1) {				NI TM__qDXzsifTQdn8ucTam9cFp4w_23;				NI TM__qDXzsifTQdn8ucTam9cFp4w_24;
#line 107 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators_1.nim"
				if (!(i_2 < L)) goto LA3;

#line 2455 "/Users/elcritch/.asdf/installs/nim/devel/lib/system.nim"
				nimln_(2455, "/Users/elcritch/.asdf/installs/nim/devel/lib/system.nim");				i = i_2;				if ((NU)(i) >= (NU)result.len){ raiseIndexError2(i,result.len-1); goto BeforeRet_;}				nimPrepareStrMutationV2((&result));
#line 2455 "/Users/elcritch/.asdf/installs/nim/devel/lib/system.nim"

#line 2455 "/Users/elcritch/.asdf/installs/nim/devel/lib/system.nim"
				if (nimAddInt(i, a, &TM__qDXzsifTQdn8ucTam9cFp4w_23)) { raiseOverflow(); goto BeforeRet_;};				if ((NU)((NI)(TM__qDXzsifTQdn8ucTam9cFp4w_23)) >= (NU)s.len){ raiseIndexError2((NI)(TM__qDXzsifTQdn8ucTam9cFp4w_23),s.len-1); goto BeforeRet_;}				result.p->data[i] = s.p->data[(NI)(TM__qDXzsifTQdn8ucTam9cFp4w_23)];
#line 109 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators_1.nim"
				nimln_(109, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators_1"
".nim");				if (nimAddInt(i_2, ((NI) 1), &TM__qDXzsifTQdn8ucTam9cFp4w_24)) { raiseOverflow(); goto BeforeRet_;};				i_2 = (NI)(TM__qDXzsifTQdn8ucTam9cFp4w_24);			} LA3: ;
		}
	}
	}BeforeRet_: ;
	popFrame();	return result;}

#line 459 "/Users/elcritch/.asdf/installs/nim/devel/lib/system.nim"
static N_INLINE(tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA, dotdot___xNR8BVBMWzS9bXXNMikmyLgsystem)(NI a, NI b) {	tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA result;	nimfr_("..", "/Users/elcritch/.asdf/installs/nim/devel/lib/system.nim");	nimZeroMem((void*)(&result), sizeof(tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA));
#line 469 "/Users/elcritch/.asdf/installs/nim/devel/lib/system.nim"
	nimln_(469, "/Users/elcritch/.asdf/installs/nim/devel/lib/system.nim");	nimZeroMem((void*)(&result), sizeof(tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA));	result.a = a;	result.b = b;	popFrame();	return result;}

#line 368 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
N_LIB_PRIVATE N_NIMCALL(tyObject_StandardFormatSpecifier__NDU7AW5Eu6Q69c8cH6RDouQ, parseStandardFormatSpecifier__VVCKI4fK6GYPxQ9cDpjISyA)(NimStringV2 s, NI start, NIM_BOOL ignoreUnknownSuffix) {	tyObject_StandardFormatSpecifier__NDU7AW5Eu6Q69c8cH6RDouQ result;	NimStringV2 colontmpD_;	NI i;	NI parsedLength;	NI TM__qDXzsifTQdn8ucTam9cFp4w_12;NIM_BOOL* nimErr_;	nimfr_("parseStandardFormatSpecifier", "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");{nimErr_ = nimErrorFlag();	nimZeroMem((void*)(&result), sizeof(tyObject_StandardFormatSpecifier__NDU7AW5Eu6Q69c8cH6RDouQ));	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
#line 379 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
	nimln_(379, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");	result.fill = 32;
#line 380 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
	nimln_(380, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");	result.align = 0;
#line 381 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
	nimln_(381, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");	result.sign = 45;
#line 382 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
	nimln_(382, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");	i = start;
#line 383 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
	nimln_(383, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");	{		NIM_BOOL T4_;		NI TM__qDXzsifTQdn8ucTam9cFp4w_2;		NI TM__qDXzsifTQdn8ucTam9cFp4w_3;		NI TM__qDXzsifTQdn8ucTam9cFp4w_4;		NI TM__qDXzsifTQdn8ucTam9cFp4w_5;
#line 383 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		T4_ = (NIM_BOOL)0;
#line 383 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"

#line 383 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		if (nimAddInt(i, ((NI) 1), &TM__qDXzsifTQdn8ucTam9cFp4w_2)) { raiseOverflow(); goto LA1_;};
#line 383 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		T4_ = ((NI)(TM__qDXzsifTQdn8ucTam9cFp4w_2) < s.len);		if (!(T4_)) goto LA5_;

#line 383 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"

#line 383 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		if (nimAddInt(i, ((NI) 1), &TM__qDXzsifTQdn8ucTam9cFp4w_3)) { raiseOverflow(); goto LA1_;};		if ((NU)((NI)(TM__qDXzsifTQdn8ucTam9cFp4w_3)) >= (NU)s.len){ raiseIndexError2((NI)(TM__qDXzsifTQdn8ucTam9cFp4w_3),s.len-1); goto LA1_;}		T4_ = (((NU8)(s.p->data[(NI)(TM__qDXzsifTQdn8ucTam9cFp4w_3)])) == ((NU8)(60)) || ((NU8)(s.p->data[(NI)(TM__qDXzsifTQdn8ucTam9cFp4w_3)])) == ((NU8)(62)) || ((NU8)(s.p->data[(NI)(TM__qDXzsifTQdn8ucTam9cFp4w_3)])) == ((NU8)(94)));		LA5_: ;
		if (!T4_) goto LA6_;

#line 384 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		nimln_(384, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");		if ((NU)(i) >= (NU)s.len){ raiseIndexError2(i,s.len-1); goto LA1_;}		result.fill = s.p->data[i];
#line 385 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		nimln_(385, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");
#line 385 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		if (nimAddInt(i, ((NI) 1), &TM__qDXzsifTQdn8ucTam9cFp4w_4)) { raiseOverflow(); goto LA1_;};		if ((NU)((NI)(TM__qDXzsifTQdn8ucTam9cFp4w_4)) >= (NU)s.len){ raiseIndexError2((NI)(TM__qDXzsifTQdn8ucTam9cFp4w_4),s.len-1); goto LA1_;}		result.align = s.p->data[(NI)(TM__qDXzsifTQdn8ucTam9cFp4w_4)];
#line 386 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		nimln_(386, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");		if (nimAddInt(i, ((NI) 2), &TM__qDXzsifTQdn8ucTam9cFp4w_5)) { raiseOverflow(); goto LA1_;};		i = (NI)(TM__qDXzsifTQdn8ucTam9cFp4w_5);	}
	goto LA2_;
	LA6_: ;
	{		NIM_BOOL T9_;		NI TM__qDXzsifTQdn8ucTam9cFp4w_6;
#line 387 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		nimln_(387, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");		T9_ = (NIM_BOOL)0;
#line 387 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"

#line 387 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		T9_ = (i < s.len);		if (!(T9_)) goto LA10_;

#line 387 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		if ((NU)(i) >= (NU)s.len){ raiseIndexError2(i,s.len-1); goto LA1_;}		T9_ = (((NU8)(s.p->data[i])) == ((NU8)(60)) || ((NU8)(s.p->data[i])) == ((NU8)(62)) || ((NU8)(s.p->data[i])) == ((NU8)(94)));		LA10_: ;
		if (!T9_) goto LA11_;

#line 388 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		nimln_(388, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");		if ((NU)(i) >= (NU)s.len){ raiseIndexError2(i,s.len-1); goto LA1_;}		result.align = s.p->data[i];
#line 389 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		nimln_(389, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");		if (nimAddInt(i, ((NI) 1), &TM__qDXzsifTQdn8ucTam9cFp4w_6)) { raiseOverflow(); goto LA1_;};		i = (NI)(TM__qDXzsifTQdn8ucTam9cFp4w_6);	}
	goto LA2_;
	LA11_: ;
	LA2_: ;

#line 391 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
	nimln_(391, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");	{		NIM_BOOL T15_;		NI TM__qDXzsifTQdn8ucTam9cFp4w_7;
#line 391 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		T15_ = (NIM_BOOL)0;
#line 391 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"

#line 391 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		T15_ = (i < s.len);		if (!(T15_)) goto LA16_;

#line 391 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		if ((NU)(i) >= (NU)s.len){ raiseIndexError2(i,s.len-1); goto LA1_;}		T15_ = (((NU8)(s.p->data[i])) == ((NU8)(45)) || ((NU8)(s.p->data[i])) == ((NU8)(43)) || ((NU8)(s.p->data[i])) == ((NU8)(32)));		LA16_: ;
		if (!T15_) goto LA17_;

#line 392 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		nimln_(392, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");		if ((NU)(i) >= (NU)s.len){ raiseIndexError2(i,s.len-1); goto LA1_;}		result.sign = s.p->data[i];
#line 393 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		nimln_(393, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");		if (nimAddInt(i, ((NI) 1), &TM__qDXzsifTQdn8ucTam9cFp4w_7)) { raiseOverflow(); goto LA1_;};		i = (NI)(TM__qDXzsifTQdn8ucTam9cFp4w_7);	}
	LA17_: ;

#line 395 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
	nimln_(395, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");	{		NIM_BOOL T21_;		NI TM__qDXzsifTQdn8ucTam9cFp4w_8;
#line 395 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		T21_ = (NIM_BOOL)0;
#line 395 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"

#line 395 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		T21_ = (i < s.len);		if (!(T21_)) goto LA22_;

#line 395 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		if ((NU)(i) >= (NU)s.len){ raiseIndexError2(i,s.len-1); goto LA1_;}		T21_ = ((NU8)(s.p->data[i]) == (NU8)(35));		LA22_: ;
		if (!T21_) goto LA23_;

#line 396 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		nimln_(396, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");		result.alternateForm = NIM_TRUE;
#line 397 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		nimln_(397, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");		if (nimAddInt(i, ((NI) 1), &TM__qDXzsifTQdn8ucTam9cFp4w_8)) { raiseOverflow(); goto LA1_;};		i = (NI)(TM__qDXzsifTQdn8ucTam9cFp4w_8);	}
	LA23_: ;

#line 399 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
	nimln_(399, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");	{		NIM_BOOL T27_;		NIM_BOOL T28_;		NI TM__qDXzsifTQdn8ucTam9cFp4w_9;		NI TM__qDXzsifTQdn8ucTam9cFp4w_10;		NI TM__qDXzsifTQdn8ucTam9cFp4w_11;
#line 399 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		T27_ = (NIM_BOOL)0;
#line 399 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		T28_ = (NIM_BOOL)0;
#line 399 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"

#line 399 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		if (nimAddInt(i, ((NI) 1), &TM__qDXzsifTQdn8ucTam9cFp4w_9)) { raiseOverflow(); goto LA1_;};
#line 399 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		T28_ = ((NI)(TM__qDXzsifTQdn8ucTam9cFp4w_9) < s.len);		if (!(T28_)) goto LA29_;

#line 399 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		if ((NU)(i) >= (NU)s.len){ raiseIndexError2(i,s.len-1); goto LA1_;}		T28_ = ((NU8)(s.p->data[i]) == (NU8)(48));		LA29_: ;
		T27_ = T28_;		if (!(T27_)) goto LA30_;

#line 399 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"

#line 399 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		if (nimAddInt(i, ((NI) 1), &TM__qDXzsifTQdn8ucTam9cFp4w_10)) { raiseOverflow(); goto LA1_;};		if ((NU)((NI)(TM__qDXzsifTQdn8ucTam9cFp4w_10)) >= (NU)s.len){ raiseIndexError2((NI)(TM__qDXzsifTQdn8ucTam9cFp4w_10),s.len-1); goto LA1_;}		T27_ = (((NU8)(s.p->data[(NI)(TM__qDXzsifTQdn8ucTam9cFp4w_10)])) >= ((NU8)(48)) && ((NU8)(s.p->data[(NI)(TM__qDXzsifTQdn8ucTam9cFp4w_10)])) <= ((NU8)(57)));		LA30_: ;
		if (!T27_) goto LA31_;

#line 400 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		nimln_(400, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");		result.padWithZero = NIM_TRUE;
#line 401 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		nimln_(401, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");		if (nimAddInt(i, ((NI) 1), &TM__qDXzsifTQdn8ucTam9cFp4w_11)) { raiseOverflow(); goto LA1_;};		i = (NI)(TM__qDXzsifTQdn8ucTam9cFp4w_11);	}
	LA31_: ;

#line 403 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
	nimln_(403, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");
#line 403 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
	parsedLength = parseSaturatedNatural__hGWFPKYRsDcYFCjZLM9acZw(s, (&result.minimumWidth), i);	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
#line 404 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
	nimln_(404, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");	if (nimAddInt(i, parsedLength, &TM__qDXzsifTQdn8ucTam9cFp4w_12)) { raiseOverflow(); goto LA1_;};	i = (NI)(TM__qDXzsifTQdn8ucTam9cFp4w_12);
#line 405 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
	nimln_(405, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");	{		NIM_BOOL T35_;		NI TM__qDXzsifTQdn8ucTam9cFp4w_13;		NI parsedLengthB;		NI TM__qDXzsifTQdn8ucTam9cFp4w_14;
#line 405 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		T35_ = (NIM_BOOL)0;
#line 405 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"

#line 405 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		T35_ = (i < s.len);		if (!(T35_)) goto LA36_;

#line 405 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		if ((NU)(i) >= (NU)s.len){ raiseIndexError2(i,s.len-1); goto LA1_;}		T35_ = ((NU8)(s.p->data[i]) == (NU8)(46));		LA36_: ;
		if (!T35_) goto LA37_;

#line 406 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		nimln_(406, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");		if (nimAddInt(i, ((NI) 1), &TM__qDXzsifTQdn8ucTam9cFp4w_13)) { raiseOverflow(); goto LA1_;};		i = (NI)(TM__qDXzsifTQdn8ucTam9cFp4w_13);
#line 407 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		nimln_(407, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");
#line 407 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		parsedLengthB = parseSaturatedNatural__hGWFPKYRsDcYFCjZLM9acZw(s, (&result.precision), i);		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
#line 408 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		nimln_(408, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");		if (nimAddInt(i, parsedLengthB, &TM__qDXzsifTQdn8ucTam9cFp4w_14)) { raiseOverflow(); goto LA1_;};		i = (NI)(TM__qDXzsifTQdn8ucTam9cFp4w_14);	}
	goto LA33_;
	LA37_: ;
	{
#line 410 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		nimln_(410, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");		result.precision = ((NI) -1);	}
	LA33_: ;

#line 412 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
	nimln_(412, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");	{		NIM_BOOL T42_;		NI TM__qDXzsifTQdn8ucTam9cFp4w_15;
#line 412 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		T42_ = (NIM_BOOL)0;
#line 412 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"

#line 412 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		T42_ = (i < s.len);		if (!(T42_)) goto LA43_;

#line 412 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		if ((NU)(i) >= (NU)s.len){ raiseIndexError2(i,s.len-1); goto LA1_;}		T42_ = (((NU8)(s.p->data[i])) >= ((NU8)(65)) && ((NU8)(s.p->data[i])) <= ((NU8)(90)) || ((NU8)(s.p->data[i])) >= ((NU8)(97)) && ((NU8)(s.p->data[i])) <= ((NU8)(122)));		LA43_: ;
		if (!T42_) goto LA44_;

#line 413 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		nimln_(413, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");		if ((NU)(i) >= (NU)s.len){ raiseIndexError2(i,s.len-1); goto LA1_;}		result.typ = s.p->data[i];
#line 414 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		nimln_(414, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");		if (nimAddInt(i, ((NI) 1), &TM__qDXzsifTQdn8ucTam9cFp4w_15)) { raiseOverflow(); goto LA1_;};		i = (NI)(TM__qDXzsifTQdn8ucTam9cFp4w_15);	}
	LA44_: ;

#line 415 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
	nimln_(415, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");	result.endPosition = i;
#line 416 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
	nimln_(416, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");	{		NIM_BOOL T48_;		tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw* T52_;		NimStringV2 T53_;		tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA T54_;		NimStringV2 T55_;
#line 416 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		T48_ = (NIM_BOOL)0;
#line 416 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"

#line 416 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"

#line 416 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		T48_ = !((i == s.len));		if (!(T48_)) goto LA49_;

#line 416 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		T48_ = !(ignoreUnknownSuffix);		LA49_: ;
		if (!T48_) goto LA50_;
		T52_ = (tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw*)0;		T52_ = (tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw*) nimNewObj(sizeof(tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw));		(*T52_).Sup.Sup.Sup.m_type = (&NTI__yoNlBGx0D2tRizIdhQuENw_);		(*T52_).Sup.Sup.name = "ValueError";
#line 418 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		nimln_(418, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");		T53_.len = 0; T53_.p = NIM_NIL;
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
		nimln_(49, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");
#line 418 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		nimln_(418, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");
#line 418 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"

#line 418 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		T54_ = dotdot___xNR8BVBMWzS9bXXNMikmyLgsystem(i, ((NI) 1));
#line 418 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		T55_.len = 0; T55_.p = NIM_NIL;		T55_ = X5BX5D___ogYTOKbgqbjPfyC123US1gsystem(s, T54_);
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
		nimln_(49, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");		eqsink___aBBXmHFBEivKqERloP6zmA((&colontmpD_), T55_);
		T53_ = rawNewString(colontmpD_.len + 37);appendString((&T53_), TM__qDXzsifTQdn8ucTam9cFp4w_17);appendString((&T53_), colontmpD_);		(*T52_).Sup.Sup.message = T53_;		(*T52_).Sup.Sup.parent = NIM_NIL;
#line 417 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		nimln_(417, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");		raiseExceptionEx((Exception*)T52_, "ValueError", "parseStandardFormatSpecifier", "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim", 417);		goto LA1_;	}
	LA50_: ;
	{		LA1_:;	}
	{
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
		nimln_(49, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
		eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&colontmpD_));
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}BeforeRet_: ;
	popFrame();	return result;}

#line 86 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/strs_v2.nim"
static N_INLINE(void, appendChar)(NimStringV2* dest, NIM_CHAR c) {	NI TM__qDXzsifTQdn8ucTam9cFp4w_27;	NI TM__qDXzsifTQdn8ucTam9cFp4w_28;{
#line 87 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/strs_v2.nim"
	(*(*dest).p).data[(*dest).len] = c;
#line 88 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/strs_v2.nim"
	if (nimAddInt((*dest).len, ((NI) 1), &TM__qDXzsifTQdn8ucTam9cFp4w_27)) { raiseOverflow(); goto BeforeRet_;};
#line 88 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/strs_v2.nim"
	(*(*dest).p).data[(NI)(TM__qDXzsifTQdn8ucTam9cFp4w_27)] = 0;
#line 89 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/strs_v2.nim"
	if (nimAddInt((*dest).len, ((NI) 1), &TM__qDXzsifTQdn8ucTam9cFp4w_28)) { raiseOverflow(); goto BeforeRet_;};	(*dest).len = (NI)(TM__qDXzsifTQdn8ucTam9cFp4w_28);	}BeforeRet_: ;
}

#line 122 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
static N_INLINE(NIM_BOOL, nimDivInt)(NI a, NI b, NI* res) {	NIM_BOOL result;	result = (NIM_BOOL)0;
#line 117 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
	{		NIM_BOOL T3_;
#line 117 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
		T3_ = (NIM_BOOL)0;
#line 117 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
		T3_ = (a == ((NI) (IL64(-9223372036854775807) - IL64(1))));		if (!(T3_)) goto LA4_;

#line 117 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
		T3_ = (b == ((NI) -1));		LA4_: ;
		if (!T3_) goto LA5_;

#line 118 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
		result = NIM_TRUE;	}
	goto LA1_;
	LA5_: ;
	{
#line 120 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"

#line 120 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
		(*res) = (NI)(a / b);	}
	LA1_: ;
	return result;}

#line 276 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
N_LIB_PRIVATE N_NIMCALL(NimStringV2, alignString__pfisktkC9crnJPz5c4ILtRg)(NimStringV2 s, NI minimumWidth, NIM_CHAR align, NIM_CHAR fill) {	NimStringV2 result;	NimStringV2 colontmpD_;	NimStringV2 colontmpD__2;	NimStringV2 colontmpD__3;	NimStringV2 colontmpD__4;NIM_BOOL* nimErr_;	nimfr_("alignString", "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");{nimErr_ = nimErrorFlag();	result.len = 0; result.p = NIM_NIL;	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;	colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;	colontmpD__3.len = 0; colontmpD__3.p = NIM_NIL;	colontmpD__4.len = 0; colontmpD__4.p = NIM_NIL;
#line 281 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
	nimln_(281, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");	{
#line 281 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		if (!(minimumWidth == ((NI) 0))) goto LA4_;

#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
		nimln_(49, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
		eq___aBBXmHFBEivKqERloP6zmA_2((&result), s);
	}
	goto LA2_;
	LA4_: ;
	{		NI sRuneLen;		NI toFill;		NI TM__qDXzsifTQdn8ucTam9cFp4w_29;
#line 284 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		nimln_(284, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");
#line 284 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		{			NI T9_;
#line 284 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"

#line 284 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"

#line 284 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
			T9_ = (NI)0;			T9_ = validateUtf8__gZHDHaRdP4jROav7Hun29aA(s);			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;			if (!(T9_ == ((NI) -1))) goto LA10_;

#line 284 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"

#line 284 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
			sRuneLen = nucruneLen(s);			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;		}
		goto LA7_;
		LA10_: ;
		{
#line 284 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
			sRuneLen = s.len;		}
		LA7_: ;

#line 285 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		nimln_(285, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");
#line 285 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		if (nimSubInt(minimumWidth, sRuneLen, &TM__qDXzsifTQdn8ucTam9cFp4w_29)) { raiseOverflow(); goto LA1_;};		toFill = (NI)(TM__qDXzsifTQdn8ucTam9cFp4w_29);
#line 286 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		nimln_(286, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");		{
#line 286 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
			if (!(toFill <= ((NI) 0))) goto LA15_;

#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
			nimln_(49, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
			eq___aBBXmHFBEivKqERloP6zmA_2((&result), s);
		}
		goto LA13_;
		LA15_: ;
		{			NIM_BOOL T18_;			NimStringV2 T22_;			NimStringV2 T23_;
#line 288 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
			nimln_(288, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");			T18_ = (NIM_BOOL)0;
#line 288 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
			T18_ = ((NU8)(align) == (NU8)(60));			if (T18_) goto LA19_;

#line 288 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
			T18_ = ((NU8)(align) == (NU8)(0));			LA19_: ;
			if (!T18_) goto LA20_;

#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
			nimln_(49, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");
#line 289 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
			nimln_(289, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");			T22_.len = 0; T22_.p = NIM_NIL;
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
			nimln_(49, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");
#line 289 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
			nimln_(289, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");			if ((toFill) < ((NI) 0) || (toFill) > ((NI) IL64(9223372036854775807))){ raiseRangeErrorI(toFill, ((NI) 0), ((NI) IL64(9223372036854775807))); goto LA1_;}
#line 289 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
			T23_.len = 0; T23_.p = NIM_NIL;			T23_ = nsuRepeatChar(fill, ((NI) (toFill)));			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
			nimln_(49, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");			eqsink___aBBXmHFBEivKqERloP6zmA((&colontmpD_), T23_);
			T22_ = rawNewString(s.len + colontmpD_.len + 0);appendString((&T22_), s);appendString((&T22_), colontmpD_);
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
			eqsink___aBBXmHFBEivKqERloP6zmA((&result), T22_);
		}
		goto LA13_;
		LA20_: ;
		{			NI half;			NI TM__qDXzsifTQdn8ucTam9cFp4w_30;			NimStringV2 T27_;			NimStringV2 T28_;			NI TM__qDXzsifTQdn8ucTam9cFp4w_31;			NimStringV2 T29_;
#line 290 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
			nimln_(290, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");			if (!((NU8)(align) == (NU8)(94))) goto LA25_;

#line 291 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
			nimln_(291, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");
#line 291 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
			if (((NI) 2) == 0){ raiseDivByZero(); goto LA1_;}			if (nimDivInt(toFill, ((NI) 2), &TM__qDXzsifTQdn8ucTam9cFp4w_30)) { raiseOverflow(); goto LA1_;};			half = (NI)(TM__qDXzsifTQdn8ucTam9cFp4w_30);
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
			nimln_(49, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");
#line 292 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
			nimln_(292, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");			T27_.len = 0; T27_.p = NIM_NIL;
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
			nimln_(49, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");
#line 292 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
			nimln_(292, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");			if ((half) < ((NI) 0) || (half) > ((NI) IL64(9223372036854775807))){ raiseRangeErrorI(half, ((NI) 0), ((NI) IL64(9223372036854775807))); goto LA1_;}
#line 292 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
			T28_.len = 0; T28_.p = NIM_NIL;			T28_ = nsuRepeatChar(fill, ((NI) (half)));			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
			nimln_(49, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");			eqsink___aBBXmHFBEivKqERloP6zmA((&colontmpD__2), T28_);

#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"

#line 292 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
			nimln_(292, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");
#line 292 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
			if (nimSubInt(toFill, half, &TM__qDXzsifTQdn8ucTam9cFp4w_31)) { raiseOverflow(); goto LA1_;};			if (((NI)(TM__qDXzsifTQdn8ucTam9cFp4w_31)) < ((NI) 0) || ((NI)(TM__qDXzsifTQdn8ucTam9cFp4w_31)) > ((NI) IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__qDXzsifTQdn8ucTam9cFp4w_31), ((NI) 0), ((NI) IL64(9223372036854775807))); goto LA1_;}
#line 292 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
			T29_.len = 0; T29_.p = NIM_NIL;			T29_ = nsuRepeatChar(fill, ((NI) ((NI)(TM__qDXzsifTQdn8ucTam9cFp4w_31))));			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
			nimln_(49, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");			eqsink___aBBXmHFBEivKqERloP6zmA((&colontmpD__3), T29_);
			T27_ = rawNewString(colontmpD__2.len + s.len + colontmpD__3.len + 0);appendString((&T27_), colontmpD__2);appendString((&T27_), s);appendString((&T27_), colontmpD__3);
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
			eqsink___aBBXmHFBEivKqERloP6zmA((&result), T27_);
		}
		goto LA13_;
		LA25_: ;
		{			NimStringV2 T31_;			NimStringV2 T32_;
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"

#line 294 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
			nimln_(294, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");			T31_.len = 0; T31_.p = NIM_NIL;
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
			nimln_(49, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");
#line 294 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
			nimln_(294, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");			if ((toFill) < ((NI) 0) || (toFill) > ((NI) IL64(9223372036854775807))){ raiseRangeErrorI(toFill, ((NI) 0), ((NI) IL64(9223372036854775807))); goto LA1_;}
#line 294 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
			T32_.len = 0; T32_.p = NIM_NIL;			T32_ = nsuRepeatChar(fill, ((NI) (toFill)));			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
			nimln_(49, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");			eqsink___aBBXmHFBEivKqERloP6zmA((&colontmpD__4), T32_);
			T31_ = rawNewString(colontmpD__4.len + s.len + 0);appendString((&T31_), colontmpD__4);appendString((&T31_), s);
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
			eqsink___aBBXmHFBEivKqERloP6zmA((&result), T31_);
		}
		LA13_: ;
	}
	LA2_: ;
	{		LA1_:;	}
	{
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"

#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
		eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&colontmpD__4));

#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"

#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
		eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&colontmpD__3));

#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"

#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
		eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&colontmpD__2));

#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"

#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
		eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&colontmpD_));
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}BeforeRet_: ;
	popFrame();	return result;}

#line 498 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
N_LIB_PRIVATE N_NIMCALL(void, formatValue__3zjq9csYPBcIN7AqvyU5ZLA)(NimStringV2* result, NimStringV2 value, NimStringV2 specifier) {	NimStringV2 value_2;	NimStringV2 colontmpD_;	tyObject_StandardFormatSpecifier__NDU7AW5Eu6Q69c8cH6RDouQ spec;	NimStringV2 T16_;NIM_BOOL* nimErr_;	nimfr_("formatValue", "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");{nimErr_ = nimErrorFlag();	value_2.len = 0; value_2.p = NIM_NIL;	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
#line 502 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
	nimln_(502, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");
#line 502 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
	spec = parseStandardFormatSpecifier__VVCKI4fK6GYPxQ9cDpjISyA(specifier, ((NI) 0), NIM_FALSE);	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
	nimln_(49, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
	eq___aBBXmHFBEivKqERloP6zmA_2((&value_2), value);

#line 504 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
	nimln_(504, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");	switch (((NU8)(spec.typ))) {
	case 115:
	case 0:
	{	}
	break;
	default:
	{		tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw* T4_;		NimStringV2 T5_;		T4_ = (tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw*)0;		T4_ = (tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw*) nimNewObj(sizeof(tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw));		(*T4_).Sup.Sup.Sup.m_type = (&NTI__yoNlBGx0D2tRizIdhQuENw_);		(*T4_).Sup.Sup.name = "ValueError";
#line 508 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		nimln_(508, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");		T5_.len = 0; T5_.p = NIM_NIL;		T5_ = rawNewString(65);appendString((&T5_), TM__qDXzsifTQdn8ucTam9cFp4w_26);appendChar((&T5_), spec.typ);		(*T4_).Sup.Sup.message = T5_;		(*T4_).Sup.Sup.parent = NIM_NIL;
#line 507 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		nimln_(507, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");		raiseExceptionEx((Exception*)T4_, "ValueError", "formatValue", "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim", 507);		goto LA1_;	}
	break;
	}

#line 510 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
	nimln_(510, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");	{
#line 510 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"

#line 510 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		if (!!((spec.precision == ((NI) -1)))) goto LA8_;

#line 511 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		nimln_(511, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");		{			NI T12_;			NI T15_;
#line 511 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"

#line 511 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"

#line 511 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
			T12_ = (NI)0;			T12_ = nucruneLen(value_2);			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;			if (!(spec.precision < T12_)) goto LA13_;

#line 512 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
			nimln_(512, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");
#line 512 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
			if ((spec.precision) < ((NI) 0) || (spec.precision) > ((NI) IL64(9223372036854775807))){ raiseRangeErrorI(spec.precision, ((NI) 0), ((NI) IL64(9223372036854775807))); goto LA1_;}
#line 512 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
			T15_ = (NI)0;			T15_ = runeOffset__EnrqtYM0boqQqeAIRc9bdmA(value_2, ((NI) (spec.precision)), ((NI) 0));			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;			if ((T15_) < ((NI) 0) || (T15_) > ((NI) IL64(9223372036854775807))){ raiseRangeErrorI(T15_, ((NI) 0), ((NI) IL64(9223372036854775807))); goto LA1_;}			setLengthStrV2((&value_2), ((NI) (T15_)));		}
		LA13_: ;
	}
	LA8_: ;

#line 513 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
	nimln_(513, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
	nimln_(49, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");
#line 513 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
	nimln_(513, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");
#line 513 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
	T16_.len = 0; T16_.p = NIM_NIL;	T16_ = alignString__pfisktkC9crnJPz5c4ILtRg(value_2, spec.minimumWidth, spec.align, spec.fill);	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
	nimln_(49, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");	eqsink___aBBXmHFBEivKqERloP6zmA((&colontmpD_), T16_);
	prepareAdd((&(*result)), colontmpD_.len + 0);appendString((&(*result)), colontmpD_);	{		LA1_:;	}
	{
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"

#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
		eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&colontmpD_));

#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"

#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
		eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&value_2));
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}BeforeRet_: ;
	popFrame();}

#line 123 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
static N_INLINE(NIM_BOOL, nimDivInt64)(NI64 a, NI64 b, NI64* res) {	NIM_BOOL result;	result = (NIM_BOOL)0;
#line 117 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
	{		NIM_BOOL T3_;
#line 117 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
		T3_ = (NIM_BOOL)0;
#line 117 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
		T3_ = (a == (IL64(-9223372036854775807) - IL64(1)));		if (!(T3_)) goto LA4_;

#line 117 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
		T3_ = (b == IL64(-1));		LA4_: ;
		if (!T3_) goto LA5_;

#line 118 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
		result = NIM_TRUE;	}
	goto LA1_;
	LA5_: ;
	{
#line 120 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"

#line 120 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
		(*res) = (NI64)(a / b);	}
	LA1_: ;
	return result;}

#line 269 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
static N_INLINE(NimStringV2, mkDigit__MPiQ66k9cc3im5NcFk1Mg9cwstrformat)(NI v, NIM_CHAR typ) {	NimStringV2 result;NIM_BOOL* nimErr_;	nimfr_("mkDigit", "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");{nimErr_ = nimErrorFlag();	result.len = 0; result.p = NIM_NIL;
#line 270 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
	nimln_(270, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");	{
#line 270 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"

#line 270 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		if (!!((v < ((NI) 26)))) goto LA3_;

#line 270 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"

#line 270 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		failedAssertImpl__W9cjVocn1tjhW7p7xohJj6A(TM__qDXzsifTQdn8ucTam9cFp4w_50);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}
	LA3_: ;

#line 271 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
	nimln_(271, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");	{		NI TM__qDXzsifTQdn8ucTam9cFp4w_51;
#line 271 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		if (!(v < ((NI) 10))) goto LA7_;

#line 272 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		nimln_(272, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");
#line 272 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"

#line 272 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"

#line 272 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		if (nimAddInt(((NI) 48), v, &TM__qDXzsifTQdn8ucTam9cFp4w_51)) { raiseOverflow(); goto BeforeRet_;};		if (((NI)(TM__qDXzsifTQdn8ucTam9cFp4w_51)) < ((NI) 0) || ((NI)(TM__qDXzsifTQdn8ucTam9cFp4w_51)) > ((NI) 255)){ raiseRangeErrorI((NI)(TM__qDXzsifTQdn8ucTam9cFp4w_51), ((NI) 0), ((NI) 255)); goto BeforeRet_;}		result = nimCharToStr(((NIM_CHAR) (((NI) ((NI)(TM__qDXzsifTQdn8ucTam9cFp4w_51))))));	}
	goto LA5_;
	LA7_: ;
	{		NIM_CHAR T10_;		NI TM__qDXzsifTQdn8ucTam9cFp4w_52;		NI TM__qDXzsifTQdn8ucTam9cFp4w_53;		NimStringV2 T16_;
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
		nimln_(49, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");
#line 274 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		nimln_(274, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");
#line 274 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"

#line 274 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"

#line 274 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"

#line 274 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		T10_ = (NIM_CHAR)0;
#line 274 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		{
#line 274 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
			if (!((NU8)(typ) == (NU8)(120))) goto LA13_;
			T10_ = 97;		}
		goto LA11_;
		LA13_: ;
		{			T10_ = 65;		}
		LA11_: ;
		if (nimAddInt(((NU8)(T10_)), v, &TM__qDXzsifTQdn8ucTam9cFp4w_52)) { raiseOverflow(); goto BeforeRet_;};		if (nimSubInt((NI)(TM__qDXzsifTQdn8ucTam9cFp4w_52), ((NI) 10), &TM__qDXzsifTQdn8ucTam9cFp4w_53)) { raiseOverflow(); goto BeforeRet_;};		if (((NI)(TM__qDXzsifTQdn8ucTam9cFp4w_53)) < ((NI) 0) || ((NI)(TM__qDXzsifTQdn8ucTam9cFp4w_53)) > ((NI) 255)){ raiseRangeErrorI((NI)(TM__qDXzsifTQdn8ucTam9cFp4w_53), ((NI) 0), ((NI) 255)); goto BeforeRet_;}		T16_.len = 0; T16_.p = NIM_NIL;		T16_ = nimCharToStr(((NIM_CHAR) (((NI) ((NI)(TM__qDXzsifTQdn8ucTam9cFp4w_53))))));
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
		nimln_(49, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");		eqsink___aBBXmHFBEivKqERloP6zmA((&result), T16_);
	}
	LA5_: ;
	}BeforeRet_: ;
	popFrame();	return result;}

#line 308 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
N_LIB_PRIVATE N_NIMCALL(NimStringV2, formatInt__mfFKm9aYkQ8qj8x65rdunAg)(NI n, NI radix, tyObject_StandardFormatSpecifier__NDU7AW5Eu6Q69c8cH6RDouQ* spec) {	NimStringV2 result;	NimStringV2 xx;	NimStringV2 colontmpD_;	NimStringV2 colontmpD__2;	NimStringV2 colontmpD__3;	NimStringV2 colontmpD__4;	NimStringV2 colontmpD__5;	NI64 v;	NIM_BOOL negative;NIM_BOOL* nimErr_;	nimfr_("formatInt", "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");{nimErr_ = nimErrorFlag();	result.len = 0; result.p = NIM_NIL;	xx.len = 0; xx.p = NIM_NIL;	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;	colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;	colontmpD__3.len = 0; colontmpD__3.p = NIM_NIL;	colontmpD__4.len = 0; colontmpD__4.p = NIM_NIL;	colontmpD__5.len = 0; colontmpD__5.p = NIM_NIL;
#line 318 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
	nimln_(318, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");	v = ((NI64) (n));
#line 319 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
	nimln_(319, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");
#line 319 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
	negative = (v < IL64(0));
#line 320 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
	nimln_(320, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");	{		NI64 TM__qDXzsifTQdn8ucTam9cFp4w_34;		if (!negative) goto LA4_;

#line 322 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		nimln_(322, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");
#line 322 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		if (nimMulInt64(v, IL64(-1), &TM__qDXzsifTQdn8ucTam9cFp4w_34)) { raiseOverflow(); goto LA1_;};		v = (NI64)(TM__qDXzsifTQdn8ucTam9cFp4w_34);	}
	LA4_: ;

#line 324 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
	nimln_(324, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");	xx = TM__qDXzsifTQdn8ucTam9cFp4w_36;
#line 325 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
	nimln_(325, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");	{		if (!(*spec).alternateForm) goto LA8_;

#line 326 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		nimln_(326, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");		switch (((NU8)((*spec).typ))) {
		case 88:
		{
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
			nimln_(49, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
			eqsink___aBBXmHFBEivKqERloP6zmA((&xx), TM__qDXzsifTQdn8ucTam9cFp4w_38);
		}
		break;
		case 120:
		{
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"

#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
			eqsink___aBBXmHFBEivKqERloP6zmA((&xx), TM__qDXzsifTQdn8ucTam9cFp4w_39);
		}
		break;
		case 98:
		{
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"

#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
			eqsink___aBBXmHFBEivKqERloP6zmA((&xx), TM__qDXzsifTQdn8ucTam9cFp4w_41);
		}
		break;
		case 111:
		{
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"

#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
			eqsink___aBBXmHFBEivKqERloP6zmA((&xx), TM__qDXzsifTQdn8ucTam9cFp4w_43);
		}
		break;
		default:
		{		}
		break;
		}
	}
	LA8_: ;

#line 333 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
	nimln_(333, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");	{
#line 333 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		if (!(v == IL64(0))) goto LA17_;

#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
		nimln_(49, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
		eqsink___aBBXmHFBEivKqERloP6zmA((&result), TM__qDXzsifTQdn8ucTam9cFp4w_45);
	}
	goto LA15_;
	LA17_: ;
	{
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"

#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
		eqsink___aBBXmHFBEivKqERloP6zmA((&result), TM__qDXzsifTQdn8ucTam9cFp4w_46);
		{
#line 337 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
			nimln_(337, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");			while (1) {				NI64 d;				NI64 TM__qDXzsifTQdn8ucTam9cFp4w_47;				NI64 TM__qDXzsifTQdn8ucTam9cFp4w_48;				NimStringV2 T22_;
#line 337 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
				if (!(IL64(0) < v)) goto LA21;

#line 338 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
				nimln_(338, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");
#line 338 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
				if (((NI64) (radix)) == 0){ raiseDivByZero(); goto LA1_;}				if (nimModInt64(v, ((NI64) (radix)), &TM__qDXzsifTQdn8ucTam9cFp4w_47)) { raiseOverflow(); goto LA1_;};				d = (NI64)(TM__qDXzsifTQdn8ucTam9cFp4w_47);
#line 339 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
				nimln_(339, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");
#line 339 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
				if (((NI64) (radix)) == 0){ raiseDivByZero(); goto LA1_;}				if (nimDivInt64(v, ((NI64) (radix)), &TM__qDXzsifTQdn8ucTam9cFp4w_48)) { raiseOverflow(); goto LA1_;};				v = (NI64)(TM__qDXzsifTQdn8ucTam9cFp4w_48);
#line 340 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
				nimln_(340, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
				nimln_(49, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");
#line 340 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
				nimln_(340, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");
#line 340 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
				T22_.len = 0; T22_.p = NIM_NIL;				T22_ = mkDigit__MPiQ66k9cc3im5NcFk1Mg9cwstrformat(((NI) (d)), (*spec).typ);				if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
				nimln_(49, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");				eqsink___aBBXmHFBEivKqERloP6zmA((&colontmpD_), T22_);
				prepareAdd((&result), colontmpD_.len + 0);appendString((&result), colontmpD_);			} LA21: ;
		}
		{			NI idx;			NI colontmp_;			NI TM__qDXzsifTQdn8ucTam9cFp4w_54;			NI i;			idx = (NI)0;			colontmp_ = (NI)0;
#line 341 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
			nimln_(341, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");
#line 341 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"

#line 341 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
			if (((NI) 2) == 0){ raiseDivByZero(); goto LA1_;}			if (nimDivInt(result.len, ((NI) 2), &TM__qDXzsifTQdn8ucTam9cFp4w_54)) { raiseOverflow(); goto LA1_;};			colontmp_ = (NI)(TM__qDXzsifTQdn8ucTam9cFp4w_54);
#line 106 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators_1.nim"
			nimln_(106, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators_1"
".nim");			i = ((NI) 0);			{
#line 107 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators_1.nim"
				nimln_(107, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators_1"
".nim");				while (1) {					NIM_CHAR T26_;					NI TM__qDXzsifTQdn8ucTam9cFp4w_55;					NI TM__qDXzsifTQdn8ucTam9cFp4w_56;					NI TM__qDXzsifTQdn8ucTam9cFp4w_57;
#line 107 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators_1.nim"
					if (!(i < colontmp_)) goto LA25;

#line 341 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
					nimln_(341, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");					idx = i;
#line 342 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
					nimln_(342, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");					T26_ = (NIM_CHAR)0;					if ((NU)(idx) >= (NU)result.len){ raiseIndexError2(idx,result.len-1); goto LA1_;}
#line 342 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"

#line 342 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"

#line 342 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
					if (nimSubInt(result.len, idx, &TM__qDXzsifTQdn8ucTam9cFp4w_55)) { raiseOverflow(); goto LA1_;};					if (nimSubInt((NI)(TM__qDXzsifTQdn8ucTam9cFp4w_55), ((NI) 1), &TM__qDXzsifTQdn8ucTam9cFp4w_56)) { raiseOverflow(); goto LA1_;};					if ((NU)((NI)(TM__qDXzsifTQdn8ucTam9cFp4w_56)) >= (NU)result.len){ raiseIndexError2((NI)(TM__qDXzsifTQdn8ucTam9cFp4w_56),result.len-1); goto LA1_;}					T26_ = result.p->data[idx];					result.p->data[idx] = result.p->data[(NI)(TM__qDXzsifTQdn8ucTam9cFp4w_56)];					result.p->data[(NI)(TM__qDXzsifTQdn8ucTam9cFp4w_56)] = T26_;
#line 109 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators_1.nim"
					nimln_(109, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators_1"
".nim");					if (nimAddInt(i, ((NI) 1), &TM__qDXzsifTQdn8ucTam9cFp4w_57)) { raiseOverflow(); goto LA1_;};					i = (NI)(TM__qDXzsifTQdn8ucTam9cFp4w_57);				} LA25: ;
			}
		}
	}
	LA15_: ;

#line 343 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
	nimln_(343, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");	{		NIM_BOOL sign;		NIM_BOOL T31_;		NI toFill;		NI TM__qDXzsifTQdn8ucTam9cFp4w_58;		NI TM__qDXzsifTQdn8ucTam9cFp4w_59;		NI TM__qDXzsifTQdn8ucTam9cFp4w_60;		if (!(*spec).padWithZero) goto LA29_;

#line 344 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		nimln_(344, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");
#line 344 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		T31_ = (NIM_BOOL)0;		T31_ = negative;		if (T31_) goto LA32_;

#line 344 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"

#line 344 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		T31_ = !(((NU8)((*spec).sign) == (NU8)(45)));		LA32_: ;
		sign = T31_;
#line 345 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		nimln_(345, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");
#line 345 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"

#line 345 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"

#line 345 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"

#line 345 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		if (nimSubInt((*spec).minimumWidth, result.len, &TM__qDXzsifTQdn8ucTam9cFp4w_58)) { raiseOverflow(); goto LA1_;};
#line 345 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		if (nimSubInt((NI)(TM__qDXzsifTQdn8ucTam9cFp4w_58), xx.len, &TM__qDXzsifTQdn8ucTam9cFp4w_59)) { raiseOverflow(); goto LA1_;};
#line 345 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		if (nimSubInt((NI)(TM__qDXzsifTQdn8ucTam9cFp4w_59), sign, &TM__qDXzsifTQdn8ucTam9cFp4w_60)) { raiseOverflow(); goto LA1_;};		toFill = (NI)(TM__qDXzsifTQdn8ucTam9cFp4w_60);
#line 346 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		nimln_(346, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");		{			NimStringV2 T37_;			NimStringV2 T38_;
#line 346 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
			if (!(((NI) 0) < toFill)) goto LA35_;

#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
			nimln_(49, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");
#line 347 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
			nimln_(347, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");			T37_.len = 0; T37_.p = NIM_NIL;
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
			nimln_(49, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");
#line 347 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
			nimln_(347, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");			if ((toFill) < ((NI) 0) || (toFill) > ((NI) IL64(9223372036854775807))){ raiseRangeErrorI(toFill, ((NI) 0), ((NI) IL64(9223372036854775807))); goto LA1_;}
#line 347 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
			T38_.len = 0; T38_.p = NIM_NIL;			T38_ = nsuRepeatChar(48, ((NI) (toFill)));			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
			nimln_(49, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");			eqsink___aBBXmHFBEivKqERloP6zmA((&colontmpD__2), T38_);
			T37_ = rawNewString(colontmpD__2.len + result.len + 0);appendString((&T37_), colontmpD__2);appendString((&T37_), result);
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
			eqsink___aBBXmHFBEivKqERloP6zmA((&result), T37_);
		}
		LA35_: ;
	}
	LA29_: ;

#line 349 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
	nimln_(349, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");	{		NimStringV2 T43_;		if (!negative) goto LA41_;

#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
		nimln_(49, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");
#line 350 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		nimln_(350, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");		T43_.len = 0; T43_.p = NIM_NIL;		T43_ = rawNewString(xx.len + result.len + 1);appendString((&T43_), TM__qDXzsifTQdn8ucTam9cFp4w_62);appendString((&T43_), xx);appendString((&T43_), result);
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
		nimln_(49, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");		eqsink___aBBXmHFBEivKqERloP6zmA((&result), T43_);
	}
	goto LA39_;
	LA41_: ;
	{		NimStringV2 T47_;
#line 351 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		nimln_(351, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");
#line 351 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		if (!!(((NU8)((*spec).sign) == (NU8)(45)))) goto LA45_;

#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
		nimln_(49, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");
#line 352 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		nimln_(352, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");		T47_.len = 0; T47_.p = NIM_NIL;		T47_ = rawNewString(xx.len + result.len + 1);appendChar((&T47_), (*spec).sign);appendString((&T47_), xx);appendString((&T47_), result);
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
		nimln_(49, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");		eqsink___aBBXmHFBEivKqERloP6zmA((&result), T47_);
	}
	goto LA39_;
	LA45_: ;
	{		NimStringV2 T49_;
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"

#line 354 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		nimln_(354, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");		T49_.len = 0; T49_.p = NIM_NIL;		T49_ = rawNewString(xx.len + result.len + 0);appendString((&T49_), xx);appendString((&T49_), result);
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
		nimln_(49, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");		eqsink___aBBXmHFBEivKqERloP6zmA((&result), T49_);
	}
	LA39_: ;

#line 356 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
	nimln_(356, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");	{
#line 356 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		if (!((NU8)((*spec).align) == (NU8)(60))) goto LA52_;
		{			NI i_2;			NI colontmp__2;			NI i_3;			i_2 = (NI)0;			colontmp__2 = (NI)0;
#line 357 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
			nimln_(357, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");
#line 357 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
			colontmp__2 = result.len;
#line 106 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators_1.nim"
			nimln_(106, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators_1"
".nim");			i_3 = colontmp__2;			{
#line 107 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators_1.nim"
				nimln_(107, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators_1"
".nim");				while (1) {					NI TM__qDXzsifTQdn8ucTam9cFp4w_63;
#line 107 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators_1.nim"
					if (!(i_3 < (*spec).minimumWidth)) goto LA56;

#line 357 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
					nimln_(357, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");					i_2 = i_3;
#line 358 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
					nimln_(358, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");					nimAddCharV1((&result), (*spec).fill);
#line 109 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators_1.nim"
					nimln_(109, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators_1"
".nim");					if (nimAddInt(i_3, ((NI) 1), &TM__qDXzsifTQdn8ucTam9cFp4w_63)) { raiseOverflow(); goto LA1_;};					i_3 = (NI)(TM__qDXzsifTQdn8ucTam9cFp4w_63);				} LA56: ;
			}
		}
	}
	goto LA50_;
	LA52_: ;
	{		NI toFill_2;		NI TM__qDXzsifTQdn8ucTam9cFp4w_64;
#line 360 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		nimln_(360, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");
#line 360 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"

#line 360 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		if (nimSubInt((*spec).minimumWidth, result.len, &TM__qDXzsifTQdn8ucTam9cFp4w_64)) { raiseOverflow(); goto LA1_;};		toFill_2 = (NI)(TM__qDXzsifTQdn8ucTam9cFp4w_64);
#line 361 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		nimln_(361, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");		{			NI half;			NI TM__qDXzsifTQdn8ucTam9cFp4w_65;			NimStringV2 T62_;			NimStringV2 T63_;			NI TM__qDXzsifTQdn8ucTam9cFp4w_66;			NimStringV2 T64_;
#line 361 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
			if (!((NU8)((*spec).align) == (NU8)(94))) goto LA60_;

#line 362 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
			nimln_(362, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");
#line 362 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
			if (((NI) 2) == 0){ raiseDivByZero(); goto LA1_;}			if (nimDivInt(toFill_2, ((NI) 2), &TM__qDXzsifTQdn8ucTam9cFp4w_65)) { raiseOverflow(); goto LA1_;};			half = (NI)(TM__qDXzsifTQdn8ucTam9cFp4w_65);
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
			nimln_(49, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");
#line 363 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
			nimln_(363, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");			T62_.len = 0; T62_.p = NIM_NIL;
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
			nimln_(49, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");
#line 363 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
			nimln_(363, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");			if ((half) < ((NI) 0) || (half) > ((NI) IL64(9223372036854775807))){ raiseRangeErrorI(half, ((NI) 0), ((NI) IL64(9223372036854775807))); goto LA1_;}
#line 363 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
			T63_.len = 0; T63_.p = NIM_NIL;			T63_ = nsuRepeatChar((*spec).fill, ((NI) (half)));			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
			nimln_(49, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");			eqsink___aBBXmHFBEivKqERloP6zmA((&colontmpD__3), T63_);

#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"

#line 363 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
			nimln_(363, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");
#line 363 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
			if (nimSubInt(toFill_2, half, &TM__qDXzsifTQdn8ucTam9cFp4w_66)) { raiseOverflow(); goto LA1_;};			if (((NI)(TM__qDXzsifTQdn8ucTam9cFp4w_66)) < ((NI) 0) || ((NI)(TM__qDXzsifTQdn8ucTam9cFp4w_66)) > ((NI) IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__qDXzsifTQdn8ucTam9cFp4w_66), ((NI) 0), ((NI) IL64(9223372036854775807))); goto LA1_;}
#line 363 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
			T64_.len = 0; T64_.p = NIM_NIL;			T64_ = nsuRepeatChar((*spec).fill, ((NI) ((NI)(TM__qDXzsifTQdn8ucTam9cFp4w_66))));			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
			nimln_(49, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");			eqsink___aBBXmHFBEivKqERloP6zmA((&colontmpD__4), T64_);
			T62_ = rawNewString(colontmpD__3.len + result.len + colontmpD__4.len + 0);appendString((&T62_), colontmpD__3);appendString((&T62_), result);appendString((&T62_), colontmpD__4);
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
			eqsink___aBBXmHFBEivKqERloP6zmA((&result), T62_);
		}
		goto LA58_;
		LA60_: ;
		{
#line 365 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
			nimln_(365, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");			{				NimStringV2 T70_;				NimStringV2 T71_;
#line 365 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
				if (!(((NI) 0) < toFill_2)) goto LA68_;

#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
				nimln_(49, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");
#line 366 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
				nimln_(366, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");				T70_.len = 0; T70_.p = NIM_NIL;
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
				nimln_(49, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");
#line 366 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
				nimln_(366, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");				if ((toFill_2) < ((NI) 0) || (toFill_2) > ((NI) IL64(9223372036854775807))){ raiseRangeErrorI(toFill_2, ((NI) 0), ((NI) IL64(9223372036854775807))); goto LA1_;}
#line 366 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
				T71_.len = 0; T71_.p = NIM_NIL;				T71_ = nsuRepeatChar((*spec).fill, ((NI) (toFill_2)));				if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
				nimln_(49, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");				eqsink___aBBXmHFBEivKqERloP6zmA((&colontmpD__5), T71_);
				T70_ = rawNewString(colontmpD__5.len + result.len + 0);appendString((&T70_), colontmpD__5);appendString((&T70_), result);
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
				eqsink___aBBXmHFBEivKqERloP6zmA((&result), T70_);
			}
			LA68_: ;
		}
		LA58_: ;
	}
	LA50_: ;
	{		LA1_:;	}
	{
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"

#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
		eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&colontmpD__5));

#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"

#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
		eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&colontmpD__4));

#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"

#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
		eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&colontmpD__3));

#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"

#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
		eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&colontmpD__2));

#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"

#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
		eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&colontmpD_));

#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"

#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
		eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&xx));
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}BeforeRet_: ;
	popFrame();	return result;}

#line 420 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
N_LIB_PRIVATE N_NIMCALL(void, formatValue__ACNJL1q6Oxfvi53i9bkeK6Q)(NimStringV2* result, NI value, NimStringV2 specifier) {	NimStringV2 colontmpD_;	NimStringV2 colontmpD__2;	tyObject_StandardFormatSpecifier__NDU7AW5Eu6Q69c8cH6RDouQ spec;	NI radix;	NimStringV2 T14_;NIM_BOOL* nimErr_;	nimfr_("formatValue", "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");{nimErr_ = nimErrorFlag();	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;	colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
#line 425 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
	nimln_(425, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");	{		NimStringV2 T6_;
#line 425 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"

#line 425 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		if (!(specifier.len == ((NI) 0))) goto LA4_;

#line 426 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		nimln_(426, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
		nimln_(49, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");
#line 426 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		nimln_(426, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");		T6_.len = 0; T6_.p = NIM_NIL;		T6_ = nimIntToStr(value);
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
		nimln_(49, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");		eqsink___aBBXmHFBEivKqERloP6zmA((&colontmpD_), T6_);
		prepareAdd((&(*result)), colontmpD_.len + 0);appendString((&(*result)), colontmpD_);
#line 427 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		nimln_(427, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
		nimln_(49, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
		eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&colontmpD__2));

#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"

#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
		eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&colontmpD_));
		goto BeforeRet_;
	}
	LA4_: ;

#line 428 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
	nimln_(428, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");
#line 428 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
	spec = parseStandardFormatSpecifier__VVCKI4fK6GYPxQ9cDpjISyA(specifier, ((NI) 0), NIM_FALSE);	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
#line 429 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
	nimln_(429, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");	radix = ((NI) 10);
#line 430 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
	nimln_(430, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");	switch (((NU8)(spec.typ))) {
	case 120:
	case 88:
	{
#line 431 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		nimln_(431, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");		radix = ((NI) 16);	}
	break;
	case 100:
	case 0:
	{	}
	break;
	case 98:
	{
#line 433 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		nimln_(433, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");		radix = ((NI) 2);	}
	break;
	case 111:
	{
#line 434 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		nimln_(434, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");		radix = ((NI) 8);	}
	break;
	default:
	{		tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw* T12_;		NimStringV2 T13_;		T12_ = (tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw*)0;		T12_ = (tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw*) nimNewObj(sizeof(tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw));		(*T12_).Sup.Sup.Sup.m_type = (&NTI__yoNlBGx0D2tRizIdhQuENw_);		(*T12_).Sup.Sup.name = "ValueError";
#line 438 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		nimln_(438, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");		T13_.len = 0; T13_.p = NIM_NIL;		T13_ = rawNewString(93);appendString((&T13_), TM__qDXzsifTQdn8ucTam9cFp4w_33);appendChar((&T13_), spec.typ);		(*T12_).Sup.Sup.message = T13_;		(*T12_).Sup.Sup.parent = NIM_NIL;
#line 436 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
		nimln_(436, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");		raiseExceptionEx((Exception*)T12_, "ValueError", "formatValue", "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim", 436);		goto LA1_;	}
	break;
	}

#line 439 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
	nimln_(439, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
	nimln_(49, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");
#line 439 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
	nimln_(439, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim");
#line 439 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/strformat.nim"
	T14_.len = 0; T14_.p = NIM_NIL;	T14_ = formatInt__mfFKm9aYkQ8qj8x65rdunAg(value, radix, (&spec));	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
	nimln_(49, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");	eqsink___aBBXmHFBEivKqERloP6zmA((&colontmpD__2), T14_);
	prepareAdd((&(*result)), colontmpD__2.len + 0);appendString((&(*result)), colontmpD__2);	{		LA1_:;	}
	{
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"

#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
		eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&colontmpD__2));

#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"

#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
		eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&colontmpD_));
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}BeforeRet_: ;
	popFrame();}
