/* Generated by Nim Compiler v1.3.3 */
/*   (c) 2020 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w -g  -I/Users/elcritch/.asdf/installs/nim/devel/lib -I/Volumes/datastore/projects/pt/third-party/spryvm/tests -o /Volumes/datastore/projects/pt/third-party/spryvm/tests/_nimcache/stdlib_sets.nim.c.o /Volumes/datastore/projects/pt/third-party/spryvm/tests/_nimcache/stdlib_sets.nim.c */
#define NIM_INTBITS 64

/* section: NIM_merge_HEADERS */

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix

/* section: NIM_merge_FRAME_DEFINES */
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
  
/* section: NIM_merge_FORWARD_TYPES */
typedef struct tyObject_HashSet__CD8Dpv0WGmASelVaNSo6zg tyObject_HashSet__CD8Dpv0WGmASelVaNSo6zg;
typedef struct tySequence__4eRCaZmrYLLw2k30GPTiMw tySequence__4eRCaZmrYLLw2k30GPTiMw;
typedef struct tySequence__4eRCaZmrYLLw2k30GPTiMw_Content tySequence__4eRCaZmrYLLw2k30GPTiMw_Content;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyTuple__QeWl6B6ffS4pU6WWrtcrDw tyTuple__QeWl6B6ffS4pU6WWrtcrDw;

/* section: NIM_merge_TYPES */
struct tySequence__4eRCaZmrYLLw2k30GPTiMw {
  NI len; tySequence__4eRCaZmrYLLw2k30GPTiMw_Content* p;
};
struct tyObject_HashSet__CD8Dpv0WGmASelVaNSo6zg {tySequence__4eRCaZmrYLLw2k30GPTiMw data;
NI counter;
};
struct NimStrPayload {NI cap;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {NI len;
NimStrPayload* p;
};
struct tyTuple__QeWl6B6ffS4pU6WWrtcrDw {
NI Field0;
NimStringV2 Field1;
};


#ifndef tySequence__4eRCaZmrYLLw2k30GPTiMw_Content_PP
#define tySequence__4eRCaZmrYLLw2k30GPTiMw_Content_PP
struct tySequence__4eRCaZmrYLLw2k30GPTiMw_Content { NI cap; tyTuple__QeWl6B6ffS4pU6WWrtcrDw data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__4eRCaZmrYLLw2k30GPTiMw_Content_PP
#define tySequence__4eRCaZmrYLLw2k30GPTiMw_Content_PP
struct tySequence__4eRCaZmrYLLw2k30GPTiMw_Content { NI cap; tyTuple__QeWl6B6ffS4pU6WWrtcrDw data[SEQ_DECL_SIZE];};
#endif

      
/* section: NIM_merge_PROC_HEADERS */
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isPowerOfTwo__1xdTQapFveM9bImKot7h9cdw)(NI x);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__W9cjVocn1tjhW7p7xohJj6A)(NimStringV2 msg);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i, NI64 a, NI64 b);
N_LIB_PRIVATE N_NIMCALL(void*, newSeqPayload)(NI cap, NI elemSize, NI elemAlign);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(NI, rawGet__h9bD59bk9aSaP9ae9axJ475zaRgsets)(tyObject_HashSet__CD8Dpv0WGmASelVaNSo6zg t, NimStringV2 key, NI* hc);
N_LIB_PRIVATE N_NIMCALL(NI, hash__6PCYkKlCNhq9cnRLnqWKkwQ)(NimStringV2 x);
static N_INLINE(NIM_BOOL, isFilled__uHIMxs9aGYDEfZheaMnN2sQsets)(NI hcode);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i, NI n);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringV2 a, NimStringV2 b);
static N_INLINE(NIM_BOOL, equalMem__9bGgqEk7RXXl6eqM9c1HdELAsystem)(void* a, void* b, NI size);
static N_INLINE(int, nimCmpMem)(void* a, void* b, NI size);
static N_INLINE(NI, nextTry__YQqpuaZxbzuIDQ5oZ9bnvuQsets)(NI h, NI maxHash);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NIM_BOOL, mustRehash__9aQKy8l9bO9aHJHq2R79c0vEiAsets)(tyObject_HashSet__CD8Dpv0WGmASelVaNSo6zg t);
N_LIB_PRIVATE N_NIMCALL(void, enlarge__S48V0eiEuyCalh7won1YWQ)(tyObject_HashSet__CD8Dpv0WGmASelVaNSo6zg* s);
static N_INLINE(NI, rawGetKnownHC__H4n01hI4Y1dhJhVV44eECQsets)(tyObject_HashSet__CD8Dpv0WGmASelVaNSo6zg t, NimStringV2 key, NI hc);
N_LIB_PRIVATE N_NIMCALL(void, rawInsert__0WGPG59byJ2eMftxsrjD02A)(tyObject_HashSet__CD8Dpv0WGmASelVaNSo6zg* s, tySequence__4eRCaZmrYLLw2k30GPTiMw* data, NimStringV2 key, NI hc, NI h);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___aBBXmHFBEivKqERloP6zmA)(NimStringV2* dest, NimStringV2 src);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ)(NimStringV2* dest);
N_LIB_PRIVATE N_NIMCALL(void, eq___aBBXmHFBEivKqERloP6zmA_2)(NimStringV2* dest, NimStringV2 src);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___1GwzQah0ciEGiSvKbGJgpg)(tySequence__4eRCaZmrYLLw2k30GPTiMw* dest);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p);

/* section: NIM_merge_DATA */
static const struct {
  NI cap; NIM_CHAR data[110+1];
} TM__0JXiWyhP5OCO8jWMA6sb1w_2 = { 110 | NIM_STRLIT_FLAG, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/s"
"etimpl.nim(19, 10) `isPowerOfTwo(initialSize)` " };
static const NimStringV2 TM__0JXiWyhP5OCO8jWMA6sb1w_3 = {110, (NimStrPayload*)&TM__0JXiWyhP5OCO8jWMA6sb1w_2};
static const struct {
  NI cap; NIM_CHAR data[117+1];
} TM__0JXiWyhP5OCO8jWMA6sb1w_4 = { 117 | NIM_STRLIT_FLAG, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/s"
"etimpl.nim(19, 10) `isPowerOfTwo(defaultInitialSize)` " };
static const NimStringV2 TM__0JXiWyhP5OCO8jWMA6sb1w_5 = {117, (NimStrPayload*)&TM__0JXiWyhP5OCO8jWMA6sb1w_4};
static const struct {
  NI cap; NIM_CHAR data[109+1];
} TM__0JXiWyhP5OCO8jWMA6sb1w_8 = { 109 | NIM_STRLIT_FLAG, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/h"
"ashcommon.nim(33, 9) `\012t.counter < t.dataLen` " };
static const NimStringV2 TM__0JXiWyhP5OCO8jWMA6sb1w_9 = {109, (NimStrPayload*)&TM__0JXiWyhP5OCO8jWMA6sb1w_8};
static const NimStringV2 TM__0JXiWyhP5OCO8jWMA6sb1w_16 = {117, (NimStrPayload*)&TM__0JXiWyhP5OCO8jWMA6sb1w_4};

/* section: NIM_merge_VARS */
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_BOOL nimInErrorMode__759bT87luu8XGcbkw13FUjA;

/* section: NIM_merge_PROCS */

#line 541 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
static N_INLINE(void, nimFrame)(TFrame* s) {
#line 542 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	{
#line 542 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
		if (!(framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA3_;

#line 543 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
		(*s).calldepth = ((NI16) 0);	}
	goto LA1_;
	LA3_: ;
	{
#line 546 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"

#line 546 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
		(*s).calldepth = (NI16)((*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1));	}
	LA1_: ;

#line 548 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	(*s).prev = framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
#line 549 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = s;
#line 550 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	{
#line 550 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
		if (!((*s).calldepth == ((NI16) 2000))) goto LA8_;

#line 550 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"

#line 550 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
		callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw();
	}
	LA8_: ;
}

#line 85 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
static N_INLINE(void, popFrame)(void) {
#line 86 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).prev;}

#line 599 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/sets.nim"
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isValid__GDLNqyUzwpO9brvFlcTOY5Q)(tyObject_HashSet__CD8Dpv0WGmASelVaNSo6zg s) {	NIM_BOOL result;	NI T1_;	nimfr_("isValid", "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/s"
"ets.nim");	result = (NIM_BOOL)0;
#line 610 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/sets.nim"
	nimln_(610, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/s"
"ets.nim");
#line 610 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/sets.nim"

#line 610 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/sets.nim"
	T1_ = s.data.len;	result = (((NI) 0) < T1_);	popFrame();	return result;}

#line 424 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {	NIM_BOOL* result;	result = (NIM_BOOL*)0;
#line 425 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	result = (&nimInErrorMode__759bT87luu8XGcbkw13FUjA);	return result;}

#line 94 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/sets.nim"
N_LIB_PRIVATE N_NIMCALL(void, init__yuYJ6k5D1l1c5lO0bWkT5w)(tyObject_HashSet__CD8Dpv0WGmASelVaNSo6zg* s, NI initialSize) {NIM_BOOL* nimErr_;	nimfr_("init", "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/s"
"ets.nim");{nimErr_ = nimErrorFlag();
#line 19 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/setimpl.nim"
	nimln_(19, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/s"
"etimpl.nim");	{		NIM_BOOL T3_;
#line 19 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/setimpl.nim"

#line 19 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/setimpl.nim"

#line 19 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/setimpl.nim"
		T3_ = (NIM_BOOL)0;		T3_ = isPowerOfTwo__1xdTQapFveM9bImKot7h9cdw(initialSize);		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;		if (!!(T3_)) goto LA4_;

#line 19 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/setimpl.nim"

#line 19 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/setimpl.nim"
		failedAssertImpl__W9cjVocn1tjhW7p7xohJj6A(TM__0JXiWyhP5OCO8jWMA6sb1w_3);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}
	LA4_: ;

#line 23 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/setimpl.nim"
	nimln_(23, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/s"
"etimpl.nim");	(*s).counter = ((NI) 0);
#line 118 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/sets.nim"
	nimln_(118, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/s"
"ets.nim");	if ((initialSize) < ((NI) 0) || (initialSize) > ((NI) IL64(9223372036854775807))){ raiseRangeErrorI(initialSize, ((NI) 0), ((NI) IL64(9223372036854775807))); goto BeforeRet_;}	(*s).data.len = ((NI) (initialSize)); (*s).data.p = (tySequence__4eRCaZmrYLLw2k30GPTiMw_Content*) newSeqPayload(((NI) (initialSize)), sizeof(tyTuple__QeWl6B6ffS4pU6WWrtcrDw), NIM_ALIGNOF(tyTuple__QeWl6B6ffS4pU6WWrtcrDw));	}BeforeRet_: ;
	popFrame();}

#line 26 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/hashcommon.nim"
static N_INLINE(NIM_BOOL, isFilled__uHIMxs9aGYDEfZheaMnN2sQsets)(NI hcode) {	NIM_BOOL result;	nimfr_("isFilled", "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/h"
"ashcommon.nim");	result = (NIM_BOOL)0;
#line 27 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/hashcommon.nim"
	nimln_(27, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/h"
"ashcommon.nim");
#line 27 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/hashcommon.nim"

#line 27 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/hashcommon.nim"
	result = !((hcode == ((NI) 0)));	popFrame();	return result;}

#line 36 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/memory.nim"
static N_INLINE(int, nimCmpMem)(void* a, void* b, NI size) {	int result;	result = (int)0;
#line 38 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/memory.nim"

#line 38 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/memory.nim"
	result = memcmp(a, b, ((size_t) (size)));	return result;}

#line 2140 "/Users/elcritch/.asdf/installs/nim/devel/lib/system.nim"
static N_INLINE(NIM_BOOL, equalMem__9bGgqEk7RXXl6eqM9c1HdELAsystem)(void* a, void* b, NI size) {	NIM_BOOL result;	int T1_;	result = (NIM_BOOL)0;
#line 2141 "/Users/elcritch/.asdf/installs/nim/devel/lib/system.nim"

#line 2141 "/Users/elcritch/.asdf/installs/nim/devel/lib/system.nim"

#line 2141 "/Users/elcritch/.asdf/installs/nim/devel/lib/system.nim"

#line 2141 "/Users/elcritch/.asdf/installs/nim/devel/lib/system.nim"
	T1_ = (int)0;	T1_ = nimCmpMem(a, b, size);	result = (T1_ == ((NI32) 0));	return result;}

#line 23 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/strmantle.nim"
static N_INLINE(NIM_BOOL, eqStrings)(NimStringV2 a, NimStringV2 b) {	NIM_BOOL result;	NI alen;	NI blen;	nimfr_("eqStrings", "/Users/elcritch/.asdf/installs/nim/devel/lib/system/strmantle.n"
"im");{	result = (NIM_BOOL)0;
#line 24 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/strmantle.nim"
	nimln_(24, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/strmantle.n"
"im");
#line 24 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/strmantle.nim"
	alen = a.len;
#line 25 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/strmantle.nim"
	nimln_(25, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/strmantle.n"
"im");
#line 25 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/strmantle.nim"
	blen = b.len;
#line 26 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/strmantle.nim"
	nimln_(26, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/strmantle.n"
"im");	{
#line 26 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/strmantle.nim"
		if (!(alen == blen)) goto LA3_;

#line 27 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/strmantle.nim"
		nimln_(27, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/strmantle.n"
"im");		{
#line 27 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/strmantle.nim"
			if (!(alen == ((NI) 0))) goto LA7_;

#line 27 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/strmantle.nim"

#line 27 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/strmantle.nim"
			result = NIM_TRUE;			goto BeforeRet_;
		}
		LA7_: ;

#line 28 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/strmantle.nim"
		nimln_(28, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/strmantle.n"
"im");
#line 28 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/strmantle.nim"

#line 28 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/strmantle.nim"
		result = equalMem__9bGgqEk7RXXl6eqM9c1HdELAsystem(((void*) ((&a.p->data[((NI) 0)]))), ((void*) ((&b.p->data[((NI) 0)]))), ((NI) (alen)));		goto BeforeRet_;
	}
	LA3_: ;
	}BeforeRet_: ;
	popFrame();	return result;}

#line 29 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/hashcommon.nim"
static N_INLINE(NI, nextTry__YQqpuaZxbzuIDQ5oZ9bnvuQsets)(NI h, NI maxHash) {	NI result;	NI TM__0JXiWyhP5OCO8jWMA6sb1w_6;	nimfr_("nextTry", "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/h"
"ashcommon.nim");{	result = (NI)0;
#line 30 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/hashcommon.nim"
	nimln_(30, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/h"
"ashcommon.nim");
#line 30 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/hashcommon.nim"

#line 30 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/hashcommon.nim"
	if (nimAddInt(h, ((NI) 1), &TM__0JXiWyhP5OCO8jWMA6sb1w_6)) { raiseOverflow(); goto BeforeRet_;};	result = (NI)((NI)(TM__0JXiWyhP5OCO8jWMA6sb1w_6) & maxHash);	}BeforeRet_: ;
	popFrame();	return result;}

#line 76 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/hashcommon.nim"
static N_INLINE(NI, rawGet__h9bD59bk9aSaP9ae9axJ475zaRgsets)(tyObject_HashSet__CD8Dpv0WGmASelVaNSo6zg t, NimStringV2 key, NI* hc) {	NI result;	NI T1_;	NI h;	NI T11_;	NI TM__0JXiWyhP5OCO8jWMA6sb1w_7;NIM_BOOL* nimErr_;	nimfr_("rawGet", "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/h"
"ashcommon.nim");{nimErr_ = nimErrorFlag();	result = (NI)0;
#line 63 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/hashcommon.nim"
	nimln_(63, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/h"
"ashcommon.nim");
#line 63 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/hashcommon.nim"
	T1_ = (NI)0;	T1_ = hash__6PCYkKlCNhq9cnRLnqWKkwQ(key);	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	(*hc) = T1_;
#line 73 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/hashcommon.nim"
	nimln_(73, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/h"
"ashcommon.nim");	{
#line 64 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/hashcommon.nim"
		nimln_(64, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/h"
"ashcommon.nim");		if (!((*hc) == ((NI) 0))) goto LA4_;

#line 65 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/hashcommon.nim"
		nimln_(65, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/h"
"ashcommon.nim");		(*hc) = ((NI) 314159265);	}
	LA4_: ;

#line 46 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/hashcommon.nim"
	nimln_(46, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/h"
"ashcommon.nim");	{		NI T8_;
#line 46 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/hashcommon.nim"

#line 46 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/hashcommon.nim"
		T8_ = t.data.len;		if (!(T8_ == ((NI) 0))) goto LA9_;

#line 47 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/hashcommon.nim"
		nimln_(47, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/h"
"ashcommon.nim");
#line 47 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/hashcommon.nim"
		result = ((NI) -1);		goto BeforeRet_;
	}
	LA9_: ;

#line 48 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/hashcommon.nim"
	nimln_(48, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/h"
"ashcommon.nim");
#line 48 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/hashcommon.nim"

#line 48 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/hashcommon.nim"
	T11_ = (t.data.len-1);	h = (NI)((*hc) & T11_);	{
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/hashcommon.nim"
		nimln_(49, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/h"
"ashcommon.nim");		while (1) {			NIM_BOOL T14_;			NI T21_;
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/hashcommon.nim"
			if ((NU)(h) >= (NU)t.data.len){ raiseIndexError2(h,t.data.len-1); goto BeforeRet_;}
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/hashcommon.nim"
			T14_ = (NIM_BOOL)0;			T14_ = isFilled__uHIMxs9aGYDEfZheaMnN2sQsets(t.data.p->data[h].Field0);			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;			if (!T14_) goto LA13;

#line 54 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/hashcommon.nim"
			nimln_(54, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/h"
"ashcommon.nim");			{				NIM_BOOL T17_;
#line 54 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/hashcommon.nim"
				T17_ = (NIM_BOOL)0;
#line 54 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/hashcommon.nim"
				if ((NU)(h) >= (NU)t.data.len){ raiseIndexError2(h,t.data.len-1); goto BeforeRet_;}				T17_ = (t.data.p->data[h].Field0 == (*hc));				if (!(T17_)) goto LA18_;

#line 54 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/hashcommon.nim"
				if ((NU)(h) >= (NU)t.data.len){ raiseIndexError2(h,t.data.len-1); goto BeforeRet_;}				T17_ = eqStrings(t.data.p->data[h].Field1, key);				LA18_: ;
				if (!T17_) goto LA19_;

#line 55 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/hashcommon.nim"
				nimln_(55, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/h"
"ashcommon.nim");
#line 55 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/hashcommon.nim"
				result = h;				goto BeforeRet_;
			}
			LA19_: ;

#line 56 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/hashcommon.nim"
			nimln_(56, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/h"
"ashcommon.nim");
#line 56 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/hashcommon.nim"
			T21_ = (t.data.len-1);
#line 56 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/hashcommon.nim"
			h = nextTry__YQqpuaZxbzuIDQ5oZ9bnvuQsets(h, T21_);			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;		} LA13: ;
	}

#line 57 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/hashcommon.nim"
	nimln_(57, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/h"
"ashcommon.nim");
#line 57 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/hashcommon.nim"
	if (nimSubInt(((NI) -1), h, &TM__0JXiWyhP5OCO8jWMA6sb1w_7)) { raiseOverflow(); goto BeforeRet_;};	result = (NI)(TM__0JXiWyhP5OCO8jWMA6sb1w_7);	}BeforeRet_: ;
	popFrame();	return result;}

#line 32 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/hashcommon.nim"
static N_INLINE(NIM_BOOL, mustRehash__9aQKy8l9bO9aHJHq2R79c0vEiAsets)(tyObject_HashSet__CD8Dpv0WGmASelVaNSo6zg t) {	NIM_BOOL result;	NIM_BOOL T6_;	NI T7_;	NI TM__0JXiWyhP5OCO8jWMA6sb1w_10;	NI TM__0JXiWyhP5OCO8jWMA6sb1w_11;	NI T9_;	NI TM__0JXiWyhP5OCO8jWMA6sb1w_12;NIM_BOOL* nimErr_;	nimfr_("mustRehash", "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/h"
"ashcommon.nim");{nimErr_ = nimErrorFlag();	result = (NIM_BOOL)0;
#line 33 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/hashcommon.nim"
	nimln_(33, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/h"
"ashcommon.nim");	{		NI T3_;
#line 33 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/hashcommon.nim"

#line 33 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/hashcommon.nim"

#line 33 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/hashcommon.nim"
		T3_ = t.data.len;		if (!!((t.counter < T3_))) goto LA4_;

#line 33 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/hashcommon.nim"

#line 33 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/hashcommon.nim"
		failedAssertImpl__W9cjVocn1tjhW7p7xohJj6A(TM__0JXiWyhP5OCO8jWMA6sb1w_9);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}
	LA4_: ;

#line 34 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/hashcommon.nim"
	nimln_(34, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/h"
"ashcommon.nim");
#line 34 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/hashcommon.nim"
	T6_ = (NIM_BOOL)0;
#line 34 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/hashcommon.nim"

#line 34 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/hashcommon.nim"

#line 34 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/hashcommon.nim"
	T7_ = t.data.len;	if (nimMulInt(T7_, ((NI) 2), &TM__0JXiWyhP5OCO8jWMA6sb1w_10)) { raiseOverflow(); goto BeforeRet_;};
#line 34 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/hashcommon.nim"
	if (nimMulInt(t.counter, ((NI) 3), &TM__0JXiWyhP5OCO8jWMA6sb1w_11)) { raiseOverflow(); goto BeforeRet_;};	T6_ = ((NI)(TM__0JXiWyhP5OCO8jWMA6sb1w_10) < (NI)(TM__0JXiWyhP5OCO8jWMA6sb1w_11));	if (T6_) goto LA8_;

#line 34 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/hashcommon.nim"

#line 34 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/hashcommon.nim"

#line 34 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/hashcommon.nim"
	T9_ = t.data.len;	if (nimSubInt(T9_, t.counter, &TM__0JXiWyhP5OCO8jWMA6sb1w_12)) { raiseOverflow(); goto BeforeRet_;};	T6_ = ((NI)(TM__0JXiWyhP5OCO8jWMA6sb1w_12) < ((NI) 4));	LA8_: ;
	result = T6_;	}BeforeRet_: ;
	popFrame();	return result;}

#line 59 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/hashcommon.nim"
static N_INLINE(NI, rawGetKnownHC__H4n01hI4Y1dhJhVV44eECQsets)(tyObject_HashSet__CD8Dpv0WGmASelVaNSo6zg t, NimStringV2 key, NI hc) {	NI result;	NI h;	NI T6_;	NI TM__0JXiWyhP5OCO8jWMA6sb1w_14;NIM_BOOL* nimErr_;	nimfr_("rawGetKnownHC", "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/h"
"ashcommon.nim");{nimErr_ = nimErrorFlag();	result = (NI)0;
#line 46 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/hashcommon.nim"
	nimln_(46, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/h"
"ashcommon.nim");	{		NI T3_;
#line 46 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/hashcommon.nim"

#line 46 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/hashcommon.nim"
		T3_ = t.data.len;		if (!(T3_ == ((NI) 0))) goto LA4_;

#line 47 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/hashcommon.nim"
		nimln_(47, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/h"
"ashcommon.nim");
#line 47 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/hashcommon.nim"
		result = ((NI) -1);		goto BeforeRet_;
	}
	LA4_: ;

#line 48 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/hashcommon.nim"
	nimln_(48, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/h"
"ashcommon.nim");
#line 48 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/hashcommon.nim"

#line 48 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/hashcommon.nim"
	T6_ = (t.data.len-1);	h = (NI)(hc & T6_);	{
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/hashcommon.nim"
		nimln_(49, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/h"
"ashcommon.nim");		while (1) {			NIM_BOOL T9_;			NI T16_;
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/hashcommon.nim"
			if ((NU)(h) >= (NU)t.data.len){ raiseIndexError2(h,t.data.len-1); goto BeforeRet_;}
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/hashcommon.nim"
			T9_ = (NIM_BOOL)0;			T9_ = isFilled__uHIMxs9aGYDEfZheaMnN2sQsets(t.data.p->data[h].Field0);			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;			if (!T9_) goto LA8;

#line 54 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/hashcommon.nim"
			nimln_(54, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/h"
"ashcommon.nim");			{				NIM_BOOL T12_;
#line 54 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/hashcommon.nim"
				T12_ = (NIM_BOOL)0;
#line 54 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/hashcommon.nim"
				if ((NU)(h) >= (NU)t.data.len){ raiseIndexError2(h,t.data.len-1); goto BeforeRet_;}				T12_ = (t.data.p->data[h].Field0 == hc);				if (!(T12_)) goto LA13_;

#line 54 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/hashcommon.nim"
				if ((NU)(h) >= (NU)t.data.len){ raiseIndexError2(h,t.data.len-1); goto BeforeRet_;}				T12_ = eqStrings(t.data.p->data[h].Field1, key);				LA13_: ;
				if (!T12_) goto LA14_;

#line 55 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/hashcommon.nim"
				nimln_(55, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/h"
"ashcommon.nim");
#line 55 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/hashcommon.nim"
				result = h;				goto BeforeRet_;
			}
			LA14_: ;

#line 56 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/hashcommon.nim"
			nimln_(56, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/h"
"ashcommon.nim");
#line 56 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/hashcommon.nim"
			T16_ = (t.data.len-1);
#line 56 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/hashcommon.nim"
			h = nextTry__YQqpuaZxbzuIDQ5oZ9bnvuQsets(h, T16_);			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;		} LA8: ;
	}

#line 57 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/hashcommon.nim"
	nimln_(57, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/h"
"ashcommon.nim");
#line 57 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/hashcommon.nim"
	if (nimSubInt(((NI) -1), h, &TM__0JXiWyhP5OCO8jWMA6sb1w_14)) { raiseOverflow(); goto BeforeRet_;};	result = (NI)(TM__0JXiWyhP5OCO8jWMA6sb1w_14);	}BeforeRet_: ;
	popFrame();	return result;}

#line 32 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/setimpl.nim"
N_LIB_PRIVATE N_NIMCALL(void, rawInsert__0WGPG59byJ2eMftxsrjD02A)(tyObject_HashSet__CD8Dpv0WGmASelVaNSo6zg* s, tySequence__4eRCaZmrYLLw2k30GPTiMw* data, NimStringV2 key, NI hc, NI h) {NIM_BOOL* nimErr_;	nimfr_("rawInsert", "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/s"
"etimpl.nim");{nimErr_ = nimErrorFlag();
#line 27 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/setimpl.nim"
	nimln_(27, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/s"
"etimpl.nim");	{		NI T4_;
#line 27 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/setimpl.nim"

#line 27 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/setimpl.nim"
		T4_ = (*data).len;		if (!(T4_ == ((NI) 0))) goto LA5_;

#line 19 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/setimpl.nim"
		nimln_(19, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/s"
"etimpl.nim");		{			NIM_BOOL T9_;
#line 19 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/setimpl.nim"

#line 19 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/setimpl.nim"

#line 19 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/setimpl.nim"
			T9_ = (NIM_BOOL)0;			T9_ = isPowerOfTwo__1xdTQapFveM9bImKot7h9cdw(((NI) 64));			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;			if (!!(T9_)) goto LA10_;

#line 19 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/setimpl.nim"

#line 19 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/setimpl.nim"
			failedAssertImpl__W9cjVocn1tjhW7p7xohJj6A(TM__0JXiWyhP5OCO8jWMA6sb1w_16);
			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;		}
		LA10_: ;

#line 23 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/setimpl.nim"
		nimln_(23, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/s"
"etimpl.nim");		(*s).counter = ((NI) 0);
#line 28 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/setimpl.nim"
		nimln_(28, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/s"
"etimpl.nim");		(*s).data.len = ((NI) 64); (*s).data.p = (tySequence__4eRCaZmrYLLw2k30GPTiMw_Content*) newSeqPayload(((NI) 64), sizeof(tyTuple__QeWl6B6ffS4pU6WWrtcrDw), NIM_ALIGNOF(tyTuple__QeWl6B6ffS4pU6WWrtcrDw));	}
	LA5_: ;

#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
	nimln_(49, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");	if ((NU)(h) >= (NU)(*data).len){ raiseIndexError2(h,(*data).len-1); goto LA1_;}
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
	eqsink___aBBXmHFBEivKqERloP6zmA((&(*data).p->data[h].Field1), key);

#line 29 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/setimpl.nim"
	nimln_(29, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/s"
"etimpl.nim");	key.len = 0; key.p = NIM_NIL;	if ((NU)(h) >= (NU)(*data).len){ raiseIndexError2(h,(*data).len-1); goto LA1_;}
#line 30 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/setimpl.nim"
	nimln_(30, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/s"
"etimpl.nim");	(*data).p->data[h].Field0 = hc;	{		LA1_:;	}
	{
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
		nimln_(49, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
		eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&key));
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}BeforeRet_: ;
	popFrame();}

#line 166 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim"
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___1GwzQah0ciEGiSvKbGJgpg)(tySequence__4eRCaZmrYLLw2k30GPTiMw* dest) {	NI colontmp_;
#line 166 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim"
	colontmp_ = ((NI) 0);	{
#line 166 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim"
		while (1) {			NI T3_;
#line 166 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim"

#line 166 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim"
			T3_ = (*dest).len;			if (!(colontmp_ < T3_)) goto LA2;

#line 166 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim"

#line 166 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim"
			eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&(*dest).p->data[colontmp_].Field1));

#line 166 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim"
			colontmp_ += ((NI) 1);		} LA2: ;
	}

#line 166 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim"
	if ((*dest).p && !((*dest).p->cap & NIM_STRLIT_FLAG)) { deallocShared((*dest).p); (*dest).p = NIM_NIL; (*dest).len = 0; }}

#line 36 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/setimpl.nim"
N_LIB_PRIVATE N_NIMCALL(void, enlarge__S48V0eiEuyCalh7won1YWQ)(tyObject_HashSet__CD8Dpv0WGmASelVaNSo6zg* s) {	tySequence__4eRCaZmrYLLw2k30GPTiMw n;	NimStringV2 colontmpD_;	NI T2_;	NI TM__0JXiWyhP5OCO8jWMA6sb1w_13;	tySequence__4eRCaZmrYLLw2k30GPTiMw T3_;NIM_BOOL oldNimErrFin1_;NIM_BOOL* nimErr_;	nimfr_("enlarge", "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/s"
"etimpl.nim");{nimErr_ = nimErrorFlag();	n.len = 0; n.p = NIM_NIL;	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
#line 38 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/setimpl.nim"
	nimln_(38, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/s"
"etimpl.nim");
#line 38 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/setimpl.nim"

#line 38 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/setimpl.nim"
	T2_ = (*s).data.len;	if (nimMulInt(T2_, ((NI) 2), &TM__0JXiWyhP5OCO8jWMA6sb1w_13)) { raiseOverflow(); goto LA1_;};	if (((NI)(TM__0JXiWyhP5OCO8jWMA6sb1w_13)) < ((NI) 0) || ((NI)(TM__0JXiWyhP5OCO8jWMA6sb1w_13)) > ((NI) IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__0JXiWyhP5OCO8jWMA6sb1w_13), ((NI) 0), ((NI) IL64(9223372036854775807))); goto LA1_;}	n.len = ((NI) ((NI)(TM__0JXiWyhP5OCO8jWMA6sb1w_13))); n.p = (tySequence__4eRCaZmrYLLw2k30GPTiMw_Content*) newSeqPayload(((NI) ((NI)(TM__0JXiWyhP5OCO8jWMA6sb1w_13))), sizeof(tyTuple__QeWl6B6ffS4pU6WWrtcrDw), NIM_ALIGNOF(tyTuple__QeWl6B6ffS4pU6WWrtcrDw));
#line 39 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/setimpl.nim"
	nimln_(39, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/s"
"etimpl.nim");	T3_.len = 0; T3_.p = NIM_NIL;	T3_ = (*s).data;	(*s).data = n;	n = T3_;	{		NI i;		NI colontmp_;		NI T5_;		NI res;		i = (NI)0;		colontmp_ = (NI)0;
#line 40 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/setimpl.nim"
		nimln_(40, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/s"
"etimpl.nim");
#line 40 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/setimpl.nim"
		T5_ = (n.len-1);		colontmp_ = T5_;
#line 56 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators_1.nim"
		nimln_(56, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators_1"
".nim");		res = ((NI) 0);		{
#line 57 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators_1.nim"
			nimln_(57, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators_1"
".nim");			while (1) {				NI TM__0JXiWyhP5OCO8jWMA6sb1w_17;
#line 57 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators_1.nim"
				if (!(res <= colontmp_)) goto LA7;

#line 40 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/setimpl.nim"
				nimln_(40, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/s"
"etimpl.nim");				i = res;
#line 41 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/setimpl.nim"
				nimln_(41, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/s"
"etimpl.nim");				{					NIM_BOOL T10_;					NI j;					NI T13_;					NI TM__0JXiWyhP5OCO8jWMA6sb1w_15;
#line 41 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/setimpl.nim"
					if ((NU)(i) >= (NU)n.len){ raiseIndexError2(i,n.len-1); goto LA1_;}
#line 41 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/setimpl.nim"
					T10_ = (NIM_BOOL)0;					T10_ = isFilled__uHIMxs9aGYDEfZheaMnN2sQsets(n.p->data[i].Field0);					if (NIM_UNLIKELY(*nimErr_)) goto LA1_;					if (!T10_) goto LA11_;

#line 42 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/setimpl.nim"
					nimln_(42, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/s"
"etimpl.nim");
#line 42 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/setimpl.nim"

#line 42 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/setimpl.nim"
					if ((NU)(i) >= (NU)n.len){ raiseIndexError2(i,n.len-1); goto LA1_;}					if ((NU)(i) >= (NU)n.len){ raiseIndexError2(i,n.len-1); goto LA1_;}
#line 42 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/setimpl.nim"
					T13_ = (NI)0;					T13_ = rawGetKnownHC__H4n01hI4Y1dhJhVV44eECQsets((*s), n.p->data[i].Field1, n.p->data[i].Field0);					if (NIM_UNLIKELY(*nimErr_)) goto LA1_;					if (nimSubInt(((NI) -1), T13_, &TM__0JXiWyhP5OCO8jWMA6sb1w_15)) { raiseOverflow(); goto LA1_;};					j = (NI)(TM__0JXiWyhP5OCO8jWMA6sb1w_15);
#line 43 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/setimpl.nim"
					nimln_(43, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/s"
"etimpl.nim");
#line 43 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/setimpl.nim"
					colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
					nimln_(49, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");					if ((NU)(i) >= (NU)n.len){ raiseIndexError2(i,n.len-1); goto LA1_;}
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
					eq___aBBXmHFBEivKqERloP6zmA_2((&colontmpD_), n.p->data[i].Field1);
					if ((NU)(i) >= (NU)n.len){ raiseIndexError2(i,n.len-1); goto LA1_;}
#line 43 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/setimpl.nim"
					nimln_(43, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/s"
"etimpl.nim");					rawInsert__0WGPG59byJ2eMftxsrjD02A(s, (&(*s).data), colontmpD_, n.p->data[i].Field0, j);
					if (NIM_UNLIKELY(*nimErr_)) goto LA1_;				}
				LA11_: ;

#line 59 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators_1.nim"
				nimln_(59, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators_1"
".nim");				if (nimAddInt(res, ((NI) 1), &TM__0JXiWyhP5OCO8jWMA6sb1w_17)) { raiseOverflow(); goto LA1_;};				res = (NI)(TM__0JXiWyhP5OCO8jWMA6sb1w_17);			} LA7: ;
		}
	}
	{		LA1_:;	}
	{		oldNimErrFin1_ = *nimErr_; *nimErr_ = NIM_FALSE;
#line 166 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim"
		nimln_(166, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim");
#line 166 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unittest.nim"
		eqdestroy___1GwzQah0ciEGiSvKbGJgpg((&n));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;		*nimErr_ = oldNimErrFin1_;	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}BeforeRet_: ;
	popFrame();}

#line 175 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/sets.nim"
N_LIB_PRIVATE N_NIMCALL(void, incl__TMNSyv4q8yRKlH5e1bO09cA)(tyObject_HashSet__CD8Dpv0WGmASelVaNSo6zg* s, NimStringV2 key) {	NI hc;	NI index;NIM_BOOL* nimErr_;	nimfr_("incl", "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/s"
"ets.nim");{nimErr_ = nimErrorFlag();
#line 46 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/setimpl.nim"
	nimln_(46, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/s"
"etimpl.nim");	{		NI T4_;
#line 46 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/setimpl.nim"

#line 46 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/setimpl.nim"
		T4_ = (*s).data.len;		if (!(T4_ == ((NI) 0))) goto LA5_;

#line 19 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/setimpl.nim"
		nimln_(19, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/s"
"etimpl.nim");		{			NIM_BOOL T9_;
#line 19 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/setimpl.nim"

#line 19 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/setimpl.nim"

#line 19 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/setimpl.nim"
			T9_ = (NIM_BOOL)0;			T9_ = isPowerOfTwo__1xdTQapFveM9bImKot7h9cdw(((NI) 64));			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;			if (!!(T9_)) goto LA10_;

#line 19 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/setimpl.nim"

#line 19 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/setimpl.nim"
			failedAssertImpl__W9cjVocn1tjhW7p7xohJj6A(TM__0JXiWyhP5OCO8jWMA6sb1w_5);
			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;		}
		LA10_: ;

#line 23 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/setimpl.nim"
		nimln_(23, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/s"
"etimpl.nim");		(*s).counter = ((NI) 0);
#line 47 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/setimpl.nim"
		nimln_(47, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/s"
"etimpl.nim");		(*s).data.len = ((NI) 64); (*s).data.p = (tySequence__4eRCaZmrYLLw2k30GPTiMw_Content*) newSeqPayload(((NI) 64), sizeof(tyTuple__QeWl6B6ffS4pU6WWrtcrDw), NIM_ALIGNOF(tyTuple__QeWl6B6ffS4pU6WWrtcrDw));	}
	LA5_: ;
	hc = (NI)0;
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/setimpl.nim"
	nimln_(49, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/s"
"etimpl.nim");
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/setimpl.nim"
	index = rawGet__h9bD59bk9aSaP9ae9axJ475zaRgsets((*s), key, (&hc));	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
#line 190 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/sets.nim"
	nimln_(190, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/s"
"ets.nim");	{		NimStringV2 blitTmp;		NI TM__0JXiWyhP5OCO8jWMA6sb1w_18;		NI TM__0JXiWyhP5OCO8jWMA6sb1w_19;
#line 50 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/setimpl.nim"
		nimln_(50, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/s"
"etimpl.nim");		if (!(index < ((NI) 0))) goto LA14_;

#line 51 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/setimpl.nim"
		nimln_(51, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/s"
"etimpl.nim");		{			NIM_BOOL T18_;
#line 51 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/setimpl.nim"

#line 51 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/setimpl.nim"
			T18_ = (NIM_BOOL)0;			T18_ = mustRehash__9aQKy8l9bO9aHJHq2R79c0vEiAsets((*s));			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;			if (!T18_) goto LA19_;

#line 52 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/setimpl.nim"
			nimln_(52, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/s"
"etimpl.nim");
#line 52 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/setimpl.nim"
			enlarge__S48V0eiEuyCalh7won1YWQ(s);
			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
#line 53 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/setimpl.nim"
			nimln_(53, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/s"
"etimpl.nim");
#line 53 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/setimpl.nim"
			index = rawGetKnownHC__H4n01hI4Y1dhJhVV44eECQsets((*s), key, hc);			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;		}
		LA19_: ;

#line 54 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/setimpl.nim"
		nimln_(54, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/s"
"etimpl.nim");
#line 54 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/setimpl.nim"
		blitTmp = key;
#line 54 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/setimpl.nim"
		key.len = 0; key.p = NIM_NIL;
#line 54 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/setimpl.nim"
		if (nimSubInt(((NI) -1), index, &TM__0JXiWyhP5OCO8jWMA6sb1w_18)) { raiseOverflow(); goto LA1_;};
#line 54 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/setimpl.nim"
		rawInsert__0WGPG59byJ2eMftxsrjD02A(s, (&(*s).data), blitTmp, hc, (NI)(TM__0JXiWyhP5OCO8jWMA6sb1w_18));
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
#line 55 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/setimpl.nim"
		nimln_(55, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/s"
"etimpl.nim");		if (nimAddInt((*s).counter, ((NI) 1), &TM__0JXiWyhP5OCO8jWMA6sb1w_19)) { raiseOverflow(); goto LA1_;};		(*s).counter = (NI)(TM__0JXiWyhP5OCO8jWMA6sb1w_19);	}
	LA14_: ;
	{		LA1_:;	}
	{
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
		nimln_(49, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
		eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&key));
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}BeforeRet_: ;
	popFrame();}

#line 365 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/sets.nim"
N_LIB_PRIVATE N_NIMCALL(NI, len__sVMoSv8jxXZJxl8pFcjd4Q)(tyObject_HashSet__CD8Dpv0WGmASelVaNSo6zg s) {	NI result;	nimfr_("len", "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/s"
"ets.nim");	result = (NI)0;
#line 377 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/sets.nim"
	nimln_(377, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/s"
"ets.nim");	result = s.counter;	popFrame();	return result;}
