/* Generated by Nim Compiler v1.3.3 */
/*   (c) 2020 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w -g  -I/Users/elcritch/.asdf/installs/nim/devel/lib -I/Volumes/datastore/projects/pt/third-party/spryvm/tests -o /Volumes/datastore/projects/pt/third-party/spryvm/tests/_nimcache/stdlib_unicode.nim.c.o /Volumes/datastore/projects/pt/third-party/spryvm/tests/_nimcache/stdlib_unicode.nim.c */
#define NIM_INTBITS 64

/* section: NIM_merge_HEADERS */

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix

/* section: NIM_merge_FRAME_DEFINES */
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
  
/* section: NIM_merge_FORWARD_TYPES */
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;

/* section: NIM_merge_TYPES */
struct NimStrPayload {NI cap;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {NI len;
NimStrPayload* p;
};

/* section: NIM_merge_PROC_HEADERS */
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i, NI n);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(NI, runeLenAt__WMpE2MYPWM1HlcK1wXx02Q)(NimStringV2 s, NI i);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i, NI64 a, NI64 b);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(NIM_BOOL, lteqpercent___x8ObPz55IkLprSyPyqBSRAsystem)(NI32 x, NI32 y);
N_LIB_PRIVATE N_NIMCALL(void, setLengthStrV2)(NimStringV2* s, NI newLen);
N_LIB_PRIVATE N_NIMCALL(void, nimPrepareStrMutationV2)(NimStringV2* s);

/* section: NIM_merge_DATA */
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__e1RUVS0Bw7xmj9cnDPXLJMQ_25 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__e1RUVS0Bw7xmj9cnDPXLJMQ_26 = {0, (NimStrPayload*)&TM__e1RUVS0Bw7xmj9cnDPXLJMQ_25};

/* section: NIM_merge_VARS */
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_BOOL nimInErrorMode__759bT87luu8XGcbkw13FUjA;

/* section: NIM_merge_PROCS */

#line 541 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
static N_INLINE(void, nimFrame)(TFrame* s) {
#line 542 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	{
#line 542 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
		if (!(framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA3_;

#line 543 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
		(*s).calldepth = ((NI16) 0);	}
	goto LA1_;
	LA3_: ;
	{
#line 546 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"

#line 546 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
		(*s).calldepth = (NI16)((*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1));	}
	LA1_: ;

#line 548 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	(*s).prev = framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
#line 549 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = s;
#line 550 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	{
#line 550 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
		if (!((*s).calldepth == ((NI16) 2000))) goto LA8_;

#line 550 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"

#line 550 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
		callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw();
	}
	LA8_: ;
}

#line 85 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
static N_INLINE(void, popFrame)(void) {
#line 86 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).prev;}

#line 35 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
N_LIB_PRIVATE N_NIMCALL(NI, nucruneLen)(NimStringV2 s) {	NI result;	NI i;	nimfr_("runeLen", "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim");{	result = (NI)0;
#line 42 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
	nimln_(42, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim");	i = ((NI) 0);	{
#line 43 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
		nimln_(43, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim");		while (1) {			NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_9;
#line 43 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"

#line 43 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
			if (!(i < s.len)) goto LA2;

#line 44 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
			nimln_(44, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim");			{				NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_2;
#line 44 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
				if ((NU)(i) >= (NU)s.len){ raiseIndexError2(i,s.len-1); goto BeforeRet_;}				if (!((NU64)(((NU) (((NU8)(s.p->data[i]))))) <= (NU64)(((NU) 127)))) goto LA5_;

#line 44 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
				if (nimAddInt(i, ((NI) 1), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_2)) { raiseOverflow(); goto BeforeRet_;};				i = (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_2);			}
			goto LA3_;
			LA5_: ;
			{				NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_3;
#line 45 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
				nimln_(45, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim");
#line 45 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
				if ((NU)(i) >= (NU)s.len){ raiseIndexError2(i,s.len-1); goto BeforeRet_;}				if (!((NU)((NU64)(((NU) (((NU8)(s.p->data[i]))))) >> (NU64)(((NI) 5))) == ((NU) 6))) goto LA8_;

#line 45 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
				if (nimAddInt(i, ((NI) 2), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_3)) { raiseOverflow(); goto BeforeRet_;};				i = (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_3);			}
			goto LA3_;
			LA8_: ;
			{				NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_4;
#line 46 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
				nimln_(46, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim");
#line 46 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
				if ((NU)(i) >= (NU)s.len){ raiseIndexError2(i,s.len-1); goto BeforeRet_;}				if (!((NU)((NU64)(((NU) (((NU8)(s.p->data[i]))))) >> (NU64)(((NI) 4))) == ((NU) 14))) goto LA11_;

#line 46 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
				if (nimAddInt(i, ((NI) 3), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_4)) { raiseOverflow(); goto BeforeRet_;};				i = (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_4);			}
			goto LA3_;
			LA11_: ;
			{				NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_5;
#line 47 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
				nimln_(47, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim");
#line 47 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
				if ((NU)(i) >= (NU)s.len){ raiseIndexError2(i,s.len-1); goto BeforeRet_;}				if (!((NU)((NU64)(((NU) (((NU8)(s.p->data[i]))))) >> (NU64)(((NI) 3))) == ((NU) 30))) goto LA14_;

#line 47 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
				if (nimAddInt(i, ((NI) 4), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_5)) { raiseOverflow(); goto BeforeRet_;};				i = (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_5);			}
			goto LA3_;
			LA14_: ;
			{				NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_6;
#line 48 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
				nimln_(48, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim");
#line 48 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
				if ((NU)(i) >= (NU)s.len){ raiseIndexError2(i,s.len-1); goto BeforeRet_;}				if (!((NU)((NU64)(((NU) (((NU8)(s.p->data[i]))))) >> (NU64)(((NI) 2))) == ((NU) 62))) goto LA17_;

#line 48 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
				if (nimAddInt(i, ((NI) 5), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_6)) { raiseOverflow(); goto BeforeRet_;};				i = (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_6);			}
			goto LA3_;
			LA17_: ;
			{				NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_7;
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
				nimln_(49, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim");
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
				if ((NU)(i) >= (NU)s.len){ raiseIndexError2(i,s.len-1); goto BeforeRet_;}				if (!((NU)((NU64)(((NU) (((NU8)(s.p->data[i]))))) >> (NU64)(((NI) 1))) == ((NU) 126))) goto LA20_;

#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
				if (nimAddInt(i, ((NI) 6), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_7)) { raiseOverflow(); goto BeforeRet_;};				i = (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_7);			}
			goto LA3_;
			LA20_: ;
			{				NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_8;
#line 50 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
				nimln_(50, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim");				if (nimAddInt(i, ((NI) 1), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_8)) { raiseOverflow(); goto BeforeRet_;};				i = (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_8);			}
			LA3_: ;

#line 51 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
			nimln_(51, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim");			if (nimAddInt(result, ((NI) 1), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_9)) { raiseOverflow(); goto BeforeRet_;};			result = (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_9);		} LA2: ;
	}
	}BeforeRet_: ;
	popFrame();	return result;}

#line 53 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
N_LIB_PRIVATE N_NIMCALL(NI, runeLenAt__WMpE2MYPWM1HlcK1wXx02Q)(NimStringV2 s, NI i) {	NI result;	nimfr_("runeLenAt", "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim");{	result = (NI)0;
#line 63 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
	nimln_(63, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim");	{
#line 63 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
		if ((NU)(i) >= (NU)s.len){ raiseIndexError2(i,s.len-1); goto BeforeRet_;}		if (!((NU64)(((NU) (((NU8)(s.p->data[i]))))) <= (NU64)(((NU) 127)))) goto LA3_;

#line 63 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
		result = ((NI) 1);	}
	goto LA1_;
	LA3_: ;
	{
#line 64 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
		nimln_(64, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim");
#line 64 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
		if ((NU)(i) >= (NU)s.len){ raiseIndexError2(i,s.len-1); goto BeforeRet_;}		if (!((NU)((NU64)(((NU) (((NU8)(s.p->data[i]))))) >> (NU64)(((NI) 5))) == ((NU) 6))) goto LA6_;

#line 64 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
		result = ((NI) 2);	}
	goto LA1_;
	LA6_: ;
	{
#line 65 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
		nimln_(65, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim");
#line 65 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
		if ((NU)(i) >= (NU)s.len){ raiseIndexError2(i,s.len-1); goto BeforeRet_;}		if (!((NU)((NU64)(((NU) (((NU8)(s.p->data[i]))))) >> (NU64)(((NI) 4))) == ((NU) 14))) goto LA9_;

#line 65 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
		result = ((NI) 3);	}
	goto LA1_;
	LA9_: ;
	{
#line 66 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
		nimln_(66, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim");
#line 66 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
		if ((NU)(i) >= (NU)s.len){ raiseIndexError2(i,s.len-1); goto BeforeRet_;}		if (!((NU)((NU64)(((NU) (((NU8)(s.p->data[i]))))) >> (NU64)(((NI) 3))) == ((NU) 30))) goto LA12_;

#line 66 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
		result = ((NI) 4);	}
	goto LA1_;
	LA12_: ;
	{
#line 67 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
		nimln_(67, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim");
#line 67 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
		if ((NU)(i) >= (NU)s.len){ raiseIndexError2(i,s.len-1); goto BeforeRet_;}		if (!((NU)((NU64)(((NU) (((NU8)(s.p->data[i]))))) >> (NU64)(((NI) 2))) == ((NU) 62))) goto LA15_;

#line 67 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
		result = ((NI) 5);	}
	goto LA1_;
	LA15_: ;
	{
#line 68 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
		nimln_(68, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim");
#line 68 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
		if ((NU)(i) >= (NU)s.len){ raiseIndexError2(i,s.len-1); goto BeforeRet_;}		if (!((NU)((NU64)(((NU) (((NU8)(s.p->data[i]))))) >> (NU64)(((NI) 1))) == ((NU) 126))) goto LA18_;

#line 68 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
		result = ((NI) 6);	}
	goto LA1_;
	LA18_: ;
	{
#line 69 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
		nimln_(69, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim");		result = ((NI) 1);	}
	LA1_: ;
	}BeforeRet_: ;
	popFrame();	return result;}

#line 424 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {	NIM_BOOL* result;	result = (NIM_BOOL*)0;
#line 425 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	result = (&nimInErrorMode__759bT87luu8XGcbkw13FUjA);	return result;}

#line 302 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
N_LIB_PRIVATE N_NIMCALL(NI, runeOffset__EnrqtYM0boqQqeAIRc9bdmA)(NimStringV2 s, NI pos, NI start) {	NI result;	NI i;	NI o;NIM_BOOL* nimErr_;	nimfr_("runeOffset", "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim");{nimErr_ = nimErrorFlag();	result = (NI)0;
#line 320 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
	nimln_(320, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim");	i = ((NI) 0);
#line 321 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
	nimln_(321, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim");	o = start;	{
#line 322 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
		nimln_(322, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim");		while (1) {			NI T3_;			NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_10;			NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_11;
#line 322 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
			if (!(i < ((NI) (pos)))) goto LA2;

#line 323 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
			nimln_(323, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim");
#line 323 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"

#line 323 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
			T3_ = (NI)0;			T3_ = runeLenAt__WMpE2MYPWM1HlcK1wXx02Q(s, o);			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;			if ((T3_) < ((NI) 0) || (T3_) > ((NI) IL64(9223372036854775807))){ raiseRangeErrorI(T3_, ((NI) 0), ((NI) IL64(9223372036854775807))); goto BeforeRet_;}			if (nimAddInt(o, ((NI) (T3_)), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_10)) { raiseOverflow(); goto BeforeRet_;};			if (TM__e1RUVS0Bw7xmj9cnDPXLJMQ_10 < 0 || TM__e1RUVS0Bw7xmj9cnDPXLJMQ_10 > IL64(9223372036854775807)){ raiseOverflow(); goto BeforeRet_;}			o = (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_10);
#line 324 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
			nimln_(324, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim");			{
#line 324 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"

#line 324 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
				if (!(s.len <= ((NI) (o)))) goto LA6_;

#line 325 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
				nimln_(325, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim");
#line 325 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
				result = ((NI) -1);				goto BeforeRet_;
			}
			LA6_: ;

#line 326 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
			nimln_(326, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim");			if (nimAddInt(i, ((NI) 1), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_11)) { raiseOverflow(); goto BeforeRet_;};			i = (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_11);		} LA2: ;
	}

#line 327 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
	nimln_(327, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim");
#line 327 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
	result = ((NI) (o));	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();	return result;}

#line 165 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
N_LIB_PRIVATE N_NIMCALL(NI, validateUtf8__gZHDHaRdP4jROav7Hun29aA)(NimStringV2 s) {	NI result;	NI i;	NI L;	nimfr_("validateUtf8", "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim");{	result = (NI)0;
#line 173 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
	nimln_(173, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim");	i = ((NI) 0);
#line 174 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
	nimln_(174, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim");
#line 174 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
	L = s.len;	{
#line 175 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
		nimln_(175, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim");		while (1) {
#line 175 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
			if (!(i < L)) goto LA2;

#line 176 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
			nimln_(176, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim");			{				NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_12;
#line 176 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
				if ((NU)(i) >= (NU)s.len){ raiseIndexError2(i,s.len-1); goto BeforeRet_;}				if (!((NU64)(((NU) (((NU8)(s.p->data[i]))))) <= (NU64)(((NU) 127)))) goto LA5_;

#line 177 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
				nimln_(177, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim");				if (nimAddInt(i, ((NI) 1), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_12)) { raiseOverflow(); goto BeforeRet_;};				i = (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_12);			}
			goto LA3_;
			LA5_: ;
			{
#line 178 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
				nimln_(178, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim");
#line 178 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
				if ((NU)(i) >= (NU)s.len){ raiseIndexError2(i,s.len-1); goto BeforeRet_;}				if (!((NU)((NU64)(((NU) (((NU8)(s.p->data[i]))))) >> (NU64)(((NI) 5))) == ((NU) 6))) goto LA8_;

#line 179 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
				nimln_(179, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim");				{
#line 179 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
					if ((NU)(i) >= (NU)s.len){ raiseIndexError2(i,s.len-1); goto BeforeRet_;}					if (!((NU64)(((NU) (((NU8)(s.p->data[i]))))) < (NU64)(((NU) 194)))) goto LA12_;

#line 179 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"

#line 179 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
					result = i;					goto BeforeRet_;
				}
				LA12_: ;

#line 180 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
				nimln_(180, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim");				{					NIM_BOOL T16_;					NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_13;					NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_14;					NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_15;
#line 180 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
					T16_ = (NIM_BOOL)0;
#line 180 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"

#line 180 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
					if (nimAddInt(i, ((NI) 1), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_13)) { raiseOverflow(); goto BeforeRet_;};					T16_ = ((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_13) < L);					if (!(T16_)) goto LA17_;

#line 180 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"

#line 180 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"

#line 180 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
					if (nimAddInt(i, ((NI) 1), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_14)) { raiseOverflow(); goto BeforeRet_;};					if ((NU)((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_14)) >= (NU)s.len){ raiseIndexError2((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_14),s.len-1); goto BeforeRet_;}					T16_ = ((NU)((NU64)(((NU) (((NU8)(s.p->data[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_14)]))))) >> (NU64)(((NI) 6))) == ((NU) 2));					LA17_: ;
					if (!T16_) goto LA18_;

#line 180 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
					if (nimAddInt(i, ((NI) 2), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_15)) { raiseOverflow(); goto BeforeRet_;};					i = (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_15);				}
				goto LA14_;
				LA18_: ;
				{
#line 181 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
					nimln_(181, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim");
#line 181 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
					result = i;					goto BeforeRet_;
				}
				LA14_: ;
			}
			goto LA3_;
			LA8_: ;
			{
#line 182 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
				nimln_(182, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim");
#line 182 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
				if ((NU)(i) >= (NU)s.len){ raiseIndexError2(i,s.len-1); goto BeforeRet_;}				if (!((NU)((NU64)(((NU) (((NU8)(s.p->data[i]))))) >> (NU64)(((NI) 4))) == ((NU) 14))) goto LA22_;

#line 183 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
				nimln_(183, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim");				{					NIM_BOOL T26_;					NIM_BOOL T27_;					NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_16;					NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_17;					NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_18;					NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_19;
#line 183 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
					T26_ = (NIM_BOOL)0;
#line 183 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
					T27_ = (NIM_BOOL)0;
#line 183 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"

#line 183 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
					if (nimAddInt(i, ((NI) 2), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_16)) { raiseOverflow(); goto BeforeRet_;};					T27_ = ((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_16) < L);					if (!(T27_)) goto LA28_;

#line 183 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"

#line 183 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"

#line 183 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
					if (nimAddInt(i, ((NI) 1), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_17)) { raiseOverflow(); goto BeforeRet_;};					if ((NU)((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_17)) >= (NU)s.len){ raiseIndexError2((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_17),s.len-1); goto BeforeRet_;}					T27_ = ((NU)((NU64)(((NU) (((NU8)(s.p->data[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_17)]))))) >> (NU64)(((NI) 6))) == ((NU) 2));					LA28_: ;
					T26_ = T27_;					if (!(T26_)) goto LA29_;

#line 183 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"

#line 183 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"

#line 183 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
					if (nimAddInt(i, ((NI) 2), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_18)) { raiseOverflow(); goto BeforeRet_;};					if ((NU)((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_18)) >= (NU)s.len){ raiseIndexError2((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_18),s.len-1); goto BeforeRet_;}					T26_ = ((NU)((NU64)(((NU) (((NU8)(s.p->data[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_18)]))))) >> (NU64)(((NI) 6))) == ((NU) 2));					LA29_: ;
					if (!T26_) goto LA30_;

#line 184 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
					nimln_(184, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim");					if (nimAddInt(i, ((NI) 3), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_19)) { raiseOverflow(); goto BeforeRet_;};					i = (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_19);				}
				goto LA24_;
				LA30_: ;
				{
#line 185 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
					nimln_(185, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim");
#line 185 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
					result = i;					goto BeforeRet_;
				}
				LA24_: ;
			}
			goto LA3_;
			LA22_: ;
			{
#line 186 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
				nimln_(186, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim");
#line 186 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
				if ((NU)(i) >= (NU)s.len){ raiseIndexError2(i,s.len-1); goto BeforeRet_;}				if (!((NU)((NU64)(((NU) (((NU8)(s.p->data[i]))))) >> (NU64)(((NI) 3))) == ((NU) 30))) goto LA34_;

#line 187 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
				nimln_(187, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim");				{					NIM_BOOL T38_;					NIM_BOOL T39_;					NIM_BOOL T40_;					NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_20;					NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_21;					NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_22;					NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_23;					NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_24;
#line 188 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
					nimln_(188, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim");					T38_ = (NIM_BOOL)0;
#line 187 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
					nimln_(187, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim");					T39_ = (NIM_BOOL)0;
#line 187 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
					T40_ = (NIM_BOOL)0;
#line 187 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"

#line 187 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
					if (nimAddInt(i, ((NI) 3), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_20)) { raiseOverflow(); goto BeforeRet_;};					T40_ = ((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_20) < L);					if (!(T40_)) goto LA41_;

#line 187 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"

#line 187 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"

#line 187 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
					if (nimAddInt(i, ((NI) 1), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_21)) { raiseOverflow(); goto BeforeRet_;};					if ((NU)((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_21)) >= (NU)s.len){ raiseIndexError2((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_21),s.len-1); goto BeforeRet_;}					T40_ = ((NU)((NU64)(((NU) (((NU8)(s.p->data[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_21)]))))) >> (NU64)(((NI) 6))) == ((NU) 2));					LA41_: ;
					T39_ = T40_;					if (!(T39_)) goto LA42_;

#line 188 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
					nimln_(188, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim");
#line 188 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"

#line 188 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
					if (nimAddInt(i, ((NI) 2), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_22)) { raiseOverflow(); goto BeforeRet_;};					if ((NU)((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_22)) >= (NU)s.len){ raiseIndexError2((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_22),s.len-1); goto BeforeRet_;}					T39_ = ((NU)((NU64)(((NU) (((NU8)(s.p->data[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_22)]))))) >> (NU64)(((NI) 6))) == ((NU) 2));					LA42_: ;
					T38_ = T39_;					if (!(T38_)) goto LA43_;

#line 189 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
					nimln_(189, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim");
#line 189 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"

#line 189 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
					if (nimAddInt(i, ((NI) 3), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_23)) { raiseOverflow(); goto BeforeRet_;};					if ((NU)((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_23)) >= (NU)s.len){ raiseIndexError2((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_23),s.len-1); goto BeforeRet_;}					T38_ = ((NU)((NU64)(((NU) (((NU8)(s.p->data[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_23)]))))) >> (NU64)(((NI) 6))) == ((NU) 2));					LA43_: ;
					if (!T38_) goto LA44_;

#line 190 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
					nimln_(190, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim");					if (nimAddInt(i, ((NI) 4), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_24)) { raiseOverflow(); goto BeforeRet_;};					i = (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_24);				}
				goto LA36_;
				LA44_: ;
				{
#line 191 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
					nimln_(191, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim");
#line 191 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
					result = i;					goto BeforeRet_;
				}
				LA36_: ;
			}
			goto LA3_;
			LA34_: ;
			{
#line 193 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
				nimln_(193, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim");
#line 193 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
				result = i;				goto BeforeRet_;
			}
			LA3_: ;
		} LA2: ;
	}

#line 194 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
	nimln_(194, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim");
#line 194 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
	result = ((NI) -1);	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();	return result;}

#line 184 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/comparisons.nim"
static N_INLINE(NIM_BOOL, lteqpercent___x8ObPz55IkLprSyPyqBSRAsystem)(NI32 x, NI32 y) {	NIM_BOOL result;	nimfr_("<=%", "/Users/elcritch/.asdf/installs/nim/devel/lib/system/comparisons"
".nim");	result = (NIM_BOOL)0;
#line 184 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/comparisons.nim"
	nimln_(184, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/comparisons"
".nim");
#line 184 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/comparisons.nim"
	result = ((NU32)(((NU32) (x))) <= (NU32)(((NU32) (y))));	popFrame();	return result;}

#line 253 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nuctoUTF8)(NI32 c) {	NimStringV2 result;	NI32 iX60gensym13155461_;	nimfr_("toUTF8", "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim");{	result.len = 0; result.p = NIM_NIL;
#line 265 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
	nimln_(265, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim");	result = TM__e1RUVS0Bw7xmj9cnDPXLJMQ_26;
#line 210 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
	nimln_(210, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim");	iX60gensym13155461_ = c;
#line 266 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
	nimln_(266, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim");	{		NIM_BOOL T3_;
#line 211 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
		nimln_(211, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim");
#line 211 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
		T3_ = (NIM_BOOL)0;		T3_ = lteqpercent___x8ObPz55IkLprSyPyqBSRAsystem(iX60gensym13155461_, ((NI32) 127));		if (!T3_) goto LA4_;

#line 212 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
		nimln_(212, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim");		setLengthStrV2((&result), ((NI) 1));		if ((NU)(((NI) 0)) >= (NU)result.len){ raiseIndexError2(((NI) 0),result.len-1); goto BeforeRet_;}		nimPrepareStrMutationV2((&result));
#line 213 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
		nimln_(213, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim");
#line 213 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
		if ((iX60gensym13155461_) < ((NI) 0) || (iX60gensym13155461_) > ((NI) 255)){ raiseRangeErrorI(iX60gensym13155461_, ((NI) 0), ((NI) 255)); goto BeforeRet_;}		result.p->data[((NI) 0)] = ((NIM_CHAR) (((NI) (iX60gensym13155461_))));	}
	goto LA1_;
	LA4_: ;
	{		NIM_BOOL T7_;
#line 215 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
		nimln_(215, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim");
#line 215 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
		T7_ = (NIM_BOOL)0;		T7_ = lteqpercent___x8ObPz55IkLprSyPyqBSRAsystem(iX60gensym13155461_, ((NI32) 2047));		if (!T7_) goto LA8_;

#line 216 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
		nimln_(216, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim");		setLengthStrV2((&result), ((NI) 2));		if ((NU)(((NI) 0)) >= (NU)result.len){ raiseIndexError2(((NI) 0),result.len-1); goto BeforeRet_;}		nimPrepareStrMutationV2((&result));
#line 217 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
		nimln_(217, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim");
#line 217 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"

#line 217 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"

#line 217 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
		if (((NI32)((NI32)((NI64)(iX60gensym13155461_) >> (NU64)(((NI) 6))) | ((NI32) 192))) < ((NI) 0) || ((NI32)((NI32)((NI64)(iX60gensym13155461_) >> (NU64)(((NI) 6))) | ((NI32) 192))) > ((NI) 255)){ raiseRangeErrorI((NI32)((NI32)((NI64)(iX60gensym13155461_) >> (NU64)(((NI) 6))) | ((NI32) 192)), ((NI) 0), ((NI) 255)); goto BeforeRet_;}		result.p->data[((NI) 0)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI64)(iX60gensym13155461_) >> (NU64)(((NI) 6))) | ((NI32) 192))))));		if ((NU)(((NI) 1)) >= (NU)result.len){ raiseIndexError2(((NI) 1),result.len-1); goto BeforeRet_;}		nimPrepareStrMutationV2((&result));
#line 218 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
		nimln_(218, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim");
#line 218 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"

#line 218 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"

#line 218 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
		if (((NI32)((NI32)(iX60gensym13155461_ & ((NI32) 63)) | ((NI32) 128))) < ((NI) 0) || ((NI32)((NI32)(iX60gensym13155461_ & ((NI32) 63)) | ((NI32) 128))) > ((NI) 255)){ raiseRangeErrorI((NI32)((NI32)(iX60gensym13155461_ & ((NI32) 63)) | ((NI32) 128)), ((NI) 0), ((NI) 255)); goto BeforeRet_;}		result.p->data[((NI) 1)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)(iX60gensym13155461_ & ((NI32) 63)) | ((NI32) 128))))));	}
	goto LA1_;
	LA8_: ;
	{		NIM_BOOL T11_;
#line 220 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
		nimln_(220, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim");
#line 220 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
		T11_ = (NIM_BOOL)0;		T11_ = lteqpercent___x8ObPz55IkLprSyPyqBSRAsystem(iX60gensym13155461_, ((NI32) 65535));		if (!T11_) goto LA12_;

#line 221 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
		nimln_(221, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim");		setLengthStrV2((&result), ((NI) 3));		if ((NU)(((NI) 0)) >= (NU)result.len){ raiseIndexError2(((NI) 0),result.len-1); goto BeforeRet_;}		nimPrepareStrMutationV2((&result));
#line 222 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
		nimln_(222, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim");
#line 222 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"

#line 222 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"

#line 222 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
		if (((NI32)((NI32)((NI64)(iX60gensym13155461_) >> (NU64)(((NI) 12))) | ((NI32) 224))) < ((NI) 0) || ((NI32)((NI32)((NI64)(iX60gensym13155461_) >> (NU64)(((NI) 12))) | ((NI32) 224))) > ((NI) 255)){ raiseRangeErrorI((NI32)((NI32)((NI64)(iX60gensym13155461_) >> (NU64)(((NI) 12))) | ((NI32) 224)), ((NI) 0), ((NI) 255)); goto BeforeRet_;}		result.p->data[((NI) 0)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI64)(iX60gensym13155461_) >> (NU64)(((NI) 12))) | ((NI32) 224))))));		if ((NU)(((NI) 1)) >= (NU)result.len){ raiseIndexError2(((NI) 1),result.len-1); goto BeforeRet_;}		nimPrepareStrMutationV2((&result));
#line 223 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
		nimln_(223, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim");
#line 223 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"

#line 223 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"

#line 223 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"

#line 223 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
		if (((NI32)((NI32)((NI32)((NI64)(iX60gensym13155461_) >> (NU64)(((NI) 6))) & ((NI32) 63)) | ((NI32) 128))) < ((NI) 0) || ((NI32)((NI32)((NI32)((NI64)(iX60gensym13155461_) >> (NU64)(((NI) 6))) & ((NI32) 63)) | ((NI32) 128))) > ((NI) 255)){ raiseRangeErrorI((NI32)((NI32)((NI32)((NI64)(iX60gensym13155461_) >> (NU64)(((NI) 6))) & ((NI32) 63)) | ((NI32) 128)), ((NI) 0), ((NI) 255)); goto BeforeRet_;}		result.p->data[((NI) 1)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI32)((NI64)(iX60gensym13155461_) >> (NU64)(((NI) 6))) & ((NI32) 63)) | ((NI32) 128))))));		if ((NU)(((NI) 2)) >= (NU)result.len){ raiseIndexError2(((NI) 2),result.len-1); goto BeforeRet_;}		nimPrepareStrMutationV2((&result));
#line 224 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
		nimln_(224, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim");
#line 224 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"

#line 224 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"

#line 224 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
		if (((NI32)((NI32)(iX60gensym13155461_ & ((NI32) 63)) | ((NI32) 128))) < ((NI) 0) || ((NI32)((NI32)(iX60gensym13155461_ & ((NI32) 63)) | ((NI32) 128))) > ((NI) 255)){ raiseRangeErrorI((NI32)((NI32)(iX60gensym13155461_ & ((NI32) 63)) | ((NI32) 128)), ((NI) 0), ((NI) 255)); goto BeforeRet_;}		result.p->data[((NI) 2)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)(iX60gensym13155461_ & ((NI32) 63)) | ((NI32) 128))))));	}
	goto LA1_;
	LA12_: ;
	{		NIM_BOOL T15_;
#line 226 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
		nimln_(226, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim");
#line 226 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
		T15_ = (NIM_BOOL)0;		T15_ = lteqpercent___x8ObPz55IkLprSyPyqBSRAsystem(iX60gensym13155461_, ((NI32) 2097151));		if (!T15_) goto LA16_;

#line 227 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
		nimln_(227, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim");		setLengthStrV2((&result), ((NI) 4));		if ((NU)(((NI) 0)) >= (NU)result.len){ raiseIndexError2(((NI) 0),result.len-1); goto BeforeRet_;}		nimPrepareStrMutationV2((&result));
#line 228 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
		nimln_(228, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim");
#line 228 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"

#line 228 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"

#line 228 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
		if (((NI32)((NI32)((NI64)(iX60gensym13155461_) >> (NU64)(((NI) 18))) | ((NI32) 240))) < ((NI) 0) || ((NI32)((NI32)((NI64)(iX60gensym13155461_) >> (NU64)(((NI) 18))) | ((NI32) 240))) > ((NI) 255)){ raiseRangeErrorI((NI32)((NI32)((NI64)(iX60gensym13155461_) >> (NU64)(((NI) 18))) | ((NI32) 240)), ((NI) 0), ((NI) 255)); goto BeforeRet_;}		result.p->data[((NI) 0)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI64)(iX60gensym13155461_) >> (NU64)(((NI) 18))) | ((NI32) 240))))));		if ((NU)(((NI) 1)) >= (NU)result.len){ raiseIndexError2(((NI) 1),result.len-1); goto BeforeRet_;}		nimPrepareStrMutationV2((&result));
#line 229 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
		nimln_(229, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim");
#line 229 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"

#line 229 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"

#line 229 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"

#line 229 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
		if (((NI32)((NI32)((NI32)((NI64)(iX60gensym13155461_) >> (NU64)(((NI) 12))) & ((NI32) 63)) | ((NI32) 128))) < ((NI) 0) || ((NI32)((NI32)((NI32)((NI64)(iX60gensym13155461_) >> (NU64)(((NI) 12))) & ((NI32) 63)) | ((NI32) 128))) > ((NI) 255)){ raiseRangeErrorI((NI32)((NI32)((NI32)((NI64)(iX60gensym13155461_) >> (NU64)(((NI) 12))) & ((NI32) 63)) | ((NI32) 128)), ((NI) 0), ((NI) 255)); goto BeforeRet_;}		result.p->data[((NI) 1)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI32)((NI64)(iX60gensym13155461_) >> (NU64)(((NI) 12))) & ((NI32) 63)) | ((NI32) 128))))));		if ((NU)(((NI) 2)) >= (NU)result.len){ raiseIndexError2(((NI) 2),result.len-1); goto BeforeRet_;}		nimPrepareStrMutationV2((&result));
#line 230 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
		nimln_(230, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim");
#line 230 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"

#line 230 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"

#line 230 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"

#line 230 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
		if (((NI32)((NI32)((NI32)((NI64)(iX60gensym13155461_) >> (NU64)(((NI) 6))) & ((NI32) 63)) | ((NI32) 128))) < ((NI) 0) || ((NI32)((NI32)((NI32)((NI64)(iX60gensym13155461_) >> (NU64)(((NI) 6))) & ((NI32) 63)) | ((NI32) 128))) > ((NI) 255)){ raiseRangeErrorI((NI32)((NI32)((NI32)((NI64)(iX60gensym13155461_) >> (NU64)(((NI) 6))) & ((NI32) 63)) | ((NI32) 128)), ((NI) 0), ((NI) 255)); goto BeforeRet_;}		result.p->data[((NI) 2)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI32)((NI64)(iX60gensym13155461_) >> (NU64)(((NI) 6))) & ((NI32) 63)) | ((NI32) 128))))));		if ((NU)(((NI) 3)) >= (NU)result.len){ raiseIndexError2(((NI) 3),result.len-1); goto BeforeRet_;}		nimPrepareStrMutationV2((&result));
#line 231 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
		nimln_(231, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim");
#line 231 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"

#line 231 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"

#line 231 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
		if (((NI32)((NI32)(iX60gensym13155461_ & ((NI32) 63)) | ((NI32) 128))) < ((NI) 0) || ((NI32)((NI32)(iX60gensym13155461_ & ((NI32) 63)) | ((NI32) 128))) > ((NI) 255)){ raiseRangeErrorI((NI32)((NI32)(iX60gensym13155461_ & ((NI32) 63)) | ((NI32) 128)), ((NI) 0), ((NI) 255)); goto BeforeRet_;}		result.p->data[((NI) 3)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)(iX60gensym13155461_ & ((NI32) 63)) | ((NI32) 128))))));	}
	goto LA1_;
	LA16_: ;
	{		NIM_BOOL T19_;
#line 233 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
		nimln_(233, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim");
#line 233 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
		T19_ = (NIM_BOOL)0;		T19_ = lteqpercent___x8ObPz55IkLprSyPyqBSRAsystem(iX60gensym13155461_, ((NI32) 67108863));		if (!T19_) goto LA20_;

#line 234 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
		nimln_(234, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim");		setLengthStrV2((&result), ((NI) 5));		if ((NU)(((NI) 0)) >= (NU)result.len){ raiseIndexError2(((NI) 0),result.len-1); goto BeforeRet_;}		nimPrepareStrMutationV2((&result));
#line 235 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
		nimln_(235, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim");
#line 235 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"

#line 235 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"

#line 235 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
		if (((NI32)((NI32)((NI64)(iX60gensym13155461_) >> (NU64)(((NI) 24))) | ((NI32) 248))) < ((NI) 0) || ((NI32)((NI32)((NI64)(iX60gensym13155461_) >> (NU64)(((NI) 24))) | ((NI32) 248))) > ((NI) 255)){ raiseRangeErrorI((NI32)((NI32)((NI64)(iX60gensym13155461_) >> (NU64)(((NI) 24))) | ((NI32) 248)), ((NI) 0), ((NI) 255)); goto BeforeRet_;}		result.p->data[((NI) 0)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI64)(iX60gensym13155461_) >> (NU64)(((NI) 24))) | ((NI32) 248))))));		if ((NU)(((NI) 1)) >= (NU)result.len){ raiseIndexError2(((NI) 1),result.len-1); goto BeforeRet_;}		nimPrepareStrMutationV2((&result));
#line 236 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
		nimln_(236, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim");
#line 236 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"

#line 236 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"

#line 236 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"

#line 236 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
		if (((NI32)((NI32)((NI32)((NI64)(iX60gensym13155461_) >> (NU64)(((NI) 18))) & ((NI32) 63)) | ((NI32) 128))) < ((NI) 0) || ((NI32)((NI32)((NI32)((NI64)(iX60gensym13155461_) >> (NU64)(((NI) 18))) & ((NI32) 63)) | ((NI32) 128))) > ((NI) 255)){ raiseRangeErrorI((NI32)((NI32)((NI32)((NI64)(iX60gensym13155461_) >> (NU64)(((NI) 18))) & ((NI32) 63)) | ((NI32) 128)), ((NI) 0), ((NI) 255)); goto BeforeRet_;}		result.p->data[((NI) 1)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI32)((NI64)(iX60gensym13155461_) >> (NU64)(((NI) 18))) & ((NI32) 63)) | ((NI32) 128))))));		if ((NU)(((NI) 2)) >= (NU)result.len){ raiseIndexError2(((NI) 2),result.len-1); goto BeforeRet_;}		nimPrepareStrMutationV2((&result));
#line 237 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
		nimln_(237, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim");
#line 237 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"

#line 237 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"

#line 237 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"

#line 237 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
		if (((NI32)((NI32)((NI32)((NI64)(iX60gensym13155461_) >> (NU64)(((NI) 12))) & ((NI32) 63)) | ((NI32) 128))) < ((NI) 0) || ((NI32)((NI32)((NI32)((NI64)(iX60gensym13155461_) >> (NU64)(((NI) 12))) & ((NI32) 63)) | ((NI32) 128))) > ((NI) 255)){ raiseRangeErrorI((NI32)((NI32)((NI32)((NI64)(iX60gensym13155461_) >> (NU64)(((NI) 12))) & ((NI32) 63)) | ((NI32) 128)), ((NI) 0), ((NI) 255)); goto BeforeRet_;}		result.p->data[((NI) 2)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI32)((NI64)(iX60gensym13155461_) >> (NU64)(((NI) 12))) & ((NI32) 63)) | ((NI32) 128))))));		if ((NU)(((NI) 3)) >= (NU)result.len){ raiseIndexError2(((NI) 3),result.len-1); goto BeforeRet_;}		nimPrepareStrMutationV2((&result));
#line 238 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
		nimln_(238, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim");
#line 238 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"

#line 238 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"

#line 238 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"

#line 238 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
		if (((NI32)((NI32)((NI32)((NI64)(iX60gensym13155461_) >> (NU64)(((NI) 6))) & ((NI32) 63)) | ((NI32) 128))) < ((NI) 0) || ((NI32)((NI32)((NI32)((NI64)(iX60gensym13155461_) >> (NU64)(((NI) 6))) & ((NI32) 63)) | ((NI32) 128))) > ((NI) 255)){ raiseRangeErrorI((NI32)((NI32)((NI32)((NI64)(iX60gensym13155461_) >> (NU64)(((NI) 6))) & ((NI32) 63)) | ((NI32) 128)), ((NI) 0), ((NI) 255)); goto BeforeRet_;}		result.p->data[((NI) 3)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI32)((NI64)(iX60gensym13155461_) >> (NU64)(((NI) 6))) & ((NI32) 63)) | ((NI32) 128))))));		if ((NU)(((NI) 4)) >= (NU)result.len){ raiseIndexError2(((NI) 4),result.len-1); goto BeforeRet_;}		nimPrepareStrMutationV2((&result));
#line 239 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
		nimln_(239, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim");
#line 239 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"

#line 239 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"

#line 239 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
		if (((NI32)((NI32)(iX60gensym13155461_ & ((NI32) 63)) | ((NI32) 128))) < ((NI) 0) || ((NI32)((NI32)(iX60gensym13155461_ & ((NI32) 63)) | ((NI32) 128))) > ((NI) 255)){ raiseRangeErrorI((NI32)((NI32)(iX60gensym13155461_ & ((NI32) 63)) | ((NI32) 128)), ((NI) 0), ((NI) 255)); goto BeforeRet_;}		result.p->data[((NI) 4)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)(iX60gensym13155461_ & ((NI32) 63)) | ((NI32) 128))))));	}
	goto LA1_;
	LA20_: ;
	{		NIM_BOOL T23_;
#line 241 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
		nimln_(241, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim");
#line 241 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
		T23_ = (NIM_BOOL)0;		T23_ = lteqpercent___x8ObPz55IkLprSyPyqBSRAsystem(iX60gensym13155461_, ((NI32) 2147483647));		if (!T23_) goto LA24_;

#line 242 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
		nimln_(242, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim");		setLengthStrV2((&result), ((NI) 6));		if ((NU)(((NI) 0)) >= (NU)result.len){ raiseIndexError2(((NI) 0),result.len-1); goto BeforeRet_;}		nimPrepareStrMutationV2((&result));
#line 243 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
		nimln_(243, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim");
#line 243 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"

#line 243 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"

#line 243 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
		if (((NI32)((NI32)((NI64)(iX60gensym13155461_) >> (NU64)(((NI) 30))) | ((NI32) 252))) < ((NI) 0) || ((NI32)((NI32)((NI64)(iX60gensym13155461_) >> (NU64)(((NI) 30))) | ((NI32) 252))) > ((NI) 255)){ raiseRangeErrorI((NI32)((NI32)((NI64)(iX60gensym13155461_) >> (NU64)(((NI) 30))) | ((NI32) 252)), ((NI) 0), ((NI) 255)); goto BeforeRet_;}		result.p->data[((NI) 0)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI64)(iX60gensym13155461_) >> (NU64)(((NI) 30))) | ((NI32) 252))))));		if ((NU)(((NI) 1)) >= (NU)result.len){ raiseIndexError2(((NI) 1),result.len-1); goto BeforeRet_;}		nimPrepareStrMutationV2((&result));
#line 244 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
		nimln_(244, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim");
#line 244 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"

#line 244 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"

#line 244 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"

#line 244 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
		if (((NI32)((NI32)((NI32)((NI64)(iX60gensym13155461_) >> (NU64)(((NI) 24))) & ((NI32) 63)) | ((NI32) 128))) < ((NI) 0) || ((NI32)((NI32)((NI32)((NI64)(iX60gensym13155461_) >> (NU64)(((NI) 24))) & ((NI32) 63)) | ((NI32) 128))) > ((NI) 255)){ raiseRangeErrorI((NI32)((NI32)((NI32)((NI64)(iX60gensym13155461_) >> (NU64)(((NI) 24))) & ((NI32) 63)) | ((NI32) 128)), ((NI) 0), ((NI) 255)); goto BeforeRet_;}		result.p->data[((NI) 1)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI32)((NI64)(iX60gensym13155461_) >> (NU64)(((NI) 24))) & ((NI32) 63)) | ((NI32) 128))))));		if ((NU)(((NI) 2)) >= (NU)result.len){ raiseIndexError2(((NI) 2),result.len-1); goto BeforeRet_;}		nimPrepareStrMutationV2((&result));
#line 245 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
		nimln_(245, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim");
#line 245 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"

#line 245 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"

#line 245 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"

#line 245 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
		if (((NI32)((NI32)((NI32)((NI64)(iX60gensym13155461_) >> (NU64)(((NI) 18))) & ((NI32) 63)) | ((NI32) 128))) < ((NI) 0) || ((NI32)((NI32)((NI32)((NI64)(iX60gensym13155461_) >> (NU64)(((NI) 18))) & ((NI32) 63)) | ((NI32) 128))) > ((NI) 255)){ raiseRangeErrorI((NI32)((NI32)((NI32)((NI64)(iX60gensym13155461_) >> (NU64)(((NI) 18))) & ((NI32) 63)) | ((NI32) 128)), ((NI) 0), ((NI) 255)); goto BeforeRet_;}		result.p->data[((NI) 2)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI32)((NI64)(iX60gensym13155461_) >> (NU64)(((NI) 18))) & ((NI32) 63)) | ((NI32) 128))))));		if ((NU)(((NI) 3)) >= (NU)result.len){ raiseIndexError2(((NI) 3),result.len-1); goto BeforeRet_;}		nimPrepareStrMutationV2((&result));
#line 246 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
		nimln_(246, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim");
#line 246 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"

#line 246 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"

#line 246 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"

#line 246 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
		if (((NI32)((NI32)((NI32)((NI64)(iX60gensym13155461_) >> (NU64)(((NI) 12))) & ((NI32) 63)) | ((NI32) 128))) < ((NI) 0) || ((NI32)((NI32)((NI32)((NI64)(iX60gensym13155461_) >> (NU64)(((NI) 12))) & ((NI32) 63)) | ((NI32) 128))) > ((NI) 255)){ raiseRangeErrorI((NI32)((NI32)((NI32)((NI64)(iX60gensym13155461_) >> (NU64)(((NI) 12))) & ((NI32) 63)) | ((NI32) 128)), ((NI) 0), ((NI) 255)); goto BeforeRet_;}		result.p->data[((NI) 3)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI32)((NI64)(iX60gensym13155461_) >> (NU64)(((NI) 12))) & ((NI32) 63)) | ((NI32) 128))))));		if ((NU)(((NI) 4)) >= (NU)result.len){ raiseIndexError2(((NI) 4),result.len-1); goto BeforeRet_;}		nimPrepareStrMutationV2((&result));
#line 247 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
		nimln_(247, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim");
#line 247 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"

#line 247 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"

#line 247 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"

#line 247 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
		if (((NI32)((NI32)((NI32)((NI64)(iX60gensym13155461_) >> (NU64)(((NI) 6))) & ((NI32) 63)) | ((NI32) 128))) < ((NI) 0) || ((NI32)((NI32)((NI32)((NI64)(iX60gensym13155461_) >> (NU64)(((NI) 6))) & ((NI32) 63)) | ((NI32) 128))) > ((NI) 255)){ raiseRangeErrorI((NI32)((NI32)((NI32)((NI64)(iX60gensym13155461_) >> (NU64)(((NI) 6))) & ((NI32) 63)) | ((NI32) 128)), ((NI) 0), ((NI) 255)); goto BeforeRet_;}		result.p->data[((NI) 4)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI32)((NI64)(iX60gensym13155461_) >> (NU64)(((NI) 6))) & ((NI32) 63)) | ((NI32) 128))))));		if ((NU)(((NI) 5)) >= (NU)result.len){ raiseIndexError2(((NI) 5),result.len-1); goto BeforeRet_;}		nimPrepareStrMutationV2((&result));
#line 248 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
		nimln_(248, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim");
#line 248 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"

#line 248 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"

#line 248 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/unicode.nim"
		if (((NI32)((NI32)(iX60gensym13155461_ & ((NI32) 63)) | ((NI32) 128))) < ((NI) 0) || ((NI32)((NI32)(iX60gensym13155461_ & ((NI32) 63)) | ((NI32) 128))) > ((NI) 255)){ raiseRangeErrorI((NI32)((NI32)(iX60gensym13155461_ & ((NI32) 63)) | ((NI32) 128)), ((NI) 0), ((NI) 255)); goto BeforeRet_;}		result.p->data[((NI) 5)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)(iX60gensym13155461_ & ((NI32) 63)) | ((NI32) 128))))));	}
	goto LA1_;
	LA24_: ;
	{	}
	LA1_: ;
	}BeforeRet_: ;
	popFrame();	return result;}
