/* Generated by Nim Compiler v1.3.3 */
/*   (c) 2020 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w -g  -I/Users/elcritch/.asdf/installs/nim/devel/lib -I/Volumes/datastore/projects/pt/third-party/spryvm/tests -o /Volumes/datastore/projects/pt/third-party/spryvm/tests/_nimcache/stdlib_cpuinfo.nim.c.o /Volumes/datastore/projects/pt/third-party/spryvm/tests/_nimcache/stdlib_cpuinfo.nim.c */
#define NIM_INTBITS 64

/* section: NIM_merge_HEADERS */

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix

/* section: NIM_merge_FRAME_DEFINES */
#define nimfr_(x, y)
#define nimln_(x, y)

/* section: NIM_merge_PROC_HEADERS */

#line 18 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/concurrency/cpuinfo.nim"
#include <sys/types.h>

#line 26 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/concurrency/cpuinfo.nim"
#include <sys/sysctl.h>
